### ISSUE TITLE
Steam logon failed - Unexpected token

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steam-tradeoffer-manager#102]
Hi, sometimes when i try to login with steamcommunity and using steam-tradeoffer-manager, i get Steam login fail: Unexpected token <.
I dont know what happend, but after some time i can login.

**Comment by DoctorMcKay** [comment]
This is the wrong place to ask about login failures. Those are relevant to node-steamcommunity, not to node-steam-tradeoffer-manager.

Anyway, that looks like just Steam being unreliable when you're trying to login. I'll add some more informative error messages.
