### ISSUE TITLE
Limited account

### ISSUE THREAD

**Issue by mig4ng** [DoctorMcKay/node-steam-tradeoffer-manager#103]
Is it possible to send trade offer with a limited account? (Without $5 verification)
I saw csgo double and other sites do it, but I don't know if they use node-steam-tradeoffer-manager

Thanks for the attention and patience

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

No, not with this module.
