### ISSUE TITLE
Error: Unknown input format

### ISSUE THREAD

**Issue by Gremilek** [DoctorMcKay/node-steam-tradeoffer-manager#104]
Hello,
sometimes, but not always, on accept offer I have error and bot crash.
Earlier all works good (I don't change code).
How to fix it?
Thanks.

```
[ERROR] Error: Unknown input format
    at new SteamID (/bot/node_modules/steamid/index.js:101:9)
    at createOfferFromData (/bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:103:38)
    at /bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:94:12
    at Array.map (native)
    at /bot/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:93:63
    at TradeOfferManager.<anonymous> (/bot/node_modules/steam-tradeoffer-manager/lib/assets.js:145:3)
    at /bot/node_modules/async/lib/async.js:52:16
    at /bot/node_modules/async/lib/async.js:361:13
    at /bot/node_modules/async/lib/async.js:52:16
    at done (/bot/node_modules/async/lib/async.js:246:17)
    at /bot/node_modules/async/lib/async.js:44:16
    at /bot/node_modules/async/lib/async.js:358:17
    at /bot/node_modules/steam-tradeoffer-manager/lib/assets.js:135:5
    at /bot/node_modules/async/lib/async.js:52:16
    at done (/bot/node_modules/async/lib/async.js:246:17)
    at /bot/node_modules/async/lib/async.js:44:16
```

**Comment by DoctorMcKay** [comment]
This happens when you accept an offer?

**Comment by Gremilek** [comment]
Sometimes this error I have after offer.accept(...);
Sometimes on manager.on('newOffer', ....); and manager.on('receivedOfferChanged', ...);

I think, on manager.on('newOffer', ....); this error after
`var steamid = offer.partner.getSteamID64();`, but all okay with getting id.

**Comment by autaut03** [comment]
I had the same error. Quick-fixed it in TradeOffer.js class on getOffers method, like this: 
`var sent = (body.response.trade_offers_sent || []).filter(function(data) {
			if(isNaN(data.accountid_other)) return false;
			return true;
		}).map(function(data) {
			return createOfferFromData(manager, data);
		});`

**Comment by shaunidiot** [comment]
Any input on this, @DoctorMcKay ?

**Comment by DoctorMcKay** [comment]
Ugh, Steam is returning offers without an accountid_other?

**Comment by autaut03** [comment]
I checked around 2k trades and all of them had accountid_other.. I think only sometimes steam gives some shit instead of it, however it's not a surprise.. steam is an absolute shit in terms of API and stuff..

**Comment by autaut03** [comment]
And for me it also appeared from nothing. Around one or two months ago everything was fine.

**Comment by DoctorMcKay** [comment]
Okay I think I have a good way to handle this. I'll try to push out an update tonight. 

Out of curiosity, how frequently do you get this?

**Comment by autaut03** [comment]
It's 5 AM and I'm replying u :D Around 5 to 10 times for a 200 trades. Not very often.
