### ISSUE TITLE
Error: Cannot find module 'steam-user'

### ISSUE THREAD

**Issue by darkthefirst** [DoctorMcKay/node-steam-tradeoffer-manager#108]
Error: Cannot find module 'steam-user'

**Comment by andrewda** [comment]
First of all, did you `npm install steam-user`? Also, we're going to need more of a stack trace than that.

**Comment by darkthefirst** [comment]
Ohh. Sorry.

**Comment by darkthefirst** [comment]
Now i did it. And it works

**Comment by darkthefirst** [comment]
Andrew, сan i ask one thing?

**Comment by andrewda** [comment]
Sure

**Comment by darkthefirst** [comment]
How can i make trade offer?

**Comment by wartab** [comment]
It's written in the Wiki.

**Comment by darkthefirst** [comment]
I know it. But how can i sent this offer from php?

**Comment by andrewda** [comment]
This should really be continued in the forum https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/

**Comment by darkthefirst** [comment]
Thank you!
