### ISSUE TITLE
sending offer error

### ISSUE THREAD

**Issue by komarevtsevdn** [DoctorMcKay/node-steam-tradeoffer-manager#109]
TypeError: Cannot convert undefined or null to object
    at TradeOfferManager.<anonymous> (/root/node_modules/steam-tradeoffer-manager/lib/polling.js:68:41)
    at /root/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:97:4
    at TradeOfferManager.<anonymous> (/root/node_modules/steam-tradeoffer-manager/lib/assets.js:166:3)
    at /root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:52:16
    at /root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:361:13
    at /root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:52:16
    at done (/root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:246:17)
    at /root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:44:16
    at /root/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:358:17
    at /root/node_modules/steam-tradeoffer-manager/lib/assets.js:156:5

**Comment by andrewda** [comment]
What's your code? Are you supplying a callback?

**Comment by komarevtsevdn** [comment]
https://jsfiddle.net/nzaxb7qr/ 
i think it error in checkConfirmations()
but i used this function in many my app and error not appeared

**Comment by DoctorMcKay** [comment]
If you believe the error to be in checkConfirmations then there is nothing I can do, as I have no relation to that module at all (and I vaguely recall hearing that it's broken). Although that stack trace isn't consistent with that theory.

Does this happen every time you send an offer?

**Comment by GlebkaF** [comment]
Hello, got same error, my code: 
```
trade.send(tradeMessage, accessToken, function (err, status){
						if (err) {
							offerState = 3;
							debug('Can\'t create offer: ', err.message)
							err.code = err.message.replace(/\D+/g,"");
							if(err.code == '401'){
								debug('Bad cookies, restoring');
								self.client.webLogOn();
							}							
							callback(offerState,trade.id);
						}
						else{
							callback(offerState,trade.id);
							debug('Trade offer sent successfully');
							self.steamCommunity.checkConfirmations()
						}
					});
```
And stack trace:
```
Wed, 09 Mar 2016 06:43:05 GMT steamAuth Trade offer sent successfully
/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/polling.js:68
				delete this.pollData.received[oldIds[i]];
				                                    ^

TypeError: Cannot convert undefined or null to object
    at TradeOfferManager.<anonymous> (/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/polling.js:68:41)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:97:4
    at TradeOfferManager.<anonymous> (/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/assets.js:166:3)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:52:16
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:361:13
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:52:16
    at done (/root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:246:17)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:44:16
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/async/lib/async.js:358:17
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/lib/assets.js:156:5
```
any ideas?

**Comment by DoctorMcKay** [comment]
Can you upload/paste your poll data here please?

**Comment by DoctorMcKay** [comment]
I've found the issue.
