### ISSUE TITLE
getActions

### ISSUE THREAD

**Issue by renesamaral** [DoctorMcKay/node-steam-tradeoffer-manager#111]
How can i use getActions to get the CS:GO inspect link ?

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? Do not create a GitHub issue. GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**
