### ISSUE TITLE
market_hash_name and market_name

### ISSUE THREAD

**Issue by iLuk** [DoctorMcKay/node-steam-tradeoffer-manager#112]
Hi, I would like to know the diffrence between market_hash_name and market_name if there's any.

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

**Comment by DoctorMcKay** [comment]
^^ Please ask there.
