### ISSUE TITLE
Error on accepting offer, while the offer was accepted..

### ISSUE THREAD

**Issue by autaut03** [DoctorMcKay/node-steam-tradeoffer-manager#114]
Hello. I have a problem.. I'm accepting lots of offers a day and sometimes your module returns error while trying to accept some of them.. but in fact they are accepted! So people send offers, bot accepts it and people get nothing, because your module thinks there was an error.. wtf?

**Comment by andrewda** [comment]
It's not the module returning an error, it's Steam. I believe that error 11 and error 2 are some of the culprits, so you should check the EResult and check to see if the offer was actually accepted (or just do everything on offer state change).

**Comment by autaut03** [comment]
How can I check it online? I mean do it when I accept offer, not when some event called..

**Comment by autaut03** [comment]
Nope. That's what happens: Can't accept offer: Error: Cannot load new trade data: Data temporarily unavailable

**Comment by andrewda** [comment]
Alright, that means you're receiving a malformed offer from getOffer(). How often does this occur? I've never experienced it.

**Comment by autaut03** [comment]
Sometimes, not often. Tried to fix it using repeating this.update instead of plain this.update (if offer is already accepted then we should update it anyways)

**Comment by DoctorMcKay** [comment]
You shouldn't rely on the callback to accept as the only way to figure out if an offer was accepted. You should use the `receivedOfferChanged` event as the final say, and the callback as just a way to find out sooner if you get a successful response.

I thought this was already the case, but as of the next version the manager will queue an immediate poll when you call accept() and it succeeds.

**Comment by autaut03** [comment]
When I have around 5 trades every 30 seconds I just can't wait minutes until it's being accepted and event fired. It's a bad way of doing things. U must call callback when the offer is accepted as the wiki explains but receivedOfferChanged must not.

**Comment by DoctorMcKay** [comment]
>I just can't wait minutes

You can and you will.

**Comment by autaut03** [comment]
No, I cant.

Then it would be much easier to rewrite this module. Also it's a big question why u update the status of the trade when it's accepted.. useless part of the code.

**Comment by DoctorMcKay** [comment]
You are very welcome to rewrite the module to suit your needs. However, I think you'll find that given the nature of Steam, you won't get everything you want.

The offer needs to be updated when it's accepted because there is data that can be necessary which isn't returned in the accept request. Specifically escrow_end_date, whether or not it went into escrow at all, last update time, and more.

**Comment by autaut03** [comment]
Then it would be clever to add some directive, and if it's false just skip this part of code.. but anyways, seems like I fixed it with repeating this.update on failure, so the ticket is closed. Thank u for replies =)
