### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by centrual** [DoctorMcKay/node-steam-tradeoffer-manager#116]
Hello,

Thanks for updates, you are really good!
Today i updated libraries to latest, but after update libraries , my program had memory leak problem. I know it's about libraries, because i using my script for 2 week and it's used only 200 mb ram max in week.

Currently program ram usage going bigger and bigger. ( i saw 1.4 gb ram usage and restarted )
If you know one way for which function causes memory leak etc. can you tell me?

Thank you so much.

I'm using this libraries:

```
var mysql			= require("mysql"),
	steamCommunity	= require("steamcommunity"),
	steamUser		= require("steam-user"),
	tradeOffers		= require("steam-tradeoffer-manager"),
	totp			= require("steam-totp"),
	bigNumber		= require("bignumber.js"),
	mkdirp			= require("mkdirp"),
	fs				= require("fs"),
	request			= require("request"),
	pusher 			= require("pusher"),
	jsonParser		= require("json3"),
	q				= require("q"),
	onceler			= require('onceler').TOTP;
```

**Comment by DoctorMcKay** [comment]
This isn't really the place to ask this (and I'm not sure what kind of information you think I'd have for so many modules).
