### ISSUE TITLE
Error: Unknown input format

### ISSUE THREAD

**Issue by GlebkaF** [DoctorMcKay/node-steam-tradeoffer-manager#119]
Hello, recently  I getting this error for no reason, I mean that there is no any events ( like poolFailure, newOffer etc.) preceding it, trace:
```
/root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/steamid/index.js:101
		throw new Error("Unknown input format");
		^

Error: Unknown input format
    at new SteamID (/root/csgoGame/node_modules/steam-tradeoffer-manager/node_modules/steamid/index.js:101:9)
    at createOfferFromData (/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:120:38)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:107:12
    at Array.map (native)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:106:63
    at checkNeededDescriptions (/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:169:3)
    at /root/csgoGame/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:96:3
    at SteamCommunity.<anonymous> (/root/csgoGame/node_modules/steam-tradeoffer-manager/lib/webapi.js:46:3)
    at Request._callback (/root/csgoGame/node_modules/steamcommunity/components/http.js:62:14)
    at Request.self.callback (/root/csgoGame/node_modules/request/request.js:199:22)
```

**Comment by DoctorMcKay** [comment]
What version are you running?

**Comment by ylms** [comment]
I was just came to write same thing. I recently updated all your modules and my nodejs version. And this is what started to happening.

**Comment by DoctorMcKay** [comment]
@GlebkaF or @ylms: Can you please pastebin/gist the output of GetTradeOffers for the account that's experiencing this issue?

**Comment by ylms** [comment]
steam-tradeoffer-manager/node_modules/steamid/index.js:101
        throw new Error("Unknown input format");
        ^

Error: Unknown input format

**Comment by DoctorMcKay** [comment]
I mean this:

https://api.steampowered.com/IEconService/GetTradeOffers/v1/?get_sent_offers=1&get_received_offers=1&key=your_accounts_api_key

**Comment by GlebkaF** [comment]
@DoctorMcKay I'm using 1.21.3 version. 
[GetTradeOffers.txt](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/files/183506/GetTradeOffers.txt)

**Comment by DoctorMcKay** [comment]
Does this error happen frequently? Rarely? All the time?

**Comment by GlebkaF** [comment]
Four times in last 24 hours.

**Comment by DoctorMcKay** [comment]
Frustrating that it isn't happening consistently. Can you tell whether it's happening as the result of a call you're making, or as the result of a poll?

**Comment by GlebkaF** [comment]
Seems like it's result of poll, because there is no any call of my functions in stack trace. But I'm not sure

**Comment by DoctorMcKay** [comment]
Alright I'll see what I can do.

**Comment by ylms** [comment]
Downgrading to old version seems to be fixed my problem just for now.

**Comment by DoctorMcKay** [comment]
Try v1.21.4 and see if you're still having an issue.

**Comment by ylms** [comment]
Did not have any issue on the udpated version. I will keep it updated. But the updated version seems to be more buggy with many malformed responses from trades. Somehow.

**Comment by DoctorMcKay** [comment]
How frequently do you get malformed responses? About as frequently as you got crashes? Because that's the alternative.

**Comment by ylms** [comment]
I used to get them when my cookie got expired after a day. But after the update I started to get those errors while handling offers (I wasn't logged off).

I didn't have much chance to test it, but that was my first impressions on the latest update. I will be able to tell how fequently it is happening tomorrow.

Also I have got some errors like ERRTIMEDOUT.

**Comment by DoctorMcKay** [comment]
Sounds like all that was just a product of how awfully unstable Steam has been today and last night.

**Comment by ylms** [comment]
After few days of testing the problem seems to be fixed.
