### ISSUE TITLE
Extremely high memory usage post-update

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steam-tradeoffer-manager#120]
Hi, I recently updated my libs and noticed that memory usage is pretty excessive now. As if something was blocking GC.  Particularly since the following screenshot does not do anything besides log the bot in and doesn't use any of the builtin confirmation checking stuff or things of that nature. Don't know if this is a known issue so apologies for double post if so, but couldn't find any other related issues.

![mem](https://cloud.githubusercontent.com/assets/2509793/13955130/24f87df2-f009-11e5-892c-1365652ec21f.png)

Unfortunately I'm finding it very hard to do any actual testcase here because the libs are all needed, and it's not obvious where it's coming from. I can guarantee that this is a regression between a certain HEAD (I can provide on request, have to find the package.json) and the current releases because there is another running instance that does much more than log in the bot, and much more than 1 bot but with memory usage that is roughly 1/3rd of what is showing above. It uses one of the aforementioned heads rather than a release.

**Edit**: Here are the relevant heads:

* `node-steam-tradeoffer-manager.git#e8ce210458126e976cb8c2bb681838d8af0b870f`
* `node-steam-user.git#bcde608c2a8127eaea8ecc212d9e4c6b1827a2b8`
* `node-steamcommunity.git#87e3665b0126b9492174a16352853f079f1c6127`

**Comment by DoctorMcKay** [comment]
You're deploying from GitHub? That's a bad idea.

**Comment by Lagg** [comment]
Yes, but at the time I had first started pulling your stuff there were bugs on all party's end. So you know. But yeah that was why I was trying to move to the proper versions.

**Comment by DoctorMcKay** [comment]
Please update to the latest npm version and let me know if the issue persists.

**Comment by Lagg** [comment]
All are running latest except for the shot I'm about to show (and I don't know how useful this will be, but bisecting isn't helping me because I don't know the code well enough. So it's all I can think to offer for the moment). This instance is using the aforementioned heads. This one has much longer uptime, more logins and isn't just sitting there nooping like the previous one given.

![mem](https://cloud.githubusercontent.com/assets/2509793/13957884/a96439c8-f013-11e5-9e51-84f469726ae5.png)

To confirm, the versions running where I'm exhibiting the high memory usage are:

steam-tradeoffer-manager: 1.21.3
steamcommunity: 3.19.3
steam-user: 3.3.4

**Comment by Lagg** [comment]
I just found this poking around npmjs: https://www.npmjs.com/package/memwatch

Looks promising, the leak detect algo looks simple and would seem to fit what is being observed here. I'm going to add this to my stuff and relaunch when I can and see what happens. Maybe it'd also be worth doing the same on your working tree @DoctorMcKay

**Comment by Lagg** [comment]
Another quick update. I don't know if this is a successful reproduction or what, but I noticed an immediate an obvious spike when `getConfirmations` was called (confirmation checker was not started) and errors out:

```
GC stats num_full_gc=12, num_inc_gc=388, heap_compactions=12, usage_trend=3474.3, estimated_base=123456926, current_base=109299464, min=81897024, max=137962168
Error fetching confirmations: ETIMEDOUT
GC stats num_full_gc=13, num_inc_gc=458, heap_compactions=13, usage_trend=0.3, estimated_base=125703979, current_base=145927456, min=81897024, max=145927456
```

Note the heap max. Before the socket timeout it was sitting at 137962168 for several GC cycles.

**Comment by Lagg** [comment]
@DoctorMcKay Are there any instances of global usage in getConfirmations worth knowing about, and is there any way I could myself be blocking GC by keeping a reference to something in the callback body?

**Comment by DoctorMcKay** [comment]
There isn't anything global in `getConfirmations`, no.

Is node up to date?

**Comment by Lagg** [comment]
`node -v` returns 5.5.0 , not quite bleeding edge but yeah more or less.

**Comment by someazndude** [comment]
I had a similar problem. Was able to fix by manually calling global.gc() every so often or reverting steamcommunity's cheerio dependency to cheerio@0.19.0. It seems like the latest version of cheerio isn't being automatically cleaned up after getting confirmations.

**Comment by Lagg** [comment]
Oooouch, manually firing gc? Is there anything you can do to workaround the issue here @DoctorMcKay if that's the case? I understand the importance of cheerio to this stuff, but perhaps there's some sort of call you can make use of to make it flush its tree or something.

**Comment by Lagg** [comment]
Well after leaving the simplified test case running all night (there was basically nothing there but the getConfirmations body) it's at 1021M currently. There's surely something in there being kept referenced.

**Comment by someazndude** [comment]
Which version of cheerio were you using for the test case?

**Comment by DoctorMcKay** [comment]
Update steamcommunity (which downgrades cheerio) and see if you still have issues.

**Comment by Lagg** [comment]
Done, will let you know what comes of it, and I don't know if I can tell anymore @someazndude . But the version used in my own stuff is 0.19.0. 

Confirming updated versions:

```
├── steam-tradeoffer-manager@1.21.4
└── steamcommunity@3.19.4
```

**Comment by Lagg** [comment]
@DoctorMcKay I don't know if this could be related, but I also removed a check for the "steammobile:" (or "Not Logged In" in the case of recent versions) error that did webLogOn when it occurred. I've noticed that 90% of the time these don't actually happen because of bad sessions and doing it too much leads to a throttle so I'm not sure it makes sense anymore to have around, at least not in that particular error case.

**Comment by Lagg** [comment]
Alright, still going to let it run through the night because it hasn't been all that long in terms of what you'd expect from a daemon's uptime. But so far results are looking good. This is after running it since shortly after I posted the last response:

![image](https://cloud.githubusercontent.com/assets/2509793/14007370/a1b10796-f13b-11e5-9ae6-1393224211ff.png)

**Comment by Lagg** [comment]
Currently at 146M after running all night, so I guess the issue is fixed.

**Comment by DoctorMcKay** [comment]
Good. Let me know if there are any more issues.
