### ISSUE TITLE
Is there way to cancel an offer when we get error 16 as result.

### ISSUE THREAD

**Issue by ylms** [DoctorMcKay/node-steam-tradeoffer-manager#122]
Hello,
So the problem is sometimes when the bot sends an offer to user, sometimes steam sends "Error 16" as result. But this means the offer might be gone, or not at all. And since it returns an error it is not really giving a tradeid number. So there is no way to cancel it or track it as much as I know. So is there any way about it?

**Comment by DoctorMcKay** [comment]
https://dev.doctormckay.com/topic/188-handling-errors-upon-sending-offer/#entry303
