### ISSUE TITLE
Can I use historicalCutOff with GetOffer?

### ISSUE THREAD

**Issue by ylms** [DoctorMcKay/node-steam-tradeoffer-manager#124]
Hello,

Sometimes some of my trades are getting stucked on "confirmation" phase. So what I am doing is polling getoffer function and getting offers statements and if they are on confirmation canceling and resend.

But sometimes polling instantly checks the statement so it is canceling the offer without letting confirmation poll to confirm it. I think it would be more healthy if I could use historicalCutOff with GetOffer, if it is possible?

**Comment by DoctorMcKay** [comment]
No. You can always perform the check locally.

Please direct future questions to the [forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).
