### ISSUE TITLE
Get Steamname in receivedOfferChanged

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#126]
Hi, how i can get the Steamname of the user the betted in receivedOfferChanged?

I had 
`offer.partner.getSteamID64()` 
there i get the SteamID64...
but idk how i can get his username... can you help me here?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You need to use the [WebAPI](https://lab.xpaw.me/steam_api_documentation.html#ISteamUser_GetPlayerSummaries_v2).
