### ISSUE TITLE
[SUGGESTION] Checking if item is in trade

### ISSUE THREAD

**Issue by Infrox** [DoctorMcKay/node-steam-tradeoffer-manager#128]
I ran into this issue today, couldn't find a good way to do it. You could add following function:
```
isItemInTrade(assetid,callback(err,data))
err - Error
data - 1 if in any trade, 0 if not found.
```

I mean I have the assetID of an item, and I need to check if bot has sent an offer with this item to someone. That would be helpful because you can check an item before sending the actual offer.

**Comment by autaut03** [comment]
Please dont do it cuz then I would need to remove my own system for this D:

**Comment by andrewda** [comment]
I think the best way to do this would be to keep an array of all assetids sent in the polldata, making the polldata.json file itself much larger, though that shouldn't matter too much. This would certainly be a handy feature, if possible.

@autaut03 Uhh... You wouldn't have to remove your own system... What @Infrox is suggesting would just make it much easier for everyone.

**Comment by DoctorMcKay** [comment]
I don't want to store a bunch of assetids in poll data. I'm thinking about just making it check the API for an active offer which contains the item(s).

**Comment by andrewda** [comment]
:+1: Sounds good to me!

**Comment by autaut03** [comment]
@DoctorMcKay That's a good idea, but it will cause major lags (each time before sending u will have to check the items) and u dont have to store all of this assetIDs. When the offer is accepted or canceled u can remove these assetIDs from the list. It works perfectly on my servers.

**Comment by DoctorMcKay** [comment]
I'll push that out in a new version to npm later on today (if I remember).

**Comment by andrewda** [comment]
@autaut03 The way @DoctorMcKay did this should be fast enough. All it does is make a single request to `getOffers()` and then check whether they contain the items you specify.
