### ISSUE TITLE
API Key Woes

### ISSUE THREAD

**Issue by WeeSkilz** [DoctorMcKay/node-steam-tradeoffer-manager#13]
I was wondering where the api key is stored. I revoked the one I was using but it is now saved and I was wondering how to remove it, and if you could add it to the wiki for future reference.

Thanks

**Comment by DoctorMcKay** [comment]
It's retrieved from Steam automatically on startup. Just restart your bot and it should get the new one.

**Comment by WeeSkilz** [comment]
After changing the domain supplied in the constructor, it still uses the same api key. Any way I can ensure that it is fetching a new one?

**Comment by WeeSkilz** [comment]
Steam locks an api key to an account. Another account changed the key.

**Comment by DoctorMcKay** [comment]
I have no idea what you're saying that your issue was, but I'm glad that you resolved it.

**Comment by WeeSkilz** [comment]
Issue was caused by the assetid changing in the trade, the fix was detailed in my newer issue.
