### ISSUE TITLE
unknownOfferSent trigger on every offer i sent

### ISSUE THREAD

**Issue by speedone** [DoctorMcKay/node-steam-tradeoffer-manager#130]
I have some troubles with awful duplicated offers by steam. 
So i found the 'unknownOfferSent' event. But for me the event trigger on every offer i send.
Is there a bug or is it possible i understand/make something wrong?

I save pollings and restore pollings after restart.

**Comment by DoctorMcKay** [comment]
Are you sending the offers from the same offer manager?

**Comment by ylms** [comment]
+ restoring pollings after restart will cancel all old pending trades.

**Comment by speedone** [comment]
> Are you sending the offers from the same offer manager where you're getting the events?

Yeah i do. In the meantime i check the unknown offers in this event for myself if its really not my offer with database (with a timeout but thats not the best solution..).Sometimes this event get triggered for normal offers i sent. I have no idea why.

**Comment by DoctorMcKay** [comment]
Could you maybe add a `console.log` inside of the callback to `send()` and also inside of `unknownOfferSent` with timestamps and show me the output?

**Comment by speedone** [comment]
Here is a case from yesterday from my logging.
2016-04-17T18:15:18.343Z - Trade will be send now. (before send())
2016-04-17T18:15:23.730Z - unknownOfferSent call
2016-04-17T18:15:30.602Z - Trade offer sent and awaiting confirmation. (callback of send())

**Comment by DoctorMcKay** [comment]
This happens for **every offer**? What's your poll interval?

**Comment by speedone** [comment]
No not for all offers, only sometimes (no idea how often, because i try to prevent a cancel of my offers with a timeout in unknownOfferSent (4 seconds) and then after this time i check the offerid from my database. (callback of send() write offerid in trading table)
But for this case the unknownOfferSent is so early that my trade was canceled because offerid information from send() callback was very late

2016-04-17T18:15:18.343Z - Trade will be send now. (before send())
2016-04-17T18:15:23.730Z - unknownOfferSent call
2016-04-17T18:15:30.602Z - Trade offer sent and awaiting confirmation. (callback of send())

**Comment by DoctorMcKay** [comment]
>unknownOfferSent trigger on every offer i sent

>So i found the 'unknownOfferSent' event. But for me the event trigger on every offer i send.

In the future if you want me to actually fix an issue, don't lie.

**Comment by speedone** [comment]
At first glance it looked like to me that it is every offer, because it happened a few times after another. (maybe also many older offers) I want to help with that report of issues.
It surprises me a little that these errors are not reportet by others.
