### ISSUE TITLE
getReceivedItems auto retry.

### ISSUE THREAD

**Issue by broomop** [DoctorMcKay/node-steam-tradeoffer-manager#131]
In reference to this:

https://dev.doctormckay.com/topic/246-couldnt-get-received-items-error-http-error-503/

is it possible to have a auto retry flag built into the 'getReceivedItems' ?

**Comment by autaut03** [comment]
Just write own small repeating module and use it like this:

`functionRepeatIfError(function(err) {
  //blabla
  if(err) return err;
});`

**Comment by DoctorMcKay** [comment]
Closing this because `getReceivedItems` is deprecated.
