### ISSUE TITLE
update newest version on npm

### ISSUE THREAD

**Issue by titanco** [DoctorMcKay/node-steam-tradeoffer-manager#132]
Hello,
I want to try install v1.22 but on npm is v1.21.4.
How can i get 1.22 ?

**Comment by andrewda** [comment]
Why can't you just install it via GitHub...? NPM will most likely be updated soon.

**Comment by titanco** [comment]
Ok, installed via Github, i just prefer using npm.
Closing.

**Comment by DoctorMcKay** [comment]
Sorry, my bad. I've published 1.22.0.

FYI, it's not a great idea to install from GitHub as I don't guarantee that GitHub will always be in a usable state.
