### ISSUE TITLE
PollFailure error.

### ISSUE THREAD

**Issue by ylms** [DoctorMcKay/node-steam-tradeoffer-manager#134]
Hello there,
So I am having poll failure error according to my logs and my bot does nothing after poll failure, even though it accepted the trade offer.

Here is the issued logs,
{"level":"debug","message":"#1 - Received new offer: - 1146841042","timestamp":"2016-04-10T03:26:01.792Z"}
{"level":"debug","message":"#7 - Offer # - 1146841042 accepted from 76561198074956634","timestamp":"2016-04-10T03:26:12.168Z"}
{"level":"debug","message":"!! POLL FAILURE ERROR !!: Error: Timeout","timestamp":"2016-04-10T03:26:14.464Z"}

**Comment by DoctorMcKay** [comment]
And it literally does nothing else ever? It stops polling completely?

**Comment by ylms** [comment]
There is not really a pattern. Sometimes it completely stops polling the issued trade offer, sometimes it does not.

**Comment by DoctorMcKay** [comment]
It stops polling entirely? It no longer checks any other offers until you restart? Or just that particular offer that stops being tracked?

**Comment by ylms** [comment]
Only particular offer, which issued error.

**Comment by DoctorMcKay** [comment]
I don't understand. It seems to me that you're seeing `newOffer` get emitted for 1146841042, then `receivedOfferChanged` for 1146841042 after it got Accepted. How could it change further?

**Comment by andrewda** [comment]
@DoctorMcKay I'm guessing that ` {"level":"debug","message":"#7 - Offer # - 1146841042 accepted from 76561198074956634","timestamp":"2016-04-10T03:26:12.168Z"} ` is logged from the callback of `.accept()` and not from `receivedOfferUpdated`, because the problem he's experiencing that `receivedOfferUpdated` isn't firing when there's a poll failure.

**Comment by ylms** [comment]
^ Andrew.

**Comment by ylms** [comment]
@DoctorMcKay 


{ Error: Timeout
    at SteamCommunity.<anonymous> (/root/bot/node_modules/steam-tradeoffer-manager/lib/webapi.js:35:16)
    at Request._callback (/root/bot/node_modules/steamcommunity/components/http.js:62:14)
    at Request.self.callback (/root/bot/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/bot/node_modules/request/request.js:1041:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/root/bot/node_modules/request/request.js:968:12)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7) eresult: '16' }

**Comment by DoctorMcKay** [comment]
What's the value for that offer id in polldata.json?

Also, can you please bind a listener to the `debug` event and log that?

**Comment by ylms** [comment]
```
{"level":"debug","message":"#1 - Received new offer: - 1446223003 - 76561198137983729","timestamp":"2016-08-09T19:14:01.080Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1444522403 from poll data","timestamp":"2016-08-09T19:14:04.079Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1444528608 from poll data","timestamp":"2016-08-09T19:14:04.080Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445460811 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445461622 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445461690 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445461792 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445462935 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445463474 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445463572 from poll data","timestamp":"2016-08-09T19:14:04.084Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445464332 from poll data","timestamp":"2016-08-09T19:14:04.085Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445464941 from poll data","timestamp":"2016-08-09T19:14:04.085Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445466167 from poll data","timestamp":"2016-08-09T19:14:04.085Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1445466184 from poll data","timestamp":"2016-08-09T19:14:04.085Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Cleaning up stale offer #1446223003 from poll data","timestamp":"2016-08-09T19:14:04.125Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Doing trade offer poll since 1470768167","timestamp":"2016-08-09T19:14:05.130Z"}
{"level":"debug","message":"Tradeoffer-Manager Debug: Doing trade offer poll since 1470768167","timestamp":"2016-08-09T19:14:06.979Z"}
{"level":"debug","message":"#7 - Offer # - 1446223003 accepted from 76561198137983729","timestamp":"2016-08-09T19:14:07.589Z"}
```

@DoctorMcKay The bot cleans trade offer from poll data even tho the process wasn't even finished yet.

**Comment by ylms** [comment]
@DoctorMcKay It does still persists, I gave you udpatd info on the other issue.
