### ISSUE TITLE
 [Error: Unknown state 2]

### ISSUE THREAD

**Issue by Xeroner** [DoctorMcKay/node-steam-tradeoffer-manager#136]
Hi there, every single time i'm accepting an offer ive got :  [Error: Unknown state 2]

My script :

`offer.accept(function (err) {
                            if(err) {
                                console.log(err);
                            }
});`

Offer is accepting, but with error :((

**Comment by trzyrazyzero** [comment]
I think its just steam bug, your offer will be accepted even if this error shows up.
This error comes for all my trades.

**Comment by andrewda** [comment]
As @trzyrazyzero said, this is most likely just a Steam issue. Steam is responding and telling us that the offer is active, when it really has been accepted. The only way to really handle this is by using the `receivedOfferChanged` event after accepting the offer, and checking if the state is accepted from there.

**Comment by Xeroner** [comment]
Ok thanks for help :)) :+1:

**Comment by DoctorMcKay** [comment]
Sorry, it's a bug on my end and is fixed in v1.22.3.

**Comment by Xeroner** [comment]
So just need to update? :)

**Comment by DoctorMcKay** [comment]
Yes.
