### ISSUE TITLE
sentOfferChanged duplicate offers in progression.

### ISSUE THREAD

**Issue by MakeCodeNotCss** [DoctorMcKay/node-steam-tradeoffer-manager#138]
**Got some issue with sentOfferChanged. I dont mind of this logs but my sql queries duplicates too. v 1.22.0. 
Some console logs:**
Offer 1188194886 sent
Checking confirmations
Checking confirmations
Checking confirmations
Checking confirmations
Offer 1188194886 changed status: Active -> Accepted
Query success
Checking confirmations
Checking confirmations
Offer 1188199781 sent
Checking confirmations
Checking confirmations
Offer 1188199781 changed status: Active -> Accepted
Offer 1188199781 changed status: Active -> Accepted
Query success
Query success
Checking confirmations
Checking confirmations
Checking confirmations
Checking confirmations
Offer 1188205510 sent
Checking confirmations
Checking confirmations
Offer 1188205510 changed status: Active -> Accepted
Offer 1188205510 changed status: Active -> Accepted
Offer 1188205510 changed status: Active -> Accepted
Query success
Query success
Query success
Checking confirmations
Checking confirmations
Checking confirmations
Offer 1188210333 sent
Checking confirmations
Checking confirmations
Checking confirmations
Checking confirmations
Checking confirmations
Checking confirmations
Offer 1188210333 changed status: Active -> Accepted
Offer 1188210333 changed status: Active -> Accepted
Offer 1188210333 changed status: Active -> Accepted
Offer 1188210333 changed status: Active -> Accepted

**Comment by darkwar123** [comment]
I think it's your mistake with setInterval, maybe

**Comment by MakeCodeNotCss** [comment]
if u mean pollInterval, i got 20000ms delay, is that to often polling?

**Comment by darkwar123** [comment]
Can you show how you handle the event "sentOfferChanged"?

**Comment by MakeCodeNotCss** [comment]
yep!
manager.on('sentOfferChanged', function(offer, oldState) {

					console.log("Offer " + offer.id + " changed status: " + TradeOfferManager.getStateName(oldState) + " -> " + TradeOfferManager.getStateName(offer.state));

					if (offer.state == TradeOfferManager.ETradeOfferState.Accepted) {

						offer.getReceivedItems(function(err, recievedItems) {

							if (err) {

								console.log("Couldn't get received items: " + err);
								throw err;

							} else {

								recievedItems.forEach(function (item, index) {

									var img_url = hack_getImgUrl(item);

									var insertData = {
										bot_steam_id: item.owner.toString(),
										owner_steam_id: partnerSID64.toString(),
										market_hash_name: item.market_hash_name.toString(),
										asset_id: item.id.toString(),
										img_src: img_url.toString()
									};

									db_connection.query('INSERT INTO osc_bot_inventory SET ?', insertData,
										function(err, rows, fields) {
										if (!err) {
											console.log('Query success');
										} else {
											console.log('Error while performing Query. Details: '+err);
											throw err;
										}
									});
								});
							}
						});
					}
				});
		}

**Comment by darkwar123** [comment]
There are no mistakes, but you are likely to assign handling of this event several times. In outer part of this code.

**Comment by MakeCodeNotCss** [comment]
i could show something:
**Here is the part where i`m calling this method:**
app.post('/sendNewOffer', function(req, res) {

	var de_partner = new Buffer(req.body.partner, 'base64').toString();
	var de_token = new Buffer(req.body.token, 'base64').toString();
	var de_items = [];
	req.body.items.forEach(function(de_val, de_index){
		de_items.push( new Buffer(de_val, 'base64').toString() );
	});

	getPlayerItems(de_partner, de_token, de_items);
});
**And here is the current method, where i`m trying to poll for accept:**
function getPlayerItems(partner, token, items) {

	var offer = manager.createOffer("[U:1:"+partner+"]");
	items.forEach(function (assetid, index) {
		offer.addTheirItem({
			"appid": 730,
			"contextid": 2,
			"assetid": assetid
		});
	});

	//convert partnerID to SteamID64
	var partnerID64 = new SteamID("[U:1:"+partner+"]");
	var partnerSID64 = partnerID64.getSteamID64();
	//end of convert

	//unresolved var name hack
	function hack_getImgUrl(item) {
		return item.icon_url_large;
	}
	//

	//Recieve player items
	offer.send("**********", token, function(err, status) {

		if (err) {
			console.log("There`s an error while sending offer. Details: " + err);
		} else {
			console.log("Offer " + offer.id + " " + status);
**And further my event goes on...**

**Comment by darkwar123** [comment]
You declare the event in "getPlayerItems" function?

**Comment by MakeCodeNotCss** [comment]
Yeah, i thought that it`s logic to declare event only when i got my trade accepted. sry me for being newbie, but ima in JS and node about few weeks.

**Comment by darkwar123** [comment]
It is our own bad experience that is a lesson to us not to repeat our mistakes. :-)

**Comment by MakeCodeNotCss** [comment]
And sometimes we need some advisers near. Thnx a lot.

**Comment by slowas** [comment]
Hi, I have the same problem. My offer is repeating in "sentOfferChanged". Where found solution? Server response https://imgur.com/a/bcKAY  Code:

`	for (var i = 0; i < bots.length; i++) {
		var kc = bots[i];

		//bots[i].instances.manager.on("debug", console.log);

		// pool data
		bots[i].instances.manager.on('pollData', function(data) {
			fs.writeFile(__dirname +'/cache/polls/' + kc.ids + '.json', JSON.stringify(data), (error) => {
				if(error) {
					console.log(color.red(error));
				}

				console.log(color.green('Pooling data to cache'));
			});
		});;
		
		// if sent offer cheanged
		bots[i].instances.manager.on('sentOfferChanged', function(offer, oldState) {
			
			// status changed
			console.log(color.magenta(`Offer #${offer.id} changed: ${TradeOfferManager.ETradeOfferState[oldState]} -> ${TradeOfferManager.ETradeOfferState[offer.state]}`));
			console.log(color.yellow("checking offer status with offer id: " + offer.id));

			// searching offer information from mysql
			db.query("SELECT transactions.*,users.*,users.id as userID FROM transactions LEFT JOIN users ON users.id = transactions.user_id WHERE trade_offer = " + mysql.escape(offer.id) + " LIMIT 1", function(err, rows, results) {
				if(err) {
					console.log('Mysql ERROR: ', err);
					if(err.code === 'PROTOCOL_CONNECTION_LOST') {
						database();
						error(9, socket, true);
					}
				} else {
					if(rows[0].trade_offer !== null && rows[0].trade_offer !== undefined) {
						// searching offers user
						console.log(color.yellow("Offer finded #" + rows[0].trade_offer + ". Checking status."));
						
						if(rows[0].status == "pedding") {
							switch(rows[0].action) {
								case "deposit":
									if (TradeOfferManager.ETradeOfferState[offer.state] == "Accepted") {

										// updating transactions to success
										db.query("UPDATE transactions SET status = 'success' WHERE trade_offer = " + mysql.escape(rows[0].trade_offer), function(err,row, results) {
											if(err) {
												console.log('Mysql ERROR: ', err);
												if(err.code === 'PROTOCOL_CONNECTION_LOST') {
													database();
													error(9, socket, true);
												}
											} else {
												rows[0].status = 'success';
												console.log(color.green("Transaction succesfuly updated to success"));
											}
										});
										
										// update balance in server side
										rows[0].money = rows[0].money + rows[0].value;
										
										// update balance in database
										db.query("UPDATE users SET money = ?, wd_limit = ?, wd_limit_betted = ?,deposited = ? WHERE id = ?", [rows[0].money,  rows[0].value, 0, true, rows[0].user_id], function(err) {
											if(err) {
												console.log('Mysql ERROR: ', err);
												if(err.code === 'PROTOCOL_CONNECTION_LOST') {
													database();
													error(9, socket, true);
												}
											} else {
												let user = findUserByUser(rows[0].user_id);
												if(user) {
													// updated local balance
													user.balance = user.balance + rows[0].value;
													
													// update wilddraw limit
													user.wd_limit = rows[0].value;
													user.wd_limit_betted = 0;
												
													// update user information
													io.to(user.id).emit('status', {
														id: user.id,
														balance: user.balance,
													});

													// removing offer from user local variable
													for (var i = user.offers.length - 1; i >= 0; i--) {
														if(user.offers[i].id === offer.id) {
															user.offers.splice(i, 1);
															break;
														}
													}

													io.to(user.id).emit("offer message", {
														offers: user.offers,
														type: "deposit",
													})

													user.deposited = true;

													console.log(color.green("User balance is updated."));

													io.to(user.id).emit('ServerSuccess',{
														message: 'You balance added +' + rows[0].value + '$',
													});
												} else {
													console.log(color.red("User is offline"));
												}
												/*
												helper.getInvetoryInfo(kc.steamid).then(data => {
													console.log("Data: " + data.data.length);
					
													// write to cache to bot
													if(data.data.length !== 0 || data.data !== undefined) {
														fs.writeFile(__dirname + '/cache/bots/' + data.user + '_inv.txt', JSON.stringify(data.data), function(err) {
															if(err) {
																return console.log(err);
															}
															console.log(color.green("[BOT][INVETORY] The bot invetory has been updated."));
														});
					
													} else {
														console.log(color.red("Error, inventory not loaded by bot #" + data.user));
													}
												});*/
											}
										});													
									}
								break;
								case "wilddraw":
									if (TradeOfferManager.ETradeOfferState[offer.state] == "Accepted") {
										// update balance in server side
										rows[0].money = rows[0].money - rows[0].value;
										
										let user = findUserByUser(rows[0].user_id);
										if(user) {
											for (var i = user.offers.length - 1; i >= 0; i--) {
												if(user.offers[i].id === offer.id) {
													user.offers.splice(i, 1);
													break;
												}
											}

											io.to(user.id).emit("offer message", {
												offers: user.offers,
												type: "willdraw",
											});

									
										} else {
											console.log(color.red("[server] User is offline"));
										}
												

										// update bot invetory
										/*
										helper.getInvetoryInfo(kc.steamid).then(data => {
											console.log("Data: " + data.data.length);
			
											// write to cache to bot
											if(data.data.length !== 0 || data.data !== undefined) {
												fs.writeFile(__dirname + '/cache/bots/' + data.user + '_inv.txt', JSON.stringify(data.data), function(err) {
													if(err) {
														return console.log(err);
													}
													console.log(color.green("[BOT][INVETORY] The bot invetory has been updated."));
												});
			
											} else {
												console.log(color.red("Error, inventory not loaded by bot #" + data.user));
											}
										});*/



										// if offer accepted update transaction status to success
										db.query("UPDATE transactions SET status = 'success' WHERE trade_offer = " + mysql.escape(rows[0].trade_offer), function(err) {
											if(err) {
												console.log('Mysql ERROR: ', err);
												if(err.code === 'PROTOCOL_CONNECTION_LOST') {
													database();
													error(9, socket, true);
												}
											} else {
												console.log(color.green("Transaction succesfuly updated to success"));
												
											}
										});
										
									}
								break;
							}
							
						} else {
							console.log("[Hacking] Trying get a free coins");
						}
					
					} else {
						error(16, socket);
					}
				}
			});	
		});`
