### ISSUE TITLE
Cannot decline a counter-offer

### ISSUE THREAD

**Issue by sbryant31** [DoctorMcKay/node-steam-tradeoffer-manager#139]
When an offer is countered (status = 4) you can't decline it 

```
break in node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:534
 532 	if (this.state != ETradeOfferState.Active && this.state != ETradeOfferState.CreatedNeedsConfirmation) {
 533 		Helpers.makeAnError(new Error("Offer #" + this.id + " is not active, so it may not be cancelled or declined"), callback);
>534 		return;
 535 	}
```

Sometimes a bot needs to decline a trade offer when it is countered by a user.

**Comment by DoctorMcKay** [comment]
A `Countered` offer is inactive; it can't be acted upon. When you counter an offer, the original one is marked as `Countered` and a new offer is sent, complete with a new offer ID. You need to decline the new one.
