### ISSUE TITLE
Offer without trade id.

### ISSUE THREAD

**Issue by WeeSkilz** [DoctorMcKay/node-steam-tradeoffer-manager#14]
`[Error: Offer #721136877 is accepted, but does not have a trade ID]`

Error returned when calling `offer.getReceivedItems(function(err, items) { ... } `

Results in items being undefined.

**Comment by 2c2c** [comment]
is this a rare occurrence?

**Comment by WeeSkilz** [comment]
No, happens each time an offer is submitted.

**Comment by DoctorMcKay** [comment]
That's 100% a Steam issue.

**Comment by WeeSkilz** [comment]
Is there any way to retrieve the new asset id other than inventory searching?

**Comment by DoctorMcKay** [comment]
You could check inventory history. [`node-steamcommunity`](https://github.com/DoctorMcKay/node-steamcommunity) has this feature.

**Comment by GlebkaF** [comment]
So what are we to do?

if(!this.tradeID) {
		makeAnError(new Error("Offer #" + this.id + " is accepted, but does not have a trade ID"), callback);
		return;
}
How is this even possible? It got offer id after   checks for its existence.

**Comment by 2c2c** [comment]
there isn't really an answer if something on steam's end is broken for a period of time

this shouldn't be something persisting though. personally i've never seen it.

if you're asking for tips on how to handle a disaster situation like this in production, something you might want to try is monitoring the change in your own bot's inventory before and after the trade. keep in mind you need some kind of async series management or you have a potential race condition

**Comment by WeeSkilz** [comment]
`offer.accept(function(accept_err) {
                    offer.getReceivedItems(function(err, items) {
                        if(err) {
                            console.log(err);
                        }
                        console.log(items);
                    });
                });
`
Am I right in thinking this is the way I should be trying to get the items?

**Comment by 2c2c** [comment]
nope. accepting the offer will emit an event after which you can use
getReceivedItems

work with events and do not assume callback functions are synchronous

**Comment by DoctorMcKay** [comment]
@2c2c He is waiting until either the callback of `accept` or the event, as `getReceivedItems` would return a different error if the offer isn't in the `Accepted` state.

**Comment by DoctorMcKay** [comment]
If you check the [API](https://lab.xpaw.me/steam_api_documentation.html#IEconService_GetTradeOffers_v1) directly, does the offer have a `trade_id`?

**Comment by WeeSkilz** [comment]
Using the event allowed access to the trade id. Not sure why though given I was already attpting to access in the callback.

**Comment by DoctorMcKay** [comment]
I was too quick to blame Steam. Entirely my fault.
