### ISSUE TITLE
uncaughtException: Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by Foltos2016** [DoctorMcKay/node-steam-tradeoffer-manager#142]
Hey!
(my node version 4.4.0)

I use steam-tradeoffer-manager , steamcommunity, steam-user

but someties. (1-2 day) after

get error : uncaughtException: Error: read ETIMEDOUT\n    at exports._errnoException (util.js:870:11)\n    at TCP.onread (net.js:550:26)

and node js stop.

How to fix?

**Comment by DoctorMcKay** [comment]
I have this issue too from time to time. Unfortunately, node gives next to no information on how to debug it, not even which module it's originating in.

As far as I can tell, I'm listening for `error` in all of my modules that directly open TCP connections.

**Comment by DoctorMcKay** [comment]
Can you please run `npm update` to get an updated version of `steam-client`? I suspect that I may have fixed it, but I'm not certain.

**Comment by Foltos2016** [comment]
I use only steam-user, steamcommunity, steam-tradeoffer-manager

More info:

lekulo11: logged into Steam as 76561198______
lekulo11: got web session
lekulo11: trade offer cookies set. Got API Key: 520120043D77469B__________

uncaughtException: Error: read ETIMEDOUT\n    at exports._errnoException (util.js:870:11)\n    at TCP.onread (net.js:550:26)

**Comment by Foltos2016** [comment]
I get error if big steam down. (and then bot login)
