### ISSUE TITLE
No Event Call on receivedOfferChanged if the Trade were created by us

### ISSUE THREAD

**Issue by xRhizon** [DoctorMcKay/node-steam-tradeoffer-manager#144]
Im not realy sure if its acually a problem or not but if we use createOffer to send our users a trade link, we dont get the event receivedOfferChanged fired but on event sentOfferChanged we get a call with the informations.

Its not pretty clear in the wiki docs, but shouldnt be there a response to receiveOfferChanged also if the trade is send by us and it gets accpeted? If not, can i savely work with sentOfferChanged if ETradeOfferState.Accepted = true ?

**Comment by andrewda** [comment]
Why would an event for receivedOfferChanged be fired if you're sending an offer? Isn't the name pretty self explanatory?

**Comment by xRhizon** [comment]
Just want to make it sure.
