### ISSUE TITLE
getEscrowDuration returns error

### ISSUE THREAD

**Issue by centrual** [DoctorMcKay/node-steam-tradeoffer-manager#145]
Hey doctor,

I had trade url check in my system. But 

> manager.getEscrowDuration(steamId, token, function(err, their, yours) { });

 function returns 

> Error: This Trade URL is no longer valid for sending a trade offer to USER

everytime.

I checked the parameters. My parameters are:
steamId( I sending user's steam id, not partner id ): 76561198264704221
token: LYadzet-

i using this account in other sites and i created new link for test.
Currently my trade link is: https://steamcommunity.com/tradeoffer/new/?partner=337855998&token=LYadzet-

Can you help?

Thank you :)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

That SteamID does not correspond to that trade URL.
