### ISSUE TITLE
Malformed Response

### ISSUE THREAD

**Issue by OfficialWilson** [DoctorMcKay/node-steam-tradeoffer-manager#148]
Hi,

I got a bot today, and it errors saying Malformed response? Why.

```
function updateStock() {
  manager.loadInventory(730, 2, true, function(err, inv) {
    if (err) {
      debug("Error loading inventory! " + err.message);
      debug("(You can ignore this error, I will automatically try again in a few minutes.)");
    } else {
      var count = 0;
      for (var i = 0; i < inv.length; i++) {
        var item = inv[i];
        if (acceptedCSKeys.inArray(item.market_name)) {
          count++;
        }
      }
      stock = count;
    }
  });
}
```

**Comment by DoctorMcKay** [comment]
Are you logged in?

**Comment by OfficialWilson** [comment]
Yes





Will Wilson






On Sun, Jun 12, 2016 at 6:38 PM +0100, "Alexander Corn" <notifications@github.com> wrote:





Are you logged in?

---

**Comment by DoctorMcKay** [comment]
Are you sure?

What's the bot's SteamID?

**Comment by ylms** [comment]
Malformed Response is usually when your cookies expired.

**Comment by Ratuvog** [comment]
I have got this error when pass into loadInventory bad contextid parameter. Is there a way to get allowed contextid?

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/CSteamUser#getinventorycontextscallback

**Comment by woepertjes** [comment]
ive got the same problem right now, contextid is correct tho. Dunno what the problem is :/

**Comment by goodjonte** [comment]
**Note for people who get this error:** I got this error when trying to load an inventory turns out the appid i entered was invalid as i mis-typed it - So make sure appID is correct if u get this error
