### ISSUE TITLE
getEscrowDuration Method Missing

### ISSUE THREAD

**Issue by dwaltz** [DoctorMcKay/node-steam-tradeoffer-manager#153]
Great work on this library man. I truly can never say enough good things about your continued support!

Wondering what happened to the `getEscrowDuration` method? Was this intentionally omitted? Is this now a part of another lib and I am just missing it?

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v2.0.0
