### ISSUE TITLE
getEscrowDuration don't working in v2.

### ISSUE THREAD

**Issue by renesamaral** [DoctorMcKay/node-steam-tradeoffer-manager#156]
guys, after the update of my bots to v2 of the API the bots are crashing with the method getEscrowDuration. Anyone with the same problem ? I come back the version to 1.22 and works correct!

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v2.0.0
