### ISSUE TITLE
getReceivedItems

### ISSUE THREAD

**Issue by ClockRide** [DoctorMcKay/node-steam-tradeoffer-manager#157]
Hi guys i need help with this function sometimes this function return error, i try to read an error message, but get empty array. How can i read error?

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**
