### ISSUE TITLE
getEscrowDuration is still in the wiki

### ISSUE THREAD

**Issue by Maarethyu** [DoctorMcKay/node-steam-tradeoffer-manager#158]
So i updated the libs quite recently and my bot was crashing because getEscrowDuration was undefined, because the function got deleted in v2 i assume.

It took me a while to realise what happened because the function was still in the v2 wiki, without any warning that it only worked in v1.

Is it meant to ? else it should be showed that it doesn't work like this anymore, maybe with a link to getUserDetails.

Also i take this opportunity to ask, is there is any migration guide available ?

**Comment by scholtzm** [comment]
Basically just check your code for all the bullet points marked with **"BREAKING"**: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v2.0.0

**Comment by DoctorMcKay** [comment]
My apologies. I removed it from the TradeOffer page but I missed it in TradeOfferManager. I've updated the wiki now.

As @scholtzm said, just check your code for everything marked **BREAKING** in the release notes.
