### ISSUE TITLE
Function signature confirmation

### ISSUE THREAD

**Issue by Lagg** [DoctorMcKay/node-steam-tradeoffer-manager#159]
Hi, I'm going over some stuff making sure my migration to 2 went smooth. However I noticed that `getUserDetails` also swaps the order of the "me" and "them" args compared to `getEscrowDuration`. I looked at the code and it seems straightforward. But for posterity can I get a confirm that the following diff is functionally identical?

```
-        return manager.getEscrowDuration(partner, token, function(err, theirDays, myDays) {
+        tradeOffer.getUserDetails(function(err, me, them) {
+            var theirDays = them.escrowDays;
+            var myDays = my.escrowDays;
```

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

Besides the fact that you should be using `me.escrowDays` instead of `them.escrowDays`, yes.

**Comment by Lagg** [comment]
Alright. Thank you, and apologies for that. Even signed in to the forum and bookmarked it yet still forgot the rule :/
