### ISSUE TITLE
API Key is wrong

### ISSUE THREAD

**Issue by autaut03** [DoctorMcKay/node-steam-tradeoffer-manager#16]
Hello. I'm using node-steam-user and this libraries. After some period of the time developing my server I started to recieve such messages: 'Error: No API-Key set (yet)' on pollFailture. 

In your wiki there's an apiKey option for the constructor, but it's not used anywhere in the code. And I didnt found any code that sets apiKey, just and _checkApikey method, which isnt fired in the constructor. I dont know what I'm doing wrong. I've set sentry like this: 
```javascript
client.setSentry(new Buffer(fs.readFileSync(config.bot.ssfn), 'binary'));
```
and successfuly logged into the account. I've set up an api key for my IP, which works perfectly on other my servers/sites/raw queries from me. Just wtf.

**Comment by DoctorMcKay** [comment]
Can you post more of your code please?

**Comment by autaut03** [comment]
```javascript
var client = new SteamUser();
var offers = new SteamTradeOfferManager({
    steam: client,
    domain: config.common.domain,
    language: config.common.language,
	pollInterval: 3000,
	cancelTime: config.common.tradeCancelTime * 1000,
});
if(fs.existsSync(config.bot.ssfn)) {
	client.setSentry(new Buffer(fs.readFileSync(config.bot.ssfn), 'binary'));
} else {
	logger.error('SSFN file not found, exiting..');
	process.exit(1);
}
client.logOn({
	accountName: config.bot.login,
	password: config.bot.pass
});

client.on('loggedOn', function() {
	logger.info('Logged into Steam');
});

client.on('webSession', function(sessionID, cookies) {
	offers.setCookies(cookies, function(err) {
		if(err) {
			logger.error('Unable to set cookies for trades. Error: ' + err);
			process.exit(1);
		}
		logger.debug('Cookies have been set successfuly');
	});
});
if(fs.existsSync('polldata.json')) {
	offers.pollData = fs.readJsonSync('polldata.json');
	logger.debug('Trade offers poll data is found and loaded');
}

offers.on('newOffer', function(offer) {
	logger.info('called1');
	if(pause) return;
	logger.info('called2');
	var partnerID = offer.partner.getSteamID64();
	logger.info('New offer from ' + partnerID);
	if(offer.itemsToGive.length > 0 && !offer.isOurOffer) return;
	logger.warn('state: ' + offer.state + ' | itemsToRecieve: ' + offer.itemsToRecieve);
	
});

offers.on('pollFailure', function (err) {
    logger.error('Error polling data for trade offers. Error: ' + err);
	stopBot();
});

offers.on('pollSuccess', function () {
    startBot();
});

offers.on('pollData', function (pollData) {
    fs.writeJson('polldata.json', pollData);
	logger.debug('New trade offers poll data recieved and wrote');
});
```
here it is.
```

**Comment by autaut03** [comment]
works if I do such thing:
```javascript
offers.apiKey = config.common.apiKey;
```
I think u've forgotten about setting this variable in TradeOfferManager constructor.

**Comment by DoctorMcKay** [comment]
What I think is happening is that your bot is logging on, getting a notification of new items and/or trade offers from Steam, and that's triggering a poll before the manager is ready. You do not need to manually set an API key anywhere.

You should just ignore that problem for now. I'll put out a fix soon.

**Comment by autaut03** [comment]
But in documentaion there's an apiKey needed. But okay, I'll wait. Thank u.

**Comment by DoctorMcKay** [comment]
### [apiKey](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#apikey)
> A **read-only** property containing your account's API key once the callback of setCookies fires for the first time.

**Comment by autaut03** [comment]
whoops, I'm sorry. but anyway it's a bug)
