### ISSUE TITLE
how can i add items to send and to recieve ?

### ISSUE THREAD

**Issue by NadirRed** [DoctorMcKay/node-steam-tradeoffer-manager#160]
hello,
im trying to make a steam trade bot (and im not so good with coding).

i found this code to send trade offer but i don"t know how to add items

```
var offer = manager.createOffer("https://steamcommunity.com/tradeoffer/new/?partner=0000000&token=xxxxxxx");
        manager.loadInventory(730, 2, true, function(err, myItems) {
            if(err) {
                console.error(err);
                return;
            }

            offer.loadPartnerInventory(730, 2, function(err, theirItems) {
                if(err) {
                    console.error(err);
                    return;
                }

                offer.addMyItem(myItems[0]);
                offer.addTheirItem(theirItems[0]);
                offer.send("");
				
			
            });
        });
});
```

let's say i want to : 
send 2 items with id 6908727870 and id 6901768067
and
recieve 2 items with id 847548541 and id 325415748

please just help me filling these ids in the code above to serve like an example for me.

thank you so much

**Comment by andrewda** [comment]
You should ask this in the forum.

**Comment by NadirRed** [comment]
link please ?

**Comment by andrewda** [comment]
It's written in bold clearly in the README: https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/

**Comment by NadirRed** [comment]
thank you
