### ISSUE TITLE
Http error 429 even with a premium account.

### ISSUE THREAD

**Issue by Cyriaqu3** [DoctorMcKay/node-steam-tradeoffer-manager#163]
I recentry tried to use the [Backpack.tf trading bot](https://bitbucket.org/srabouin/backpack.tf-automatic) and got stuck with an http error :
`Cannot get API key: HTTP error 429` 

- My account is not limited
- I'm not trade restricted
- Steam Guard is enabled on my account
- I revoqued my old Api key and try with a new one but same result.

After some searchs, it seem that the problem came from this modules (used by the BP.tf bot).

Indeed, if i remove the error callback from the function line **110** **_(index.js)_** and specify my [key](https://steamcommunity.com/dev/apikey) manually, everything seem to work fine.

[Source code after the modification](https://gist.github.com/Cyriaqu3/a8c9694d17cb9339bdfdbf50c20dab41)

[My first issue on the Backpack.tf bot Bitbucket page](https://bitbucket.org/srabouin/backpack.tf-automatic/issues/156/cannot-get-api-key-http-error-429)

Any idea ?

**Comment by DoctorMcKay** [comment]
https://httperrors.com/429

You need to turn the bot off and wait. Your IP has made too many requests to Steam in a short time.

**Comment by Cyriaqu3** [comment]
I would not open an issueif it were that simple .

I never used the bot before and instantly got this error.
No VPN or thing like that.
Tried from 3 differents places, same error.

If I manually ask a new apikey i don't have any error from Steam, i mean he simply regenerate another (without telling me rate limit or anyting like that...).

Stop me if i'm wrong :
I got the error 429 when the module try to get a new API key ([like here](https://steamcommunity.com/dev/apikey))

So why can i ask for a new one manually (seem to be 1 per hour max) but not the bot ?

**Comment by DoctorMcKay** [comment]
I don't control Steam. All I can tell you is that 429 means that your IP has been rate limited.

**Comment by LikMigTel** [comment]
maybe this module try to communicate with steam incorrectly in large backpacks with alot of items?
i got same failure 429 and got 1700+ items on my BP

**Comment by LikMigTel** [comment]
Was the problem solved ?

**Comment by Cyriaqu3** [comment]
No, the problem is still here.

**Comment by LikMigTel** [comment]
i turned off my bot for ~5 days, after that delete all files and unpack new ones it from new downloaded zip with entering all info like pass and codes into the opened window and now it works

seems like temporary ban on steam servers for incorrect working of some bot modules
maybe it depends with huge amount of items on BP and opened backpack.tf classified trades

**Comment by scholtzm** [comment]
I'm pretty sure your issues are unrelated to this repo.

**Comment by Lagg** [comment]
It worked fine a year ago because valve has been increasing their throttling policies in consistent but small amounts. Likely because of the severity of abuse by such shit as SIH steadily increasing as well as its user count. Long story short, figure out how to make your connections non-concurrent and sleep between them. It's not a lib thing.

**Comment by Cyriaqu3** [comment]
I tried to login with another premium account ... and it worked fine.
I'm lost.

> maybe this module try to communicate with steam incorrectly in large backpacks with alot of items?
i got same failure 429 and got 1700+ items on my BP

I will check that...

**Comment by ylms** [comment]
Oh, are you sure your account not limited? Some paid accounts was randomly limited by Steam for no reason back in time, then one of my account stopped working.

https://steamcommunity.com/discussions/forum/1/392184522702183205/

**Comment by Cyriaqu3** [comment]
Mmmh, not sure, I encounter this problem only when i ask an api key **with this lib**, never got any problem elsewhere.
Also, it seem [i'm not alone](https://bitbucket.org/srabouin/backpack.tf-automatic/issues/156/cannot-get-api-key-http-error-429#comment-30427933)

I will open a thread on the Steam forum to be sure.

**Comment by Lagg** [comment]
This occurs because before a month or so ago there wasn't any throttling done  on `/dev/apikey`. Now there is. A request to it occurs when you set your offer cookies. If you have a login system where you try to do something like connect all your accounts without doing proper synchronous-asynchronous practices so that they don't all try to connect at once.

**Comment by Lagg** [comment]
Now Valve is sending back 429s for confirmations. That's not good.

**Comment by DoctorMcKay** [comment]
I don't think there are any pages that are immune from 429.

**Comment by Dakshster** [comment]
[2017-02-24 18:24:36.885] [TRACE] [default] - Sucesfully auth
[2017-02-24 18:24:37.287] [ERROR] [default] - Cant make apikey
[2017-02-24 18:24:37.287] [DEBUG] [default] - [Error: Access Denied]
Error: Access Denied
