### ISSUE TITLE
newOffer after Error dont comes again

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#168]
When an newOffer was sendet and gets an error for steam or anything, it dont comes again after interval...

What i must do for it?

**Comment by ylms** [comment]
Do you have callbacks for it? This is -most likely- not related to module issue. You'll need to explain your problem more.

**Comment by andrewda** [comment]
As @ylms you'll need to explain more. From what you've said, I think your issue is that you're attempting to accept/decline an incoming offer, but when an error occurs accepting/declining it, you're expecting to have the `newOffer` event fire again. That won't happen. Instead, you'll need to check for the error in the callback of `offer.accept()` or `offer.decline()` and re-accept/decline if the error is present.

**Comment by Marow** [comment]
@ylms @andrewda I have
 `manager.on('newOffer', function(offer) {`
there comes the offer. But much times it gets an Error from Steam, cause he cannot read the Offer. Like Error 28. 

Thats here than
`offer.accept(function(err) {
	if (err) {
		console.log("Unable to accept offer: " + err.message);
		return;
	} else {
		community.checkConfirmations(); // Check for confirmations right after accepting the offer
		console.log("Offer accepted");
	}
});`
All Times than he Says "Unable to accept offer: Error 28" or like that.

But when i make new offer (2nd) he see the 2nd offer, but dont see the first anymore.
And here he checks and accepts every 30 secs
`community.startConfirmationChecker(30000, "SECRET");`

**Comment by DoctorMcKay** [comment]
As others have said, newOffer is only emitted when an offer is received. If there's an error acting on it, you'll need to re-act on your own. Errors are Steam's fault, and you best get used to them.

**Comment by MikeLund** [comment]
Can you please elaborate a bit on the suggested way to re-act on the accept failing? I really liked how it was handled internally before.

I might be missing something big, but I keep ending up getting IP blocked by Steam when I am trying to work around it myself. (I have a couple hundred trade-offers pending, so it's probably sending too many requests, BUT it worked fine before with poll+autoretry method..) Thanks!

**Comment by DoctorMcKay** [comment]
It's really up to you. Make a list of offers in a database. Call `getOffers` periodically and act on any that are outstanding which should have been handled already. Set a timer when accept fails in `newOffer`. There are many options.
