### ISSUE TITLE
newOffer return; will stop from firing it again

### ISSUE THREAD

**Issue by autaut03** [DoctorMcKay/node-steam-tradeoffer-manager#17]
Hello. One more issue:
When newOffer is fired and I do
```javascript
return;
```
this trade offer will never be fired again. And this is very bad. For example this code:
```javascript
offers.on('newOffer', function(offer) {
	logger.info('called1');
	if(pause) return;
	logger.info('called2');
});
```
If my server was on the pause (for example when steam is down etc) then this trade will never be fired again. What can I do then?

**Comment by andrewda** [comment]
Well, logically `newOffer` would not fire again as you aren't receiving a new offer. You have to call the `getOffers()` method to receive a list of tradeoffers.

**Comment by DoctorMcKay** [comment]
Agreed with @andrewda. If you ignore a `newOffer` event, it's your responsibility to come back and pick it up again.

**Comment by autaut03** [comment]
But how can I do this better? It would be very stupid solution just to call getOffers. U should add some way to just skip the offer on 'newTrade' OR add the method, that will re-call 'newTrade' for all unaccepted trades.. I dont know. How can I just pause getting this trades? Dont decline them, dont accept, dont do anything, just stop getting them?

**Comment by autaut03** [comment]
And same with other events... how can I pause them all? How can I just skip them all and call when I stop pause? For example steam is down and everything works incorrect. Then I manually or when 'pollFailture' starting the pause and... and after the pause nothing works too =_=

**Comment by autaut03** [comment]
Works now:
```javascript
function stopBot() {
	if(pause) return;
	pause = true;
	logger.warn('Bot has been stopped for a while.');
}

function startBot() {
	if(!pause) return;
	pause = false;
	logger.info('Bot has been resumed.');
	offers.pollData = {};
	offers.doPoll();
}
``` 
So I'm manually clearing the pollData and doing the poll. But this is wrong way of doing this.

**Comment by autaut03** [comment]
UPD2:
everything works fine If I remove pollData loading and saving + using the code upper.

**Comment by DoctorMcKay** [comment]
Set [`pollInterval`](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#pollinterval) to `-1` to pause polling, then reset it and call `doPoll()` to resume?

**Comment by autaut03** [comment]
It doesnt work. Even if I set -1 at the constructor it's being called. After for example 10 seconds bot starts (setting interval to normal and setting the pause to false) and it's not being called again.
For now I'll still use my way, but it seems to me that it should work another way. I mean something like when function returned false then dont put it in pollData array.

**Comment by DoctorMcKay** [comment]
I could add something to entirely pause polling if you want, but I don't see it being hugely useful.

**Comment by autaut03** [comment]
It would be better to add a way to cancel and continue the event. Or if it seems hard or bad way to do it then u can fix stop/start of the polling. cuz now even with -1 events are being called.
and sry for my English ;)

**Comment by DoctorMcKay** [comment]
Deferring the event is just a bad way to do it.
