### ISSUE TITLE
glitched offer

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steam-tradeoffer-manager#171]
what is a glitched offer ? (because i cant understand)

**Comment by andrewda** [comment]
You can see what criteria define a glitched offer [here](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/4a5a5488b5fbc66386c9e67b33dafb7755d62a5f/lib/classes/TradeOffer.js#L240-L256).

A glitched offer is an offer that Steam sends to us without an id, without any items, or without some items' names.
