### ISSUE TITLE
callback not a function when sending offer

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#172]
I get this error, when i will make an offer.
`callback is not a function`

I get this error here
`offer.send('Your win Round #' + round + ' from ' + sitename + ' with Hash #' + hash + '', function (err, status){
		            if (err) {
		                console.log(err);
		                return;
		            } else {
		                console.log('Trade offer sent successfully');
		            }
		        });`

and my code looks like
`var offer = manager.createOffer(tradelink);
manager.loadInventory(730, 2, true, function(err, myItems) {
offer.loadPartnerInventory(730, 2, function(err, theirItems) {
itemx = {
		            appid: 730,
		            contextid: 2,
		            amount: 1,
		            assetid: 7294441328
		        }
		        offer.addMyItem(itemx);`
and than this from the top

the error is in 
`/node_modules/steam-tradeoffer-manager/lib/helpers.js:29`

**Comment by andrewda** [comment]
Please provide more the entire stack trace.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v2.0.0

**Comment by Marow** [comment]
Oh thanks Doctor.

Can you help me with another Problem?
How i can send "much" items in one Trade? I find AddMyItems() but idk how it works and how i use...
One item send with AddMyItem it works

Do you have an Example for sending many items?

**Comment by DoctorMcKay** [comment]
Either call `addMyItems` with an array of item objects, or call `addMyItem` multiple times.
