### ISSUE TITLE
Error: There was an error sending your trade offer. Please try again later. (15)

### ISSUE THREAD

**Issue by xJustx** [DoctorMcKay/node-steam-tradeoffer-manager#173]
Hey..

If I try to send a offer to someone (with his steamid + token) I'm getting the error: `Error: There was an error sending your trade offer. Please try again later. (15)`.
If I add him as friend, all is working fine. Trade with the browser or the steam client is working fine without having him as friend.
The token is correct:
example from the wiki: `var offer = manager.createOffer("https://steamcommunity.com/tradeoffer/new/?partner=46143802&token=KYworVTM"); // SteamID and trade token both provided`
Error if I using this: `throw new Error("Unknown SteamID input format \"" + input + "\"");`
If I use this: `var offer = manager.createOffer(new TradeOfferManager.SteamID("76561198006409530"), "KYworVTM"); // trade token provided` I get the problem with sending the trade offer. I tryed this with different tradeoffer-links and it's not working. Token is 100% correct.

**Comment by andrewda** [comment]
"**Have a question about the module or coding in general? *Do not create a GitHub issue.* GitHub issues are for feature
requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).
Such issues may be ignored!**"
