### ISSUE TITLE
newOffer not firing on module startup

### ISSUE THREAD

**Issue by StevePavlin** [DoctorMcKay/node-steam-tradeoffer-manager#174]
I send an offer to my bot listening using the newOffer event. The event is fired okay if the manager is already polling, but when the application starts, it will not recognize an offer that was sent while the manager was not polling.

I am saving the polldata.json and reloading it each time the bot starts. Am I doing something wrong?

**Comment by DoctorMcKay** [comment]
I can't seem to reproduce this. Are you restoring your poll data before you begin polling?

**Comment by StevePavlin** [comment]
Fixed. I was doing this only after logging in:

```
  require('./components/offer-send/offer-send')(this);
```

That file had the listeners in it, so they were firing but not being listened upon. By the way, do you write tests for this library? Just curious.

**Comment by DoctorMcKay** [comment]
No, I don't really write tests.
