### ISSUE TITLE
Load inventory limit

### ISSUE THREAD

**Issue by Infrox** [DoctorMcKay/node-steam-tradeoffer-manager#179]
Hey there,
I have a question that has been bothering me for a very long time.
As you might know, steam web API has a limit on requests per IP address.
Do these limits apply to functions like manager.loadInventory or manager.loadUserInventory?
Thanks.

**Comment by trzyrazyzero** [comment]
Yes

**Comment by Aareksio** [comment]
**Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

All non-api calls are rate limited. both `loadInventory` and `loadUserInventory` uses one of them (https://steamcommunity.com/profiles/`steamid`/inventory/json/`appid`/`contextid`).
