### ISSUE TITLE
Items, returned by getRecivedItems are undefined

### ISSUE THREAD

**Issue by GlebkaF** [DoctorMcKay/node-steam-tradeoffer-manager#18]
Hello, im using this code : 
```javascript
offer.accept(function (err) {
                        if (err) {
                            debug("Unable to accept offer: ", err.message);
                        }
                        else {
                            offer.getReceivedItems(function(err, items) {
                                items.forEach(function(item){
                                 // Handle recived items
                                })
                     
                            })
//and so on...
```
but I got error  "Cannot read property 'forEach' of undefined" while offer was accepted and contains receiving items.
It work's fine before and after this error.
If it's important, item to recive was m4a1-s | Cyrex (Minmal wear) and there are no items to give.

**Comment by DoctorMcKay** [comment]
You're not checking the `err` in the callback of `getReceivedItems`. You likely have an error there.

**Comment by GlebkaF** [comment]
Yeah, thank you, i added this check, awaiting for similar errors. I got it first time over 1k accepted trades.
