### ISSUE TITLE
Malformed response why?

### ISSUE THREAD

**Issue by esvills** [DoctorMcKay/node-steam-tradeoffer-manager#181]
console.log("New offer #" + offer.id + " from " + offer.partner.getSteamID64());
    offer.getUserDetails(function(err,me,them){
  
  })
 Error: **Malformed response**, next 10 seconds trade offer change state 2 -> 7. 

Thanks

Previously, it was all good

**Comment by ylms** [comment]
That happens mostly because your cookies expires.
