### ISSUE TITLE
Most time Error: Unable to get offer: Data temporarily unavailable

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#183]
Hi,

i get this error so much...
`Unable to get offer: Data temporarily unavailable`

But why? How can i fix this....? I dont find anything for that.
In Tradeoffers its look like there are no items... but there are.

And when he tried much times, one time gets error 28...

It looks like that
`data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable

data:    bot.js:11149 - Retrying to get.

data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable

data:    bot.js:11149 - Retrying to get.

data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable

data:    bot.js:11149 - Retrying to get.

data:    bot.js:11149 - Unable to accept offer: There was an error accepting this trade offer.  Please try again later. (28)

data:    bot.js:11149 - Retrying to accept.

data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable

data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
data:    bot.js:11149 - Unable to get offer: Data temporarily unavailable
data:    bot.js:11149 - Retrying to get.
`

Here you see my retryOffer...
`function retryOffer(id) {

    manager.getOffer(id, function (err,offer) {
        if (err) {
            console.log("Unable to get offer: " + err.message);
                console.log("Retrying to get.");
                setTimeout(function(){ 
                	retryOffer(id);
                }, 5000);
        }
        else {
            offer.accept(function (err) {
                if (err) {
                    console.log("Unable to accept offer: " + err.message);
                    if (err.eresult == 28) {
                        console.log("Retrying to accept.");
                        retryOffer(offer.id);
                    }
					tradelock = false;
                }
                else {
                    console.log("Offer accepted");
                    community.checkConfirmations();
                }
            });
        }
    });
} 
`

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**
