### ISSUE TITLE
getReceivedItems return no items in receivedOfferChanged

### ISSUE THREAD

**Issue by Marow** [DoctorMcKay/node-steam-tradeoffer-manager#184]
The Bot accepted the Trade. Gets receivedOfferChanged to accepted but in items is nothing. But he dont crash with an error!

```
offer.getReceivedItems(function(err, items) {
			if (err) {
				console.log("Couldn't get received items: " + err);
				offer.decline();
				tradelock = false;
			} else {
                                console.log(items);
```

In console log looks like 
`[]`

**Comment by Marow** [comment]
i tried now one more time. Same again... it gets accepted, and getReceivedItems gets items with empty array

**Comment by scholtzm** [comment]
Are you completely oblivious to what is being said to you? This is an issue tracker, not your personal help desk.

Stop spamming everyone's mailbox with your questions.

*1 https://github.com/DoctorMcKay/node-steam-user/issues/83
*2 https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/issues/183

**Comment by DoctorMcKay** [comment]
Due to repeated and gross ignorance of instructions, this user has been blocked from opening new issues.
