### ISSUE TITLE
Creating a trade offer returns Error 400.

### ISSUE THREAD

**Issue by unr** [DoctorMcKay/node-steam-tradeoffer-manager#19]
I've created a functioning trade bot using `node-steam-tradeoffers`, and afterwards have switched over to using `node-steam-tradeoffer-manager`.

**I've already been using my account, and sentry file, successfully sending trades for days.**

The structure of my bot [matches how ParentBot](https://github.com/dragonbanshee/node-steam-parentbot) is set up, switching out `node-steam-tradeoffers` however.

When I make the trade request using `node-steam-tradeoffers`, returns tradeid fine.

When I make the trade request using `node-steam-tradeoffer-manager`, I receive a 400 error.

---

Any guidance on how I can try to debug this? Been trying to log the request headers to compare between the two - to see what the difference is. 

Kind of stuck, thought I'd make a post~

**Comment by unr** [comment]
Investigating further... I think this has to do with Steam IDs, vs PartnerID/Access Token.

I'm trying to make a trade, via a 3rd party trade url. I have access to SteamPartnerId, and SteamAccessToken. 

I will not know the original Steam ID, nor will we be friends. I need to use the PartnerID...

---

When using `steam-tradeoffers` my request adds `partner: '76561198003688743'` this is a SteamPartnerID.

When using `steam-tradeoffer-manager` my request adds `partner: '4980378'` This is a SteamID

Pretty sure this has something to do with my issue.

**Comment by unr** [comment]
When creating a request, `steam-tradeoffers` goes:

1. Is there a SteamID? If so, use it.
2. Is there a SteamPartnerID? Convert it to a SteamID, then use it.
3. Missing both? Fail, return error.

It seems like `steam-tradeoffer-manager` is missing this step.

---

in `steam-tradeoffers`:

```js
var Long = require('long');

// Utility function, stolen from `steam-tradeoffers/index.js`
function toSteamId(accountId) {
  return new Long(parseInt(accountId, 10), 0x1100001).toString();
}

var partnerID = '76561198003688743';
var steamID = toSteamId(partnerID); // '4980378'
```

**Comment by DoctorMcKay** [comment]
Please show the code where you're creating the offer.

**Comment by unr** [comment]
@DoctorMcKay I've uploaded my current bot file - the `ryanPartnerId` mentioned is legit, as are his items.

I'm logging in with my personal sentry/steam account, which sends trades.

Gist here: https://gist.github.com/unr/c34257cbd187669f00c0

---

Inside of `steam-tradeoffer-manager/lib/classes/TradeOffer.js`, I made the `send()` function use the PartnerID I set in my bot file above.

```js
"partner": this.partnerAccountId || this.partner.toString(),
```

**Comment by DoctorMcKay** [comment]
var newOffer = this.offers.createOffer(ryanPartnerSteamId);

This is what you're doing wrong. From the [documentation](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#createofferpartner), `partner` should be "either a SteamID object or something which can parse into one". So you have three options:

1. Use `offers.createOffer(ryanSteamId)`
2. Use `offers.createOffer("[U:1:" + ryanPartnerSteamId + "]")`
3. Create a SteamID object as follows:

    var sid = new TradeOfferManager.SteamID();
    sid.universe = TradeOfferManager.SteamID.Universe.PUBLIC;
    sid.type = TradeOfferManager.SteamID.Type.INDIVIDUAL;
    sid.instance = TradeOfferManager.SteamID.Instance.DESKTOP;
    sid.accountid = ryanPartnerSteamId;
    var newOffer = offers.createOffer(sid);

**Comment by unr** [comment]
Oh my god @DoctorMcKay Thank you! 

The infamous `[U:1:"PartnerID":]` Has been driving me insane. Didn't realize it was PartnerID.
