### ISSUE TITLE
tradeoffer.send strips out classid and instance id from items

### ISSUE THREAD

**Issue by daywiss** [DoctorMcKay/node-steam-tradeoffer-manager#191]
this may not be important data for steam to receive, but it is somewhat important to be able to get that classid/instanceid back as data in the created trade offer. can make a PR if helpful.  

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L427

just need to update the function here to include classid and instanceid

**Comment by DoctorMcKay** [comment]
Why do you need the classid and instanceid to be available there? If you know them why can't you just use your already-known data? 

It is not feasible to provide that data via the library as it's not data that Steam wants when you send an offer.

**Comment by daywiss** [comment]
My work around is just to replace the stripped trade offer items with my original items after the trade succeeds. Its surprising behavior to have properties silently stripped off the items, and in my case caused confusion until I realized what was happening.  Obviously easy to work around if you know the internals of the trade offer class, but not easy to identify in the first place if you don't.

I think rather than remapping the items as they are set with addItem, just map them right before they are sent to steam, leaving the original items the user attached intact.  It actually looks like you are doing this already in the send function, so mapping them in addItem is probably redundant.

**Comment by DoctorMcKay** [comment]
I could add some documentation to the wiki regarding this behavior. I'm currently out of country right now so I can't look at the code but I can probably look it over and decide the best course of action for this next week.

**Comment by daywiss** [comment]
yea sounds good. you can close this issue at your discretion. thank you
