### ISSUE TITLE
DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by ylms** [DoctorMcKay/node-steam-tradeoffer-manager#192]
Hello,

I have recently updated my nodejs to v7.2.x

Then this error started to appear
(node:8902) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

It has no affection on bot's working but I was curious about that might be the issue why there is delay between events.

**Comment by DoctorMcKay** [comment]
Run `npm update` and the warning should go away.
