### ISSUE TITLE
When changed IP, i got after while error 401

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steam-tradeoffer-manager#193]
Hi,
after i changed ip for all my bots using:
```
	self.CMClient = new CMClient();
	self.CMClient.bind('212.83.131.158');
	self.steamClient = new SteamUser(self.CMClient);
	self.steamCommunity = new SteamCommunity({localAddress: '212.83.131.158'});
```
i got after 5-10 minutes error 401, but when i change back to my normal ip (commenting cmclient, localadress etc), its good.
Its bug on my side or module site?

**Comment by DoctorMcKay** [comment]
Congratulations, you managed to follow instructions and then disregard them afterward. 

https://dev.doctormckay.com/topic/693-error-http-error-401/#entry2218
