### ISSUE TITLE
steam update inventory problems

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steam-tradeoffer-manager#194]
Steam new update

Error while getting users inventory: null, status: 429

**Comment by DoctorMcKay** [comment]
https://httpstatuses.com/429

**Comment by scholtzm** [comment]
https://github.com/Jessecar96/SteamBot/issues/1060

> Valve has added a new endpoint for inventory requests and has rate-limited the old one further to 5 requests/min.
> Old: http://steamcommunity.com/profiles/76561198045552709/inventory/json/730/2
> New: http://steamcommunity.com/inventory/76561198045552709/570/2?l=english&count=5000
> New with pagination: http://steamcommunity.com/inventory/76561198045552709/570/2?l=english&count=250&start_assetid=8244114748
> count, used for pagination, can be a max of 5000.

**Comment by Vankxr** [comment]
I started to get 429's too.
Given that I didn't use to get that before this update, and I didn't change my code, maybe we should implement this new endpoint.

I noticed that if an item isn't tradeable, it's `instanceid` is 0, is that right?

**Comment by andrewda** [comment]
@Vankxr nope – CS:GO cases and Graffitis all have an `instanceid` of `0`. Why can't you just use the `tradable` property?

**Comment by Vankxr** [comment]
I tried the new endpoint with tradeable flag like the old one and it didnt seem to work hmm

**Comment by andrewda** [comment]
There's no `tradable` property in the URL, but there is a `tradable` property inside of each item object.

**Comment by Vankxr** [comment]
Didnt notice. I'll try later at home
