### ISSUE TITLE
Multi-bot

### ISSUE THREAD

**Issue by mworkg** [DoctorMcKay/node-steam-tradeoffer-manager#196]
I use multi bot , and have a question , how to use proxy for each of them?

**Comment by Aareksio** [comment]
> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

**Comment by DoctorMcKay** [comment]
Please give more detail at the above-linked forum.
