### ISSUE TITLE
getInventoryContents don't russian language

### ISSUE THREAD

**Issue by esvills** [DoctorMcKay/node-steam-tradeoffer-manager#197]
New method "getInventoryContents" don't load ru languange, loadInventory - load russian

**Comment by ylms** [comment]
Change your steam language.

**Comment by rover5056** [comment]
getInventoryContents don't chinese language,too.
I can't set descriptions with chinese

**Comment by DoctorMcKay** [comment]
This is fixed in v2.7.5.
