### ISSUE TITLE
Version of this lib published to NPM is different to the GitHub version

### ISSUE THREAD

**Issue by Rob--** [DoctorMcKay/node-steam-tradeoffer-manager#199]
Try doing a fresh install of this library in an empty directory, open up `lib/classes/TradeOffer.js` and scroll to the bottom of the file. Compare it to the end of this file `https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js`.

The `setMessage` and `setToken` methods are missing. Not just that, the file has 783 lines compared to the GitHub version of 920 lines.

NPM says the latest version if 2.6.0 and was last updated the same time as the last commit on this repo so I'm not sure what's happened or if any other files are not up to date either.

**Comment by DoctorMcKay** [comment]
![](https://mckay.media/jMl5l)

**Comment by Rob--** [comment]
Oops, 2.5.0 not 2.6.0, but the issue still remains. Did you make a new dir and install from NPM and check the file?

**Comment by DoctorMcKay** [comment]
Yes, I did. It has 920 lines (plus one blank) as expected.
