### ISSUE TITLE
Cant send offer

### ISSUE THREAD

**Issue by trzyrazyzero** [DoctorMcKay/node-steam-tradeoffer-manager#2]
Hello.
I cant send trade offer.

```javascript
							create = manager.createOffer('steam64');
							itemx = {
								appid: 730,
								contextid: 2,
								amount: 1,
								assetid: '2550388675'
							}
							create.addMyItem(itemx);
							
							create.send('test', 'token', function(err, status) {
								if(err)
									console.log(err);
								else
								{	
									console.log('Success');
								}
							});
```
When i try this: 
[Error: There was an error sending your trade offer.  Please try again later. (25)]

I dont know why.

**Comment by DoctorMcKay** [comment]
25 = LimitExceeded. You've sent too many trade offers either globally or to that person.

You can only send up to 30 trade offers total, or up to 5 to one person.

In the future, please direct Steam-related questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).
