### ISSUE TITLE
createOffer without cancelTime

### ISSUE THREAD

**Issue by kenzik** [DoctorMcKay/node-steam-tradeoffer-manager#20]
Hello, is it possible to send some trade offers without cancelTime?

**Comment by DoctorMcKay** [comment]
No, but I can add that soon.

**Comment by kenzik** [comment]
That would be awesome, thanks!

**Comment by kinsi55** [comment]
While at it, making it flexible by passing either false/0, or a different value shouldnt be too hard either right? Just thinking into the future ^^

**Comment by Netifriik** [comment]
@kinsi55 Then it could also be false by default and make it optional?

**Comment by kinsi55** [comment]
Yes thats what i meant. If you dont pass a value it will use whatever you passed upon initialisation  of the manager, else if you pass 0/false to thr tradeoffer it will override with "disabled", or any other time independent of the initialisation value

**Comment by DoctorMcKay** [comment]
I believe that I'm going to add an `offer.setCancelTime` method. If not called, it will use the default in the constructor. It could also be overridden per-offer.

**Comment by DoctorMcKay** [comment]
See this (especially the section labeled cancelTime underneath it): https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#datakey-value

**Comment by kinsi55** [comment]
I was just now working on it and pretty much done ¯\_(ツ)_/¯

Well i didnt implement the data stuff though in mine.

**Comment by DoctorMcKay** [comment]
Sorry!

To be fair though, you did give me until the end of today...

**Comment by kinsi55** [comment]
Yeah no problem, my solution was implemented within minutes anways :) Thank you!
