### ISSUE TITLE
getInventoryContent returns "Malformed response" when inventory is empty

### ISSUE THREAD

**Issue by Maarethyu** [DoctorMcKay/node-steam-tradeoffer-manager#201]
If i use manager.getInventoryContent() and the inventory Im trying to get is empty, the callback returns "Error: Malformed response".

Ii've not tested if it's in node-steam-tradeoffer-manager or it's coming from the original function in node-steamcommunity but this is a easy fix as far as i know.

You could check if json.total_inventory_count equal 0 and if yes you return an empty array.

If this error is by design you should return "Error: Empty inventory" instead of malformed response so it would be clearer for future users.

**Comment by Vankxr** [comment]
Its from the response parser, node-steamcommunity
I am getting it aswell.

**Comment by DoctorMcKay** [comment]
This has been fixed in node-steamcommunity v3.30.4. Just run `npm update` to get it.
