### ISSUE TITLE
Resuming old session

### ISSUE THREAD

**Issue by feedarz** [DoctorMcKay/node-steam-tradeoffer-manager#203]
In node-steamcommunity module, which included by default in node-steam-tradeoffer-manager, it says that you can resume previously opened session if you have saved cookies from it, but when i pass them in manager.setCookies it returns me "Not Logged In". 

Do i have to log my bot in every time at the start or am i doing something wrong here?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You can't resume a session if your cookies have expired, which seems to be the case here. So yes, you need to log in fresh every time.

**Comment by feedarz** [comment]
I am sorry, but i the case is i am saving in minutes before starting the bot, which is not the case in terms of expiring.

**Comment by DoctorMcKay** [comment]
Please post a thread at the forum and provide your code.

**Comment by feedarz** [comment]
Posted, please approve.
