### ISSUE TITLE
Old assetid of a received item [Improvement]

### ISSUE THREAD

**Issue by feedarz** [DoctorMcKay/node-steam-tradeoffer-manager#204]
Prologue
I don't want to spend time on understand the whole structure of the module, so I will just contribute some of my ideas to make it work.

So, as you can read from the title, It can be useful to add old assetid for a received item (those you acquire from `TradeOffer.getReceivedItems` method).

As I came across this problem, I needed to find old assetids for items to update them in DB. 

My first approach to it's solution was to just go through `receivedItems` and `offer.itemsToReceive` at the same time basically mapping old assetid from `offer.itemsToReceive` to a new one from `receivedItems`. It was not successful, because steam assigns new steamids in random order, so for each key from `offer.itemsToReceive` you might not get same item as from `receivedItems`.

So now we move to next and current working solution that i am using. When I was looking at my bot's inventory I noticed that items are in the same order in the inventory as they are in the tradeoffer they transfered through. So the very basic thing you can do is you can take the position of an item in the inventory (which you can get from `receivedItems[key].pos`) and `receivedItems` array by position parameter and than you are good to use the first method I described.

As simple as it sounds some of the people might not notice it, so that`s why I think it should be added.

**Comment by feedarz** [comment]
Here is a piece of a code i am using:

```javascript
var itemsReceived = [];
for(var key in items){
  itemsReceived.push({ 
    old_assetid : 0, 
    assetid : items[key].id, 
    name : items[key].market_hash_name, 
    img : items[key].icon_url, 
    val : items[key].pos 
  });
}

itemsReceived = insertionSort(itemsReceived); // sorts items by val

var old_assetids = offer.itemsToReceive.reverse();

//mapping old assetids
for(var i = 0; i < old_assetids.length; i++){
  itemsReceived[i].old_assetid = old_assetids[i].id;
}
```

**Comment by DoctorMcKay** [comment]
The order of items in the offer or in the receipt is not guaranteed, and indeed I've seen instances where the order varies. Unfortunately, this isn't possible.

**Comment by feedarz** [comment]
I tested over 100 offers and every time order in the offer matches order in inventory. So i am sorting `receivedItems` by `pos` (position in inventory) and then them mapping to `offer.itemsToReceive`. 

I hope you are talking about random order of `receivedItems`, not about random order of items in offer and in inventory.

**Comment by feedarz** [comment]
Can you, please, reopen issue, maybe someone have better solution to a problem.

**Comment by scholtzm** [comment]
Which game does this apply to?

**Comment by feedarz** [comment]
I think it applies to any game, but I use it on csgo-related service.

**Comment by DoctorMcKay** [comment]
```json
			{
				"tradeofferid": "1801736833",
				"accountid_other": 46143802,
				"message": "",
				"expiration_time": 1486318813,
				"trade_offer_state": 2,
				"items_to_receive": [
					{
						"appid": "730",
						"contextid": "2",
						"assetid": "8465500021",
						"classid": "926978479",
						"instanceid": "0",
						"amount": "1",
						"missing": false
					},
					{
						"appid": "730",
						"contextid": "2",
						"assetid": "8715853261",
						"classid": "991959905",
						"instanceid": "0",
						"amount": "1",
						"missing": false
					}
				]
				,
				"is_our_offer": false,
				"time_created": 1485109213,
				"time_updated": 1485109217,
				"from_real_time_trade": false,
				"escrow_end_date": 0,
				"confirmation_method": 0
			},
			{
				"tradeofferid": "1801736504",
				"accountid_other": 46143802,
				"message": "",
				"expiration_time": 1486318805,
				"trade_offer_state": 2,
				"items_to_receive": [
					{
						"appid": "730",
						"contextid": "2",
						"assetid": "8715853261",
						"classid": "991959905",
						"instanceid": "0",
						"amount": "1",
						"missing": false
					},
					{
						"appid": "730",
						"contextid": "2",
						"assetid": "8465500021",
						"classid": "926978479",
						"instanceid": "0",
						"amount": "1",
						"missing": false
					}
				]
				,
				"is_our_offer": false,
				"time_created": 1485109205,
				"time_updated": 1485109218,
				"from_real_time_trade": false,
				"escrow_end_date": 0,
				"confirmation_method": 0
			}
```

The order in the data is the order in which the items were added to the offer.
