### ISSUE TITLE
The launch of two bots on the same server

### ISSUE THREAD

**Issue by OLDIN** [DoctorMcKay/node-steam-tradeoffer-manager#205]
Greetings, tell me, please, how do I authorize 2 accounts on a single server with a single IP? 
It works if the variant with domain purchase and screwing them to the same IP, the distribution between the bots using Nginx? 
Or is there any other solutions? 
Thank you in advance )

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

Also, I have no idea what you asked.
