### ISSUE TITLE
Getting old assetid is now possible [Improvement]

### ISSUE THREAD

**Issue by feed4rz** [DoctorMcKay/node-steam-tradeoffer-manager#206]
Dear @DoctorMcKay , although we closed issue #204 , its now possible to get old assetids. 

Check this out https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#CEcon_GetTradeHistory_Response_Trade_TradedAsset

**Comment by DoctorMcKay** [comment]
I'm aware of this, I just haven't had time to add something for it it yet.

**Comment by feedarz** [comment]
The most annoying thing is, it came out right after i finished project without this feature. 

Anyway, if you are aware of this, you can close the issue. Sorry for not posting it on forum.

**Comment by DoctorMcKay** [comment]
No, this is the right place to post feature/enhancement requests. I'll keep this open until I'm able to get something together.

**Comment by feedarz** [comment]
I would like if you include this feature into getReceivedItems method.

**Comment by feedarz** [comment]
Not really cool to add changes before they are test :/

Error: Error: Call failed for service method request 'Econ.GetInventoryItemsWithDescriptions#1'.

**Comment by DoctorMcKay** [comment]
What are you talking about?

**Comment by feed4rz** [comment]
Sorry, misunderstood the error description.

**Comment by DevDuckEl** [comment]
@DoctorMcKay @feed4rz In this API you cannot obtain a specific trade offer. If a bot sent 2 or more of the trade offers and the user has accepted them. How can we know the new assetid of the penultimate trade offer?

**Comment by DoctorMcKay** [comment]
You can match the trade ID.

**Comment by DevDuckEl** [comment]
@DoctorMcKay Can we translate from tradeofferid in the tradeid? These values differ.

**Comment by DoctorMcKay** [comment]
The trade ID is present in the GetTradeOffer[s] output.

**Comment by DevDuckEl** [comment]
@DoctorMcKay Sorry, my mistake.

**Comment by DoctorMcKay** [comment]
Added in [v2.6.0](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v2.6.0).
