### ISSUE TITLE
User is in Escrow for [object Object] days

### ISSUE THREAD

**Issue by Yumba** [DoctorMcKay/node-steam-tradeoffer-manager#207]
I updated the node version and I made the change from offer.getEscrowDetails to offer.getUserDetails, but I still get the error: User is in Escrow for [object Object] days. 

What should I change?

**Comment by scholtzm** [comment]
You haven't really explained your problem.

Might wanna check the docs: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#getuserdetailscallback

**Comment by Yumba** [comment]
`if (daysTheirEscrow != 0)
				{
					proceed=false;
					offer.decline(function(err)
					{
						console.log('>> Declined offer #'+offer.id+' from '+name+' (ID:'+steamid+'). | Reason: User is in Escrow for '+daysTheirEscrow+' days');
						if (err)
						{
							console.log('Decline error: '+err);
						}
					});	
					return;
				}`
If I get a offer, it declines it directly and this error happens.

**Comment by scholtzm** [comment]
But have you checked the docs?

**Comment by Yumba** [comment]
I did not code that bot. I just updated the bot and node, and now I need to change some functions because they do not exist in the new versions. 

> But have you checked the docs? 
I Guess

**Comment by DoctorMcKay** [comment]
This is not the place to ask for help coding your things.

If you don't know how to fix it, I suggest that you stick with version 1.
