### ISSUE TITLE
Error eresult 28 and getReceivedItems empty items

### ISSUE THREAD

**Issue by esvills** [DoctorMcKay/node-steam-tradeoffer-manager#209]
![image](https://cloud.githubusercontent.com/assets/3481684/22795542/b5e43054-eeff-11e6-843d-ff2ed8d27227.png)
1. Why  many error eresult 28 and many error "Error getting trade offers for poll: Data temporarily unavailable" (pollInterval -  7000) I increase pollInterval  or decrease pollInterval ?

2. Method receivedOfferChanged + offer.getReceivedItems sometimes gives out empty items

Thanks

**Comment by DoctorMcKay** [comment]
Those are all issues with Steam, and there's nothing you can do when they're happening but wait and try again later.
