### ISSUE TITLE
Attempting to send a tradeoffer using setTimeout() fails and the offer is not sent.

### ISSUE THREAD

**Issue by WeeSkilz** [DoctorMcKay/node-steam-tradeoffer-manager#21]
When an offer is sent using `setTimeout()` its status immediately after it is sent is always pending: eg. email confirmation required, even on an account with email authentication disabled.

I was wondering if anyone could replicate this and, if so, could suggest a fix.

**Comment by DoctorMcKay** [comment]
Please show the code that is giving you problems.

**Comment by WeeSkilz** [comment]
https://gist.github.com/WeeSkilz/e2d5a24f09b93d24ac46

Both the first and second offers show as pending.

**Comment by DoctorMcKay** [comment]
That code looks fine to me. By pending, you mean that `status` is `"pending"`? Is the offer actually getting sent or is it sending an email or something?

**Comment by WeeSkilz** [comment]
Status is pending however no email is sent and the offer is not sent.

**Comment by DoctorMcKay** [comment]
Are you doing anything with `offer` and `ownerOffer` between when you create them and when you send them in the timeout callback?

The only way it could possibly be `pending` is if Steam reports back `needs_email_confirmation`.

Are you sure you're logged into the correct account?

**Comment by WeeSkilz** [comment]
Caused by a miscommunication with the person who owned the account. I had disabled emails and it was re-enabled.
