### ISSUE TITLE
How could i trade skins under .45 to somebody else

### ISSUE THREAD

**Issue by Monphito** [DoctorMcKay/node-steam-tradeoffer-manager#210]
I have tried doing this but can not wrap my head around it can you help with this that would be greatly appreciated. Or if you can set me in the right direction that would be great i didn't know where else to put this.

**Comment by Monphito** [comment]
I dont want code i just would like to be pointed in the right direction

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You need to get prices from somewhere. You might want to check [OPSkins](https://opskins.com/kb/api-ipricing).
