### ISSUE TITLE
Cannot read property 'appid' of undefined

### ISSUE THREAD

**Issue by codefln** [DoctorMcKay/node-steam-tradeoffer-manager#212]
Hi all. Please help with my problem

node bot.js

Logged into Steam
[]
/Users/code/Documents/node/steam/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:421
	if (typeof details.appid === 'undefined' || typeof details.contextid === 'undefined' || (typeof details.assetid === 'undefined' && typeof details.id === 'undefined')) {
	                  ^

TypeError: Cannot read property 'appid' of undefined
    at addItem (/Users/code/Documents/node/steam/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:421:20)
    at TradeOffer.addMyItem (/Users/code/Documents/node/steam/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:332:9)
    at manager.loadInventory (/Users/code/Documents/node/steam/bot.js:70:10)
    at SteamCommunity.<anonymous> (/Users/code/Documents/node/steam/node_modules/steamcommunity/components/users.js:331:5)
    at Request._callback (/Users/code/Documents/node/steam/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/Users/code/Documents/node/steam/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/code/Documents/node/steam/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)

**Comment by codefln** [comment]
My code:
`const SteamUser = require('steam-user');
const SteamTotp = require('steam-totp');
const SteamCommunity = require('steamcommunity');
const TradeOfferManager = require('steam-tradeoffer-manager');

const client = new SteamUser();
const community = new SteamCommunity();
const manager = new TradeOfferManager({
	steam: client,
	community: community,
	language: 'en'
});

const logOnOptions = {
	accountName: '****',
	password: '****',
	twoFactorCode: SteamTotp.generateAuthCode('****')
};

client.logOn(logOnOptions);

client.on('loggedOn', () => {
	console.log('Logged into Steam');

	client.setPersona(SteamUser.Steam.EPersonaState.Online);
	client.gamesPlayed(440);
});

client.on('webSession', (sessionid, cookies) => {
	manager.setCookies(cookies);

	community.setCookies(cookies);
	community.startConfirmationChecker(10000, '****');

	sendRandomItem();
});

manager.on('newOffer', (offer) => {
	if (offer.partner.getSteamID64() === '****') {
		offer.accept((err, status) => {
			if (err) {
				console.log(err);
			} else {
				console.log(`Accepted offer. Status: ${status}.`);
			}
		});
	} else {
		offer.decline((err) => {
			if (err) {
				console.log(err);
			} else {
				console.log('Canceled offer from scammer.');
			}
		});
	}
});

function sendRandomItem() {

	const partner = '****';
	const appid = 440;
	const contextid = 2;
	const offer = manager.createOffer(partner);

	manager.loadInventory(appid, contextid, true, (err, myInv) => {
		if (err) {
			console.log(err);
		} else {
			const myItem = myInv[Math.floor(Math.random() * myInv.length - 1)];
			offer.addMyItem(myItem);

			manager.loadUserInventory(partner, appid, contextid, true, (err, theirInv) => {
				if (err) {
					console.log(err);
				} else {
					const theirItem = theirInv[Math.floor(Math.random() * theirInv.length - 1)];
					offer.addTheirItem(theirItem);

					offer.setMessage(`Will you trade your ${theirItem.name} for my ${myItem.name}?`);
					offer.send((err, status) => {
						if (err) {
							console.log(err);
						} else {
							console.log(`Sent offer. Status: ${status}.`);
						}
					});
				}
			});
		}
	});
}`

**Comment by DoctorMcKay** [comment]
https://dev.doctormckay.com/topic/885-typeerror-cannot-read-property-appid-of-undefined/
