### ISSUE TITLE
Send offers problem: Error: Access Denied

### ISSUE THREAD

**Issue by codefln** [DoctorMcKay/node-steam-tradeoffer-manager#213]
My function:

function sendOrder ( logOnOptions, offerLink ) {

  var client = new SteamUser();
  var manager = new TradeOfferManager({
    "steam": client, // Polling every 30 seconds is fine since we get notifications from Steam
    "domain": "example.com", // Our domain is example.com
    "language": "en" // We want English item descriptions
  });
  var community = new SteamCommunity();

  if (fs.existsSync('polldata.json')) {
    manager.pollData = JSON.parse(fs.readFileSync('polldata.json'));
  }

  client.logOn(logOnOptions);

  client.on('loggedOn', function() {
    console.log("Logged into Steam");
  });

  client.on('webSession', function(sessionID, cookies) {

    manager.setCookies(cookies, function(err) {
      if (err) {
        console.log(err);
        process.exit(1); // Fatal error since we couldn't get our API key
        return;
      }

      console.log("Got API key: " + manager.apiKey);

      // Get our inventory
      manager.loadInventory(730, 2, true, function(err, inventory) {
        if (err) {
          console.log(err);
          return;
        }

        if (inventory.length == 0) {
          // Inventory empty
          console.log("CS:GO inventory is empty");
          return;
        }

        console.log("Found " + inventory.length + " CS:GO items");

        // Create and send the offer
        var offer = manager.createOffer(offerLink);
        offer.addMyItems(inventory);
        offer.setMessage("Here, have some items!");
        offer.send(function(err, status) {
          if (err) {
            console.log(err);
            return;
          }

          if (status == 'pending') {
            // We need to confirm it
            console.log(`Offer #${offer.id} sent, but requires confirmation`);
            
            community.acceptConfirmationForObject(logOnOptions.identySecrect, offer.id, function(err) {
              if (err) {
                console.log(err);
              } else {
                console.log("Offer confirmed");
              }
            });
          } else {
            console.log(`Offer #${offer.id} sent successfully`);
          }
        });
      });
    });

    community.setCookies(cookies);
  });

  manager.on('sentOfferChanged', function(offer, oldState) {
    console.log(`Offer #${offer.id} changed: ${TradeOfferManager.ETradeOfferState[oldState]} -> ${TradeOfferManager.ETradeOfferState[offer.state]}`);
  });

  manager.on('pollData', function(pollData) {
    fs.writeFile('polldata.json', JSON.stringify(pollData), function() {});
  });

}

After calling it, I get an error:

Logged into Steam
Error: Access Denied
    at SteamCommunity.<anonymous> (/Users/code/Documents/node/steam/node_modules/steamcommunity/components/webapi.js:15:20)
    at Request._callback (/Users/code/Documents/node/steam/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/Users/code/Documents/node/steam/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/code/Documents/node/steam/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/Users/code/Documents/node/steam/node_modules/request/request.js:1091:12)
    at Gunzip.g (events.js:291:16)

Please help me

**Comment by DoctorMcKay** [comment]
Answering on the dev forum, which is the proper place to ask these questions.
