### ISSUE TITLE
Error: Unknown SteamID input format

### ISSUE THREAD

**Issue by bimbomaria70** [DoctorMcKay/node-steam-tradeoffer-manager#214]
I found a new bug yesterday and it crashed my bot.

uncaughtException: Error: Unknown SteamID input format \"[U:1:24614013Âą]\"\n    at new SteamID (/home/bot/node_modules/steam-tradeoffer-manager/node_modules/steamid/index.js:101:9)

**Comment by DoctorMcKay** [comment]
It seems your SteamID is somehow corrupt. The bug is on your end.
