### ISSUE TITLE
Error polling for trade offers: Error: socket hang up

### ISSUE THREAD

**Issue by bimbomaria70** [DoctorMcKay/node-steam-tradeoffer-manager#215]
I got this error every 2-4 hours.

Error polling for trade offers: Error: socket hang up
Error polling for trade offers: Error: socket hang up
Error polling for trade offers: Error: socket hang up

Why? connection is good.

**Comment by DoctorMcKay** [comment]
Not a bug in the module. Networks can be unreliable.
