### ISSUE TITLE
Missing appid contextid and or assetid whein adding inventory in addTheirItem function

### ISSUE THREAD

**Issue by dilipsoni** [DoctorMcKay/node-steam-tradeoffer-manager#216]
I am login like a bot , I am getting inventory from database of other member i am getting error message that you are login from another device , or when i pass inventory into addthieritem and make offer i get error missing appid contextid or assetid where as i am passing all inventory in to this function. here is example

var offer = manager.createOffer("https://steamcommunity.com/tradeoffer/new/?partner=370473804&token=954wS5y5");
						
						offer.loadPartnerInventory(730, 2, function(err, theirItems) {
						if(err) {
							console.error(err);
							return;
						}
						
						console.log(theirItems);
						
						//offer.addMyItems(rowss);
						offer.addTheirItem(theirItems);

**Comment by andrewda** [comment]
`theirItems` is an array. You should be using the `offer.addTheirItems` method (not `.addTheirItem`) in order to add an array of items.
