### ISSUE TITLE
There was an error sending your trade offer. please try again later

### ISSUE THREAD

**Issue by dilipsoni** [DoctorMcKay/node-steam-tradeoffer-manager#217]
I am login from bot . i am using function load partner inventory and passing the inventory in the addTheirItems function and getting result There was an error sending your trade offer. please try again later
You have logged in from new device. In order to protect the item in your inventory you will be unable to trade from this device for 7 days. i am getting this error how can is solve this any solution for this please?

here is my code 

client.on('webSession', function(sessionID, cookies) {
	manager.setCookies(cookies, function(err) 
	{

var mysql = require("mysql");

var con = mysql.createConnection({
			  host: "localhost",
			  user: "root",
			  password: "",
			  database: "scratchcard",
			  supportBigNumbers: true,
			  bigNumberStrings: true
			});
			
			con.connect(function(err){
			  if(err){
				console.log('Error connecting to Db');
				return;
			  }
			  console.log('Connection established');
			});
			
			var inventory = [];
			con.query('SELECT * FROM tbl_conflip_game where from_make_offer_id="" order by game_id desc',function(err,rows){
			  if(err) throw err;

			//  console.log('Data received from Db:\n');
			
			  for (var i = 0; i < rows.length; i++) {
				  
			   
				  game_ids  = rows[i].game_id;
				  from_user_id  = rows[i].from_user_id;
				  
				  con.query('SELECT offer_id,game_id,user_id,assets_id as assetid,contextid,appid FROM tbl_offers Where game_id = ? and user_id = ?',
										  [game_ids, from_user_id],function(err,rowss)
					{
					  if(err) throw err;

					//  console.log('Data received from Db:\n');
					 // console.log(rowss);
					//	var jsonString = JSON.stringify(rowss);
						
					//	inventory = jsonString;
					//	console.log(rowss);
						con.query('SELECT * FROM trade_url where user_id='+from_user_id,function(err,trade)
					{
						if(trade.length!=0){
						trade_url = trade[0].trade_url;
						
						trade_url = trade[0].trade_url;

var offer = manager.createOffer("https://steamcommunity.com/tradeoffer/new/?partner=470473804&token=954wS5y5");
						
						offer.loadPartnerInventory(730, 2, function(err, theirItems) {
						if(err) {
							console.error(err);
							return;
						}
						
						console.log(theirItems);
						
						//offer.addMyItems(rowss);
						offer.addTheirItems(theirItems);

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You have logged in from a new device. You can't trade from a new device for 7 days. You fix it by waiting.

Make sure you're recording your sentryfile or Steam Guard cookie and using it again later. If you're using node-steam-user, it saves the sentryfile automatically and will use it automatically for subsequent logins on the same machine.
