### ISSUE TITLE
Get the new id then of accepting the trade.

### ISSUE THREAD

**Issue by Unkn09wn** [DoctorMcKay/node-steam-tradeoffer-manager#22]
I am currently doing a bot that records items received in a MySQL database. But I’ve noticed that once accepted the trade objects ID (assetid) changes. So then it is impossible to identify you when you send these objects to another user.

Would there be a way to get the actual object id received within the event ‘receivedOfferChanged’?

**Comment by DoctorMcKay** [comment]
You can get the new asset IDs of the items you receive using `getReceivedItems`. At this time, I'm unsure if the order of items in `getReceivedItems` matches the order of items in `itemsToReceive`, but in all cases I've checked, they do.

**Comment by Unkn09wn** [comment]
Thank you! You're great.
