### ISSUE TITLE
Can i create real-time trade with this module.

### ISSUE THREAD

**Issue by lian88jian** [DoctorMcKay/node-steam-tradeoffer-manager#220]
hello~ i only find one document (https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/Real-Time-Trades) about real-time trade, can you offer a link about how to create the real-time trade..  thank you~

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You can use [node-steam-trade](https://github.com/seishun/node-steam-trade) for real-time trading.
