### ISSUE TITLE
Error: There was an error sending your trade offer.  Please try again later. (26)] eresult: 26 

### ISSUE THREAD

**Issue by dilipsoni** [DoctorMcKay/node-steam-tradeoffer-manager#221]
When i sending trade offer for one user its working fine , and when i selecting other user inventory and sending trade offer using node js i am getting error like this { [Error: There was an error sending your trade offer.  Please try again later.
(26)] eresult: 26 }
How can i solve this ?

**Comment by scholtzm** [comment]
You are most likely trying to send trade offer with items that are no longer available in the inventory.

https://steamerrors.com/26

**Comment by dilipsoni** [comment]
i am sending offer as bot
and how can i solve this any solution ?

**Comment by scholtzm** [comment]
Don't try to send items which are not available in your inventory.

**Comment by dilipsoni** [comment]
Bot have no item in its inventory, but its working fine for other player inventory , its generating offer id easily. where i using firstplayer inventory its showing error 26

**Comment by dilipsoni** [comment]
Its working fine in csgoreaper for same product and not working in my application

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**
