### ISSUE TITLE
Please help: Unknown column 'NaN' in 'field list'".

### ISSUE THREAD

**Issue by AlaDyn172** [DoctorMcKay/node-steam-tradeoffer-manager#224]
CODE: https://pastebin.com/EuTd0n5S
ERROR: https://pastebin.com/ncE6H26k

Thanks for helping!

**Comment by andrewda** [comment]
This is a MySQL error and completely unrelated to this module. Please use Google to search for your issue first. http://stackoverflow.com/a/1346298
