### ISSUE TITLE
Adding a custom property to TradeOffer

### ISSUE THREAD

**Issue by Netifriik** [DoctorMcKay/node-steam-tradeoffer-manager#23]
Is it possible to add a custom property to TradeOffer that you could later check with getOffer?

**Comment by DoctorMcKay** [comment]
You mean like some context value to associate with an offer?

That possible, and is a good idea. I'll add it soon.

**Comment by DoctorMcKay** [comment]
See this: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#datakey-value

**Comment by Netifriik** [comment]
Awesome, thanks!
