### ISSUE TITLE
manager.getUserInventoryContents() not working

### ISSUE THREAD

**Issue by Koncealed** [DoctorMcKay/node-steam-tradeoffer-manager#230]
Hello, am I looking to get my inventory, and finding the cheapest item in my inventory.

I am looking for a response, and I am getting an error. https://pastebin.com/j3DXBp24

manager.getUserInventoryContents(76561198163142980 ,730, 2, true, function(err,inv,call){
	inventory = inv;
});

Is what I am using. Everything is logged in 100%

**Comment by andrewda** [comment]
Steam ID needs to be a steing
