### ISSUE TITLE
Multiple bots?

### ISSUE THREAD

**Issue by AlaDyn172** [DoctorMcKay/node-steam-tradeoffer-manager#231]
Hello,

I want to use multiple bots.
I have node v6.x ;)

**Comment by Aareksio** [comment]
Hello,

I want you to post on dedicated forum instead.
I have a saved reply for you ;)

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**

**Comment by AlaDyn172** [comment]
Ok, I will do this question to forum.
Thanks!
