### ISSUE TITLE
Language 'zh' doesn't work 

### ISSUE THREAD

**Issue by rover5056** [DoctorMcKay/node-steam-tradeoffer-manager#233]
`var offers = new TradeOfferManager({
    steam: client,
    domain: config.domain,
    language: "zh", // I want chinese item descriptions
    pollInterval: 8000, // (Poll every 8 seconds (8,000 ms)
    cancelTime: 300000 // Expire any outgoing trade offers that have been up for 5+ minutes (300,000 ms)
});`

I want getUserInventoryContents return me Inventory descriptions with chinese..But it doesn't work .It still return me with English..

**Comment by scholtzm** [comment]
For simplified Chinese, the correct language code is `schinese`.

**Comment by DoctorMcKay** [comment]
This is fixed in v2.7.5.
