### ISSUE TITLE
trades of some users don't get seen by the manager

### ISSUE THREAD

**Issue by aboyobam** [DoctorMcKay/node-steam-tradeoffer-manager#239]
This is how I create my offers 
`manager.createOffer('https://steamcommunity.com/tradeoffer/new/?partner='+accountid+'&token='+token);`

After that I add the items and send it. This works perfect, but if do
 `manager.getOffers(someCallback)` or `getOffer(offerid, someCallback)` 
then I get errors returned ('No Match').

 If I do `manger.on('sentOfferChanged', someCallback)` or `manger.on('receivedOfferChanged, someCallback)`
 I do not get a response if I accept/decline it.

On some accounts everything works perfectly, on other accounts the Manager doesn't find the trades.
I have 4 steam accounts (lvl 500, 100, 0, 0) lvl 500 and 100 own CSGO, trades with those two get recognized by the manager and the others not

**Comment by Aareksio** [comment]
You're probably trying to trade on limited account (limited API). You need to unlock your account before using the module, as it relies heavily on api access.

By the way, perfect example of how `createOffer` accepting trade url encourages bad habits...

> **Have a question about the module or coding in general? _Do not create a GitHub issue._ GitHub issues are for feature requests and bug reports. Instead, post in the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/). Such issues may be ignored!**
