### ISSUE TITLE
Implement "unknownOfferSent" event

### ISSUE THREAD

**Issue by kinsi55** [DoctorMcKay/node-steam-tradeoffer-manager#24]
Sometimes when you send an offer Steam will return an Error, thus the `.send` method failed, and did not return any `tradeofferid` (for further processing). It would be great if, when polling, any "unknown" offers like these ones, and ones that were sent outside of the tradeoffer manager could get piped trough to an `unknownOfferSent` event where you could cancel the trades, or do further stuff with them.

**Comment by Netifriik** [comment]
+1

**Comment by DoctorMcKay** [comment]
Added in 1.10.0.
