### ISSUE TITLE
receivedOfferChanged does not get triggered if offer is declined.

### ISSUE THREAD

**Issue by bennetgallein** [DoctorMcKay/node-steam-tradeoffer-manager#244]
First, my code:

`
manager.on('receivedOfferChanged', function(offer, oldState) {
console.log(`Offer #${offer.id} changed: ${TradeOfferManager.ETradeOfferState[oldState]} -> {TradeOfferManager.ETradeOfferState[offer.state]}`);

    if (offer.state == TradeOfferManager.ETradeOfferState.Accepted) {
        offer.getReceivedItems(function(err, items) {
            if (err) {
                console.log("Couldn't get received items: " + err);
            } else {
                var names = items.map(function(item) {
                    return item.name;
                });

                console.log("Received: " + names.join(', '));
                connection.query("UPDATE tradeoffer SET status='accepted' WHERE offerid='" + offer.id + "'", function(err, rows, fields) {
                    if (err) console.log(err);
                    postReq("accepted", offer.id);
                });
            }
        });
    }
    if (offer.state == TradeOfferManager.ETradeOfferState.Countered) {
        offer.decline();
        connection.query("UPDATE tradeoffer SET status='countered' WHERE offerid='" + offer.id + "'", function(err, rows, fields) {
            if (err) console.log(err);
            postReq("countered", offer.id);
        });
    }
    if (offer.state == TradeOfferManager.ETradeOfferState.Declined) {
        connection.query("UPDATE tradeoffer SET status='denied' WHERE offerid='" + offer.id + "'", function(err, rows, fields) {
            if (err) console.log(err);
            postReq("denied", offer.id);
        });
    }
    if (offer.state == TradeOfferManager.ETradeOfferState.InEscrow) {
        offer.decline();
        connection.query("UPDATE tradeoffer SET status='escrow' WHERE offerid='" + offer.id + "'", function(err, rows, fields) {
            if (err) console.log(err);
            postReq("escrow", offer.id);
        });
    }
    if (offer.state == TradeOfferManager.ETradeOfferState.InvalidItems) {
        connection.query("UPDATE tradeoffer SET status='invalid' WHERE offerid='" + offer.id + "'", function(err, rows, fields) {
            if (err) console.log(err);
            postReq("invalid", offer.id);
        });
    }
});
`

For some reason if the offer gets declined by the person to accept it, the function does not get triggered.. Maybe someone can help me?

**Comment by bennetgallein** [comment]
#push

**Comment by DoctorMcKay** [comment]
Answered on the forum by someone else.
