### ISSUE TITLE
Polldata Problem.

### ISSUE THREAD

**Issue by Barika2017** [DoctorMcKay/node-steam-tradeoffer-manager#245]
I have a question, and I'm seeking an answer for it. I'm using the newest steam trade offer manager, and would like to know when does the polldata clear out? Since the bot is running for 1 day already, and the file keeps growing and it never gets cleared. The problem with this is the bigger it is, the slower will the state processing be.

Please answer, thank you.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

Currently it doesn't prune old offers from the polldata. This doesn't really have an impact on performance.
