### ISSUE TITLE
newOffer not being triggered (using examples/storehouse-steam.js)

### ISSUE THREAD

**Issue by NeonWizard** [DoctorMcKay/node-steam-tradeoffer-manager#247]
This isn't a problem with the example code - I've been having this problem with any attempt I've made. I can log in perfectly fine using steam-totp to generate an auth code from my shared_secret. However, whenever I send a trade to the bot it doesn't trigger the 'newOffer' handler, even though startConfirmationChecker is called. I thought at first my identity_secret was wrong, but I checked multiple times and it's perfectly right. I've noticed a few other people have had this issue, so is there any solution or anything I should be looking out for?

Thanks.

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

Post in the forum and show the code you're using, please.
