### ISSUE TITLE
Error: Can't accept trade: not logged in

### ISSUE THREAD

**Issue by mor619dx** [DoctorMcKay/node-steam-tradeoffer-manager#248]
Hey,

So I noticed that after a few hours where I run a program and I receive trade offer I seem to be able to read the trade offer, I can confirm the items (the newOffer event function is being called).

But when I call to the accept function with the offer it return the error of not logged in.
I do not receive any 'error', 'disconnected' (from steam-user) or any exception in the program for that matter.

It only happen after a few hours and once I get the error I can't accept any offers (they return the same error).

Is there any solution? I know it suppose to reconnect by itself but it doesn't seem to do it.
I'm also ok with only get notify in case it disconnected so I just rerun the program.

**Comment by scholtzm** [comment]
Looks like your cookies just expired, you can listen to `sessionExpired` event emitted by `node-steamcommunity` and just refresh your cookies.

From: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#constructoroptions

> community - Optional. A node-steamcommunity instance of v3.19.1 or later to use. If not provided, one will be created internally automatically.

Also: https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#sessionexpired

**Comment by mor619dx** [comment]
@scholtzm I see, so it is more of a general problem since I didn't see any example have a try to reconnect option from steamcommunity?

How is it not happening to more people using those packages?

In order to reconnect I need to call community.setCookies(cookies) with the new cookies? which cookie should I use? right now I use the cookies I get from client.on('webSession') but this event isn't emitted when I reconnect. Will the Client have the corrected cookie?

**Comment by scholtzm** [comment]
@mor619dx Just call [`client.webLogOn()`](https://github.com/DoctorMcKay/node-steam-user#weblogon)
