### ISSUE TITLE
offer.accept failed with no error

### ISSUE THREAD

**Issue by mor619dx** [DoctorMcKay/node-steam-tradeoffer-manager#249]
Hey,

So I had a problem where I'm adding the items I accept to a db they aren't actually in my inventory, my code is very similar to the offloader.js example, although I am only receiving offers and not sending them.

I listen on the newOffer event and receive trade offers, I verify the trade and then call offer.accept, the callback is check if err exist:
`
if (err) {
console.log(err.message)
}
`
and if there isn't I add the items to a DB.
After some check I saw that sometimes a trade offer that received and become "Items Now Unavailable For Trade" before I managed to accept is recognized as a successfull trade - meaning: I call offer.accept and the callback return no error as a parameter. and since the code see there is no error it add it to DB although the trade didn't actually happened.

The offer send - received - and accept happen very fast on my end and it is happening quite frequently I receive a trade which have "Items Now Unavailable For Trade" text in the trade offers on steam.

Is this a bug? is there a way to know for sure the trade accepted and the items transfered?

I am using the latest version.

**Comment by DoctorMcKay** [comment]
Steam is known to do things like that. The best way to make sure that a trade was truly accepted is to wait for the `receivedOfferChanged` event to emit with new state `Accepted`.

I haven't seen a call to `accept()` that fails but returns success in a long time though.

**Comment by mor619dx** [comment]
@DoctorMcKay Thank you for the quick answer,
I noticed that the receivedOfferChanged event doesn't occur as fast as newOffer event, I assume it is because newOffer get notify and receivedOfferChanged is only polling.
I tried to speed it up by calling manager.doPoll(); in the accept function but didn't see really improvement in the speeds (do you have tips how to speed this?).

The problem I described doesn't happen a lot but I'm doing thousands of trades per day and performing them very quickly so I guess some trades are slips through this bug.

I changed and it seem to solve the problem.

**Comment by DoctorMcKay** [comment]
Are you calling doPoll() inside the callback to accept? If not, try that. If yes, try adding a short delay (maybe 5 seconds).
