### ISSUE TITLE
Steam Market Transactions

### ISSUE THREAD

**Issue by overheader** [DoctorMcKay/node-steam-tradeoffer-manager#25]
Is it possible with node-steam to buy the keys to the cases in cs:go (not marketplace)?

**Comment by andrewda** [comment]
No, this is not possible with Node-Steam.

**Comment by overheader** [comment]
After that it can be done?
I can pay for the work.

**Comment by andrewda** [comment]
It's certainly *possible*, but it'll require quite a lot of tedious work monitoring the CS:GO client.

**Comment by trzyrazyzero** [comment]
You dont need csgo client to buy keys.
example. http://store.steampowered.com/buyitem/730/1203/1

**Comment by DoctorMcKay** [comment]
This is firstly outside the scope of this module, and secondly I will never release anything that can automate purchasing as that's against the Steam Subscriber Agreement.

**Comment by overheader** [comment]
Thank you.
A full list of how to get an item (keys)?
