### ISSUE TITLE
getExchangeDetails needs a tradeID to work with rejected offers

### ISSUE THREAD

**Issue by verkhoumov** [DoctorMcKay/node-steam-tradeoffer-manager#250]
I use the `getExchangeDetails` method to get the `rollback_new_assetid` parameter, which is available when the trade is canceled. This method requires the `tradeID` parameter. At the same time, the `tradeID` parameter of the `Offer` object is `null`, since the offer was rejected. Because of this, I will never get a `rollback_new_assetid` when the trade is canceled.

**Comment by DoctorMcKay** [comment]
Yes, you've just described reality. There's no way to get trade details without a trade ID.
