### ISSUE TITLE
Accepting trade offer does not act at all

### ISSUE THREAD

**Issue by arnaspecelis** [DoctorMcKay/node-steam-tradeoffer-manager#253]
I'm using this method

`self.manager.getOffer(offerid, function (err, offer) {
if (err) {
...
} else {
..
offer.accept(true, function (err, status) {`

and it goes to the `accept` function but does nothing. Leaves the offer hanging and doesn't even calls the function? 

Where the problem could be? Sometimes it goes well and sometimes as I said..

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

You probably need to confirm it, which you can do with [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity).

**Comment by arnaspecelis** [comment]
No, it was sent not by me but by third party and I'm accepting it 30 seconds after it was sent to be sure its already confirmed.
