### ISSUE TITLE
How to check if user has mobile confirmation enabled before sending tradeoffer

### ISSUE THREAD

**Issue by shimonchick** [DoctorMcKay/node-steam-tradeoffer-manager#254]
Title says it all , i want to check if user has mobile confirmation before sending the trade instead off getting .Escrowdays after he accepts it. How do i do that ?

**Comment by scholtzm** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#getuserdetailscallback

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**
