### ISSUE TITLE
Method getUserInventoryContents() always fails with "Error: This profile is private."

### ISSUE THREAD

**Issue by Gameghostify** [DoctorMcKay/node-steam-tradeoffer-manager#256]
I recently have started using this great manager again and love it, however theres a problem loading **any** users inventory.

As far as that goes, it always fails with an `err` object stating `Error: This profile is private` even though it is not.
I have tried getting multiple users' inventories but sadly all im getting is said error, no matter if the profile of the user is really private or not.

For reference, here's my usage of the method:
`manager.getUserInventoryContents(steamID.toString(), 730, 2, false)`

(In this case I'm only using `toString()` to make sure the steamid is parsable into a SteamID-Object, as given in the docs. The callback simply logs the `error` or `inventory` object to the console)

Is there something obvious im missing here?

**Comment by DoctorMcKay** [comment]
Glad you found the problem. 😄
