### ISSUE TITLE
.editorconfig 💄

### ISSUE THREAD

**Issue by QuantumLlama** [DoctorMcKay/node-steam-tradeoffer-manager#257]
This can improve the code viewing experience on GitHub:

It seems GitHub defaults to 8 spaces.
Before: https://i.gyazo.com/9fecbf7cae06afe0047e633643ac88e5.png
After: https://i.gyazo.com/f94c922887b2eeeeb88086fe56490465.png

Example .editorconfig (details at http://editorconfig.org):

```
root = true

[*]
charset = utf-8
indent_style = tab
indent_size = 4
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
insert_final_newline = false
trim_trailing_whitespace = false
```

Thanks

**Comment by DoctorMcKay** [comment]
TIL. Thanks.
