### ISSUE TITLE
apiKey not set (yet)

### ISSUE THREAD

**Issue by MordorKing78** [DoctorMcKay/node-steam-tradeoffer-manager#258]
I'm having this issue were it's throwing an error saying the apiKey is not set and I have no idea why.. it used to work fine but now it says the apiKey is not set and then after like five minutes it is set and everything works fine.. but it's really a shame that I have to wait 5 minutes to be able to restart my server..

Any idea?

Edit: also whenever the server is restarted it's sometimes showing `Error: Error: ETIMEDOUT`

**Comment by DoctorMcKay** [comment]
You're trying to do things before you've called setCookies and waited for the callback.

**Comment by MordorKing78** [comment]
I've tried only listening the node after setting the cookies, still won't work properly.

**Comment by DoctorMcKay** [comment]
Then you aren't checking for an error in that callback.

**Comment by MordorKing78** [comment]
I know have it setup for it to wait till a apikey has been detected but sometimes may take very long, where should I be checking for this error?

**Comment by DoctorMcKay** [comment]
In the callback to setCookies.

**Comment by MordorKing78** [comment]
You are very quick to respond, would it be something like the following,
`	manager.setCookies(cookies, function(){
		//Start Server
	});`

**Comment by DoctorMcKay** [comment]
Please read the docs. That callback can have an error, and you need to check that error. You should only start doing things if the callback is fired without an error.

**Comment by MordorKing78** [comment]
Yeah, that was what I meant. It would then be `function(key, err)` if I'm correct.

`callback - Optional. Will be called once the API key is retrieved and the module is ready for use. The first argument will be null on success or an Error object on failure. You'll get an Access Denied error if your account is limited.`

**Comment by DoctorMcKay** [comment]
No, it's just `function(err) { }`

**Comment by MordorKing78** [comment]
Kinda works, I mean it can still take a while for the server to be ready to listen. I'm guessing thats just the delay from the session. 

Thanks.
