### ISSUE TITLE
unknownOfferSent triggers on every own offer sent

### ISSUE THREAD

**Issue by Gameghostify** [DoctorMcKay/node-steam-tradeoffer-manager#260]
The event `unknownOfferSent` seems to trigger for almost every single offer that has been sent after the poll data has been cleared. This results in hundreds of events being triggered after each restart.

Is there any fix to it?

A bare-bones setup looks like the following:

`manager.on("unknownOfferSent", function(offer) {
	console.log(offer.id);
});`

This will result in hundreds of (different!) `offer.id`'s being logged each second (it *will* eventually stop depending on how many tradeoffers have been sent from the account that the tradeoffers are being polled from)

**Comment by Gameghostify** [comment]
#130 seems to be somewhat similar of an issue. They didn't share any details of their event handling setup.

**Comment by DoctorMcKay** [comment]
That's the idea. If the offer isn't in poll data then it's not known, and if it sees an offer that was sent that's not known, it triggers unknownOfferSent.

**Comment by Gameghostify** [comment]
Oh, I see. It does make more sense that way; checking the tradeofferstate could be done manually.
Thank you for the explaination.
