### ISSUE TITLE
PUBG items stacking?

### ISSUE THREAD

**Issue by Baterka** [DoctorMcKay/node-steam-tradeoffer-manager#265]
Is there way how to send trade offer for some amount of PUBG items (primary keys)? PUBG have system for stacking (bundling) items together, but there it not any .amount property as Gems have

**Comment by andrewda** [comment]
PUBG does _not_ have a system for sending groups of items together, that is solely in the PUBG UI and not how the inventory system works, unlike games like Spiral Knights which do actually allow you to send stacks of currencies. Each item has its own unique `assetId` which you will need to use when sending the item.

**Comment by Baterka** [comment]
Every item ihave `amount` property what I see... But when I change this amount to for example 1 from 5 I will get trade offer for 5 keys... What the fuck :D

**Comment by andrewda** [comment]
`amount` is only to be used for games that have item stacking built in. PUBG does not, so `amount` will always be `1`.

**Comment by Baterka** [comment]
Not true. I checked it now. I have 5 PUBG keys in stack. There is `amount: 5`
When I change amount to 2, bot will send just 2 keys in stack. So I think this is not issue
