### ISSUE TITLE
Offer state change when bot offline

### ISSUE THREAD

**Issue by Baterka** [DoctorMcKay/node-steam-tradeoffer-manager#266]
Imagine bot go offline after tradeoffer sent. User will accept offer and presumes that he will get some codes into chat. But whoops bot went offline right before user accepted offer. Bot starts 1 minute later and he dont know about any accepted offer when he was offline. How to solve this?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

This is what poll data is for.
