### ISSUE TITLE
send offer gives error

### ISSUE THREAD

**Issue by adaptivedev** [DoctorMcKay/node-steam-tradeoffer-manager#27]
I'm also getting: [Error: Malformed response]

I'm getting the callback from setCookies with the apiKey, and only later calling the createOffer call below.

BTW, I try to print out the body that's malformed in lib/index.js but nothing get printed. It's strange. It's as if it's coming from somewhere else.

I started from the example code in which login works, as does trade discovery/accept.

```
// EXAMPLE FILE USE OF COOKIES

client.on('webSession', function(sessionID, cookies) {
	manager.setCookies(cookies, function(err) {
		if(err) {
			console.log(err);
			process.exit(1); // Fatal error since we couldn't get our API key
			return;
		}
		console.log("Got API key: " + manager.apiKey);
	});
});

// HERE IS YOUR CODE I AM TRYING TO USE
		var offer = manager.createOffer(partnerSteamId);
		manager.loadInventory(440, 2, true, function(err, myItems) {
			if(err) {
				console.error(err);
				return;
			}
			
			offer.loadPartnerInventory(440, 2, function(err, theirItems) {
				if(err) {
					console.error(err);
					return;
				}
				
				offer.addMyItem(myItems[0]);
				offer.addTheirItem(theirItems[0]);
				offer.send("");
			});
		});
```

THANKS!

**Comment by DoctorMcKay** [comment]
I don't fully understand the issue. The example code doesn't work for you?

**Comment by adaptivedev** [comment]
I'm also getting: [Error: Malformed response]

I had the wrong appid for my game. Make sure you have that correct, as explained here:

http://steamcommunity.com/groups/SteamRE/discussions/3/537402115077785228/#p1

We can close this issue.

Thanks!
