### ISSUE TITLE
How to get context id？

### ISSUE THREAD

**Issue by JethroSovr** [DoctorMcKay/node-steam-tradeoffer-manager#272]
"contextid - The ID of the "context" within the game you want to retrieve"
I see the documents and However dont know what the meaning is ...
"manager.getInventoryContents(730, 2, true, function(err, inventory)"
I dont know what the 2 meaning for ?
Can someone  explain for me.. 
Very appreciate it~

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#getpartnerinventorycontentsappid-contextid-callback

You can get your own inventory contexts through [steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity).

In practice though, most games just have a static context ID. For all current Valve games and most third-party games, it's 2.
