### ISSUE TITLE
Unknown SteamID format for trade links

### ISSUE THREAD

**Issue by mordigann228** [DoctorMcKay/node-steam-tradeoffer-manager#275]
![image](https://user-images.githubusercontent.com/25629578/38307630-e3a09172-3846-11e8-8557-86c8138c5f07.png)
Yesterday I openned the same issue, but you closed it with single comment "Update". I am on the latest version of tradeoffer manager, so the problem is not in the version

**Comment by DoctorMcKay** [comment]
And yesterday I asked what your version number is.

**Comment by mordigann228** [comment]
@DoctorMcKay 2.9.3

**Comment by DoctorMcKay** [comment]
Show your code.

**Comment by mordigann228** [comment]
@DoctorMcKay 
![image](https://user-images.githubusercontent.com/25629578/38327786-ba34cc60-387b-11e8-8632-acdd84d1d727.png)
![image](https://user-images.githubusercontent.com/25629578/38327824-d3fe5580-387b-11e8-8059-71a90814183c.png)

**Comment by mordigann228** [comment]
and user.tradelink returns a string from the DB
![image](https://user-images.githubusercontent.com/25629578/38328412-794ccafc-387d-11e8-8d9d-5c67b790e73f.png)

**Comment by DoctorMcKay** [comment]
`getUserInventoryContents` expects a SteamID as its first argument, not a trade URL.
