### ISSUE TITLE
Trade offer is not being sent

### ISSUE THREAD

**Issue by mordigann228** [DoctorMcKay/node-steam-tradeoffer-manager#276]
![image](https://user-images.githubusercontent.com/25629578/38383063-0eeca10c-393e-11e8-9261-a83841f8997d.png)
![image](https://user-images.githubusercontent.com/25629578/38383142-438c58ee-393e-11e8-9a5e-cd5474967ff8.png)

This might be my last question here, but the trade offer with the selected item for the bot is not being sent at all, what could possibly be the problem? It does not even log an error, it just does nothing.

**Comment by DoctorMcKay** [comment]
**Please direct questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**
