### ISSUE TITLE
Detecting invalid cookies

### ISSUE THREAD

**Issue by scholtzm** [DoctorMcKay/node-steam-tradeoffer-manager#28]
Tradeoffer manager is currently detecting certain cases, when the trade offer simply cannot be sent/accepted, e.g. `NewDevice`. However, it's still not detecting invalid cookies.

If cookies become invalid, it's impossible to accept or send any trade offer without "refreshing" the cookies.

Manager currently does this:

- when accepting trade offer, manager will return error "HTTP error 403". If auto-retry is enabled, manager will attempt to repeatedly accept the trade offer even though it's impossible
- when sending trade offer, manager will emit error "HTTP error 401"

It's possible to detect invalid cookies by checking the response from `request` module. In both cases, the `cookie` header will no longer contain `steamLogin` nor `steamLoginSecure` cookies.

It would be great if manager detected these cases and provided appropriate `error.cause`.

Here's my [testing script](https://gist.github.com/scholtzm/65facbd95814f8e20c76).

**Comment by DoctorMcKay** [comment]
For a while I've wanted to detect when the session is invalid and emit an event prompting the user to supply new cookies, after which the pending requests would be completed immediately. I'll see when I can get around to this.

**Comment by GlebkaF** [comment]
Why did cookie become invalid? My bot working for 5 min and then i got 403 error again and again.

**Comment by DoctorMcKay** [comment]
Did you login to the account elsewhere?

**Comment by GlebkaF** [comment]
Yes, do you think it's the reason?

**Comment by DoctorMcKay** [comment]
Logging in elsewhere invalidates current sessions in my experience.

**Comment by GlebkaF** [comment]
@DoctorMcKay ok, thank you for advice

**Comment by dnowitski69** [comment]
What's the best way to deal with an invalid session using node-steam-user?

a) calling logOn()
b) calling webLogOn() (as per wiki "but you can call webLogOn() to create a new session if your old one expires or becomes invalid.")

Thanks!

**Comment by DoctorMcKay** [comment]
You never need to call `logOn` again while you're currently logged on. Just call `webLogOn` and wait for the `webSession` event to refresh your web session.

**Comment by dnowitski69** [comment]
Thank you for your reply.

I've been calling logOff to simulate the error however this will disconnect the bot from Steam network and will require logOn; webSession will not suffice in this case.

Is there any way to simulate an invalid session by destroying the cookies?

**Comment by scholtzm** [comment]
Dummy values would do the trick.

**Comment by GlebkaF** [comment]
Hi guys, when my cookies became invalid im calling webLogOn and then i'm trying to set new cookies, but I get error: [Error: HTTP error 403] code: 403.
```
this.client.on('webSession', function(sessionID, cookies){
		self.offers.setCookies(cookies, function (err){
			if (err) {
				debug('Unable to set trade offer cookies: ',err)
				process.exit(-1) 
			}	
		});
});
```
What should i do in this case to fix this issue?

**Comment by adaptivedev** [comment]
I also get this error. When should we call client.webLogOn, and when should we call:
	bot.community.login(login_details, function(err, session_id, cookies, steamguard)
?

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/wiki/HTTP-Hooks

**Comment by scholtzm** [comment]
Just to make this clear for everyone including myself, the suggested way would be to use "post HTTP hook" and check the `httpError`?

Also, if using both steamcommunity as well as manager, I'm assuming it's probably best to instantiate manager with an already active steamcommunity instance.

**Comment by DoctorMcKay** [comment]
Sorry, I didn't mention that along with those hooks, the latest version of steamcommunity also has a `sessionExpired` event.
