### ISSUE TITLE
Got some error in a JSON.pase

### ISSUE THREAD

**Issue by justazul** [DoctorMcKay/node-steam-tradeoffer-manager#280]
`Mem:   0 MB    CPU:  0 %  stopped xx cardbot >     at JSON.parse (<anonymous>)                                                                                                                         x
x                                                                     xx cardbot >     at _getFromDisk (/home/cappi/cardbot/cardbot/node_modules/steam-tradeoffer-manager/lib/index.js:130:26)                                             x
x                                                                     xx cardbot >     at storage.readFiles (/home/cappi/cardbot/cardbot/node_modules/steam-tradeoffer-manager/lib/index.js:268:4)                                         x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:52:16                                                      x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:361:13                                                     x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:52:16                                                      x
x                                                                     xx cardbot >     at done (/home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:246:17)                                              x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:44:16                                                      x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/node_modules/async/lib/async.js:358:17                                                     x
x                                                                     xx cardbot >     at /home/cappi/cardbot/cardbot/node_modules/file-manager/index.js:119:4`

Somehow a bad json was save in the Disk, and this module does not handle bad json files :(

**Comment by DoctorMcKay** [comment]
Fixed in 38d2407.
