### ISSUE TITLE
receivedOfferChanged dont receive offer.id

### ISSUE THREAD

**Issue by live4net** [DoctorMcKay/node-steam-tradeoffer-manager#282]
I got problem with receivedOfferChanged. It don't receive offer.id and status. Below is my code and output from console.

```
    var botsManager = new BotManager();

    botsManager.on('receivedOfferChanged', function(offer, oldState) {
                       console.log('--> STATUS ' + offer.id + ':' + offer.tradeID + ': (OLD:' + oldState + ') TO (NEW:' + offer.state + ')');
    });
```

Output:

--> STATUS undefined:undefined: (OLD:[object Object]) TO (NEW:undefined)

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**

https://dev.doctormckay.com/topic/1729-receivedofferchanged-dont-receive-offerid/
