### ISSUE TITLE
Error with sending offer : {}

### ISSUE THREAD

**Issue by P4R4P3T** [DoctorMcKay/node-steam-tradeoffer-manager#283]
Hi, guys. I have a problem. My bots can not send offers after a period of time, but they can listen for events. What to do?

**Comment by DoctorMcKay** [comment]
Gonna need more detail than that.

**Comment by P4R4P3T** [comment]
@DoctorMcKay, I have one more question. I have such a problem: How do I make the session to be 24/7 and hold without falling for at least a month? I use a lot of IP addresses so that Steam does not block them because of frequent updates to the session.

`    var SteamClient = require('steam-user');
    SteamClient.on('webSession', (sessionsID, cookies) => {
        
        // node-steamcommunity
        var Steam = new SteamCommunity({
            localAdress : ip,
        });
        Steam.setCookies(cookies);
        
        // node-steam-tradeoffer-manager
        var Manager = new SteamTradeofferManager({
            steam : SteamClient,
            community : Steam,
            domain : ip,
            language : 'en',
            pollInterval : 1000,
        });
    
        Steam.on('sessionExpired', () => {
            SteamClient.webLogOn(); 
        });
        
        setTimeout(function() {
            SteamClient.webLogOn();
        }, 45 * 60 * 1000); // 45 minutes
    });`

In all modules I use the same ip. Maybe i need to put some interval on the check or something else? It is necessary to make the bot work 24/7, including technical work (or put it on pause), but I can not do relogin, this is the problem.
Thank you for your time, dear @DoctorMcKay

**Comment by DoctorMcKay** [comment]
Login more frequently. Put your webLogOn on an interval, not a one-off timeout.
