### ISSUE TITLE
Trade offers

### ISSUE THREAD

**Issue by Nikita2150** [DoctorMcKay/node-steam-tradeoffer-manager#284]
Hey, I've created a bot and when I write to him !sell [item], he displays me how much i need to pay and creates a offer - with the item and his payment.
The problem is it sometimes sends me the payment and I shouldn't give him anything. I've checked it with itemsToGive ItemsToRecieve and it didn't work.
Then I saw the isGlitched() method but everytime the bot sends a trade, it shows that it's glitched although sometimes it isn't..

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [dedicated forum](https://dev.doctormckay.com/forum/9-node-steam-tradeoffer-manager/).**
