### ISSUE TITLE
Use `partnerinventory` endpoint when loading partner's inventory

### ISSUE THREAD

**Issue by scholtzm** [DoctorMcKay/node-steam-tradeoffer-manager#29]
It looks like manager is currently using the "regular" (`inventory/json/:appid/:contextid`) inventory endpoint for partner inventory retrieval.

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L227
https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/users.js#L241

However, Steam uses different endpoint for partner inventories - `tradeoffer/new/partnerinventory`. This endpoint provides 2 advantages:
* tradable items only
* works for private inventories (provides subset of items necessary to "decode" the offer)

**Comment by DoctorMcKay** [comment]
- It's already loading only tradable items from the regular endpoint
- Is the data in the `itemsToReceive` array not sufficient? Is something missing?

**Comment by scholtzm** [comment]
I completely missed this https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/assets.js#L91

I suppose providing `partnetinventory` loading might be beneficial in some cases, it's probably not necessary. Closing for now.

**Comment by DoctorMcKay** [comment]
I'm not opposed to the idea, I just don't want to reimplement inventory loading. The module previously used the partnerinventory endpoint, but I moved inventory loading to `node-steamcommunity` where it's self-contained. I'd rather not write the code twice if it's not necessary, is all.
