### ISSUE TITLE
getOffer using

### ISSUE THREAD

**Issue by zyznos321** [DoctorMcKay/node-steam-tradeoffer-manager#3]
Could You help me?
How can I use getOffer method?

I try this but it not working:

var offer;
manager.getOffer(568651808, offer);

it return error: undefined is not a function
(tradeoffer.js line 39)

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE).

The second parameter needs to be a callback function.

```js
manager.getOffer(offerID, function(err, offer) {
    if(err) {
        // Some error occurred
    } else {
        // Success, offer is a TradeOffer object
    }
});
```
