### ISSUE TITLE
Invalid sessions or 401 after a while

### ISSUE THREAD

**Issue by Netifriik** [DoctorMcKay/node-steam-tradeoffer-manager#30]
I'm getting invalid session or 401 unauthorized errors after running the bot for a while. How should I manage these errors?

**Comment by DoctorMcKay** [comment]
When you get such errors you should renew your web session (log in again and set new cookies). You can usually avoid them by periodically relogging automatically. I relog hourly and I rarely have problems.

**Comment by Netifriik** [comment]
"Could not fetch offer: 849368180 items. Error:  Error: No session" - I started the bot ~10-15 minutes ago.

**Comment by DoctorMcKay** [comment]
Steam might be acting up. It happens frequently.

**Comment by kenzik** [comment]
@DoctorMcKay Would you mind sharing your relogging code?

Here's what I'm doing but it doesn't seem to work:
```
manager.shutdown();
client.logOff();
logOnOptions['twoFactorCode'] = SteamTotp.generateAuthCode(totp_data.shared_secret);
client.logOn(logOnOptions);
```

**Comment by DoctorMcKay** [comment]
You don't need to do all that. Just call `webLogOn` in node-steam/node-steam-user and then call `setCookies` when you get new web session cookies.
