### ISSUE TITLE
Manager events are not emmited

### ISSUE THREAD

**Issue by TGamingStudio** [DoctorMcKay/node-steam-tradeoffer-manager#300]
Hello, manager does not run any of events i've created.
`manager.on("sentOfferChanged", function (offer, oldState) {
//Code
})`
does nothing.
Sending offers and loading  inventory works okay. But this or any other events are not emmited. What can i do? I haven't changed polling Interval (kept default),

**Comment by TGamingStudio** [comment]
![obrázok](https://user-images.githubusercontent.com/45291673/56867436-7b62a380-69e5-11e9-88ba-43b2175ea96f.png)
This is how my manager object looks. And in _events is my event sentOfferChanged.
I can also see my apiKey is null here.

**Comment by TGamingStudio** [comment]
The "sentOfferChanged" event was emmited after i sent from my main account offer to bot and bot accepted / declined it. In documentation is written it has to be emmited when bot's offer has been changed.
"receivedOfferChanged" does nothing
I am so confused

**Comment by DoctorMcKay** [comment]
Show your full code.

**Comment by TGamingStudio** [comment]
My full code is 500 lines or more... What exaclty do you need to see?

**Comment by TGamingStudio** [comment]
My code:
```const client = new SteamUser()
const community = new SteamCommunity()
const manager = new TradeOfferManager({
  steam: client,
  community: community,
  language: 'en'
  //also tried   pollInterval: 1000
})
client.on("webSession", (sessionid, cookies) => {
  manager.setCookies(cookies)
  //manager.apiKey = process.env.apiKey
  
  
  community.setCookies(cookies)
  community.startConfirmationChecker(10000, process.env.identitySecret)
})
```

some code with socket.io to create an offer and send it
Offer is sent and then i want to emmit this event when offer bot sent was accepted
```

manager.on("sentOfferChanged", function (offer, oldState) { //TODO test this
  console.log("id:" + offer.id)
})
```
I accept offer bot sent but the event isnt emmited.

**Comment by DoctorMcKay** [comment]
Add a callback to `manager.setCookies`. There might be an error in there. If I had to guess, I'd say your account is limited.

**Comment by TGamingStudio** [comment]
Oh yes... My bot's account is limited... Whole the time could be the error 🤦 Ill put some money to the steam and see what happens. Thank you for your help

**Comment by TGamingStudio** [comment]
Error i got was Access Denied

**Comment by DoctorMcKay** [comment]
Well, that's your problem.
