### ISSUE TITLE
Wrong data in polldata

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-tradeoffer-manager#301]
Im using atm, the latest release version.

I activated some debug logs on mw own to check processed trades, and sometimes it happens something like this..

![00](https://user-images.githubusercontent.com/30638036/59336151-619ac880-8cd4-11e9-9b2c-60878c710647.JPG)
![0](https://user-images.githubusercontent.com/30638036/59336157-652e4f80-8cd4-11e9-922a-80eab3da52f6.JPG)
![after](https://user-images.githubusercontent.com/30638036/59336164-665f7c80-8cd4-11e9-91cb-09e4a0132ce7.JPG)

something is wenting wrong, it hapending time to time..

**polldata** its being stored by **savePollData: true** option on constructor..

i think this is a bug that regards steam api probably, but im not sure if this is really supposed to happen in this module :c

**Comment by DoctorMcKay** [comment]
This doesn't have anything to do with poll data. Sometimes Steam is just complete garbage and gives junk data. Not really anything we can do about it.

**Comment by JustAzul** [comment]
What if before emits any sentOfferChanged it checks on module data if the offer was previously completed before?, im trying that atm, and its working, since we can get the oldOfferState i assume that is possible somehow right?

**Comment by DoctorMcKay** [comment]
Yes, it would be possible, but I'm concerned that there might be cases where trade offers go from a completed state to a different state in reality. For example, back in the day, it was possible for offers to go from Accepted to InvalidItems.

**Comment by JustAzul** [comment]
steam really sucks at some points :(
