### ISSUE TITLE
language setting is not working

### ISSUE THREAD

**Issue by ylhbot2** [DoctorMcKay/node-steam-tradeoffer-manager#302]
This is my code：
`const manager = new TradeOfferManager({
    steam: client,
    community,
    language: 'zh',
    pollInterval: 10000,
    cancelTime: 300000
});`
and I console.log the manager:
`...
steamID:...,
  _languageName: 'chinese',
  _events: [Object: null prototype] { newOffer: [Function] },
  _eventsCount: 1 }`
but it doesn't work,i still got the inventory description in English.
i see a  same issue but it had been closed, i think maybe this bug is not fixed?

**Comment by DoctorMcKay** [comment]
You should use szh (for Simplified Chinese) or tzh (for Traditional).

**Comment by ylhbot2** [comment]
> You should use `szh` (for Simplified Chinese) or `tzh` (for Traditional).

It worked，thanks for your reply.But i think the wiki doc should be modified,it says the language must be 2-character language code. You'd better list all the language code or list the special one at least.

**Comment by DoctorMcKay** [comment]
Thanks, I've updated the wiki.
