### ISSUE TITLE
tradeoffer.getExchangeDetails new_contextid not working when trade Subnautica items

### ISSUE THREAD

**Issue by coodrag** [DoctorMcKay/node-steam-tradeoffer-manager#305]
Trade a 'Subnautica' item and use tradeoffer.getExchangeDetails, contextid as same new_contextid, but contextid should be change after the exchange

**Comment by DoctorMcKay** [comment]
This is actually a bug in Subnautica's item server. The Steam API is returning the same value for `new_contextid` as it is for `contextid`, and the Steam API gets that data from the game's item server.

I've confirmed that it's not a Steam bug, as when you trade Spiral Knights items, the contextid also changes and the value of `new_contextid` is as expected in that case.
