### ISSUE TITLE
having some trouble with this

### ISSUE THREAD

**Issue by 2cab** [DoctorMcKay/node-steam-tradeoffer-manager#306]
`Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\serbe>cd C:\Users\serbe\Downloads\bot

C:\Users\serbe\Downloads\bot>node bot
Succesfully logged on.
C:\Users\serbe\Downloads\bot\bot.js:79
    var our_items = offer.itemsToGive;
                          ^

TypeError: Cannot read property 'itemsToGive' of undefined
    at process (C:\Users\serbe\Downloads\bot\bot.js:79:27)
    at TradeOfferManager.<anonymous> (C:\Users\serbe\Downloads\bot\bot.js:134:3)
    at TradeOfferManager.emit (events.js:311:20)
    at C:\Users\serbe\Downloads\bot\node_modules\steam-tradeoffer-manager\lib\polling.js:239:10
    at Array.forEach (<anonymous>)
    at C:\Users\serbe\Downloads\bot\node_modules\steam-tradeoffer-manager\lib\polling.js:223:12
    at C:\Users\serbe\Downloads\bot\node_modules\steam-tradeoffer-manager\lib\index.js:509:4
    at C:\Users\serbe\Downloads\bot\node_modules\steam-tradeoffer-manager\lib\assets.js:171:4
    at C:\Users\serbe\Downloads\bot\node_modules\async\dist\async.js:1140:9
    at C:\Users\serbe\Downloads\bot\node_modules\async\dist\async.js:473:16`

here is my code

`function process(offer) {
    client.setPersona(SteamUser.EPersonaState.Busy);
    var our_items = offer.itemsToGive;
    var their_items = offer.itemsToReceive;

    if(offer.isGlitched() || offer.state == 11)
        decline(offer);
    else if(offer.partner.getSteamID64() == config.owner.ID64) 
        accept(offer);
    else
        for (var i in our_items)
            var item = our_items[i];
            var name = item.market_hash_name
            if(isTF2()) {
                if(Prices[name]) 
                    ours += Math.ceil(Prices[name].sell * 9);
            else 
                ours += Math.pow(2, 50)
            }
                
        for(var i in their_items) 
            var item = their_items[i];
            var name = item.market_hash_name;
            if(isTF2()) {
                if(Prices[name])
                    theirs += Math.ceil(Prices[name].buy * 9);
            }

    print(`${log('trade')} Their value: ${Math.floor(theirs / 9 * 100) / 100} ref`); 
    print(`${log('trade')} They want: ${Math.floor(ours / 9 * 100) / 100} ref`); 

    if (ours <= theirs) {
        offer.getUserDetails((err, them) => {
            if (err) {
                throw err;
            }
            else if(offer.itemsToGive.length == 0 && offer.itemsToReceive.length > 0) {
                offer.accept((err) => {
                    if(err) print(`${log('trade')} ${err}`);
                    print(`${log('trade')}   Trying to accept incoming donation.`);
                    client.chatMessage(offer.partner.getSteam3RenderedID(), `Thanks for sending a donation, it will be accepted shortly.`)
                })
            }
            else if (them.escrowDays > 0) {
                escrow(offer);
            } else {
                accept(offer); 
            }
        });
    } else {
        decline(offer);
    }
}`

**Comment by DoctorMcKay** [comment]
You called `process()` somewhere with an undefined argument.
