### ISSUE TITLE
Steam Escrow

### ISSUE THREAD

**Issue by s992** [DoctorMcKay/node-steam-tradeoffer-manager#31]
I don't know when (or if) this is going to be implemented, but I thought it'd be worthwhile to bring it to your attention:

https://www.reddit.com/r/GlobalOffensive/comments/3tdcpe/steam_is_adding_an_escrow_and_multiple_day_delay/

I don't know what will be involved in supporting this, but I'd be happy to help in any way I can.

**Comment by DoctorMcKay** [comment]
Yeah, I'm aware of this potential (awful) change. There isn't really anything that can be done to accommodate it until it actually happens though, since we don't know any implementation details. `escrow_end_date` appeared in the trade offers API, which is likely to be a unix timestamp, but without knowing for certain I don't want to write any code for it.

**Comment by s992** [comment]
I figured that was the case. I'll be watching this news closely, so hopefully I can offer some assistance when the time comes (if you need/want it).

**Comment by scholtzm** [comment]
http://store.steampowered.com/mobile

It's happening, unfortunately.

[Some technical details have been already found.](https://www.reddit.com/r/Steam/comments/3tdpfd/valve_to_add_escrow_to_trading_which_holds_items/cx62f91)

**Comment by trzyrazyzero** [comment]
Someone make c# library for steam auth - https://github.com/geel9/SteamAuth

**Comment by DoctorMcKay** [comment]
I know. [I already have it implemented in node.](https://github.com/DoctorMcKay/node-steam-totp).

**Comment by trzyrazyzero** [comment]
This library contains accepting trades, so problem solved probably?

**Comment by DoctorMcKay** [comment]
Implemented about as much as it can be: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases/tag/v1.13.0

**Comment by GlebkaF** [comment]
Hello guys, so, is it possible to fetch, accept, and deny mobile confirmations in node like in C# library? I looking for some method, but i did't found it. I'm already got my secret for TOTP, and logining using 2factor auth, but now i need to confirm outgoing offers automaticly, to avoid escrow. thank you

**Comment by scholtzm** [comment]
@GlebkaF [All available packages linked at the top.](https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/)

**Comment by GlebkaF** [comment]
@scholtzm my thanks to you sir
