### ISSUE TITLE
Typescript support and contributions

### ISSUE THREAD

**Issue by Ascenio** [DoctorMcKay/node-steam-tradeoffer-manager#312]
I would like to ask if a migration to typescript would be viable and a interest of you guys, if that's the case maybe there's some devs which are willing to help. Maybe even refactor, linting, etc. My thought is that such things would help considering the current's project age (and old codebase), while giving a chance to beginners to make contributions.

**Comment by DoctorMcKay** [comment]
I'm not very interested in switching to TypeScript.
