### ISSUE TITLE
getExchangeDetails returns incorrect assetids after steam stacks items

### ISSUE THREAD

**Issue by ksewo** [DoctorMcKay/node-steam-tradeoffer-manager#316]
Steam stacks some RUST (APPID: 252490) items after trade. If steam does that, getExchangeDetails returns wrong assetid for received item if it has been stacked.

Is there a way I can prevent items stacking or get correct assetids of items after trade (if they stack)?

There is the same issue with getReceivedItems.

**Comment by DoctorMcKay** [comment]
Unfortunately not. The asset server automatically stacks the items, and the data returned in those methods comes straight from the asset server. If it's wrong, that's the asset server's fault.
