### ISSUE TITLE
Error: There was an error accepting this trade offer.  Please try again later. (28)

### ISSUE THREAD

**Issue by Nilzpils** [DoctorMcKay/node-steam-tradeoffer-manager#317]
from most offers I get the bot doesn't accept and just errors out "Error: There was an error accepting this trade offer.  Please try again later. (28)"

Anyone got a fix?

**Comment by DoctorMcKay** [comment]
https://steamerrors.com/28

Sounds like you're double-accepting offers.

**Comment by Nilzpils** [comment]
I just put in this log just before accepting the offer which only logs once in the console, so this might not be the case
![image](https://user-images.githubusercontent.com/43572624/106389783-8f6edc80-63e5-11eb-8aa5-d04320110659.png)

**Comment by DoctorMcKay** [comment]
Either way, that error is coming from Steam, meaning that the module is doing its job.
