### ISSUE TITLE
Typescript declaration

### ISSUE THREAD

**Issue by arthurfiorette** [DoctorMcKay/node-steam-tradeoffer-manager#318]
Hello, I'm using some of your node-steam packages in my typescript project. There are ways to generate the **.d.ts** files [automatically](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html) without having to recode everything in typescript. I'm asking here, but it would be a great help if you could add types to all of your node-steam projects. You could add it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) or even into your code.

**Comment by kjsmita6** [comment]
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/steam-tradeoffer-manager) has one as of April 2023.
