### ISSUE TITLE
Polling Overloading

### ISSUE THREAD

**Issue by JustAzul** [DoctorMcKay/node-steam-tradeoffer-manager#320]
<details>
<summary>Logs</summary>

![image](https://user-images.githubusercontent.com/30638036/147422715-20b3918a-44db-4d68-8901-c10baa0a3d12.png)

</details>

<details>
<summary>Active Requests Screenshot</summary>

![image](https://user-images.githubusercontent.com/30638036/147422730-b59d8608-4dba-442c-aac9-63cbe84563ea.png)

</details>

```
The event loop gets overload during poll updates, when it executes full updates, the overload is bigger.
```

First polling: 35k requests
Second and so on: 10~15k requests

## Update 2
After some debugging, I've got some results.
<details>
<summary>PM2 Active Requests</summary>

![image](https://user-images.githubusercontent.com/30638036/147997849-ec3acf2a-1b48-4746-8a91-bb1d30a2c009.png)

</details>

<details>
<summary>Debug Screenshots</summary>

<details>
<summary>Code</summary>

![image](https://user-images.githubusercontent.com/30638036/147997860-8c197db2-bfbe-4d61-abff-10e03c5ad289.png)

</details>

<details>
<summary>Logs</summary>

![image](https://user-images.githubusercontent.com/30638036/147997878-47a2d8ab-c50b-4d24-b6ba-409d3bedb155.png)

</details>

</details>

## Update 3
After several tests, I've found the source of this issue.

the problem is on I/O bound operations, mainly used when our **[assetCacheMaxItems](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#assetcachemaxitems)** does not have a big number, making the node process to execute a HUGE number of I/O operations all at once, freezing the entire event loop.

Possible solutions:
- use a [worker thread](https://nodejs.org/api/worker_threads.html) to handle I/O bound operations
- increase  **[assetCacheMaxItems](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#assetcachemaxitems)** (would increase memory usage)

**Comment by JustAzul** [comment]
#Updating:
Logs:
![image](https://user-images.githubusercontent.com/30638036/147422715-20b3918a-44db-4d68-8901-c10baa0a3d12.png)
PM2 Monit: 35k requests
![image](https://user-images.githubusercontent.com/30638036/147422730-b59d8608-4dba-442c-aac9-63cbe84563ea.png)

the issue seems to happen when it performs a full polling update

**Comment by JustAzul** [comment]
after some debugging, i've got some interesthing results.
![image](https://user-images.githubusercontent.com/30638036/147997849-ec3acf2a-1b48-4746-8a91-bb1d30a2c009.png)

![image](https://user-images.githubusercontent.com/30638036/147997860-8c197db2-bfbe-4d61-abff-10e03c5ad289.png)
![image](https://user-images.githubusercontent.com/30638036/147997878-47a2d8ab-c50b-4d24-b6ba-409d3bedb155.png)
the function `finish` is apparently blocking the event loop, tested on `v2.10.4`.

**Comment by JustAzul** [comment]
after several tests, I've found the source of this issue.

the problem is on I/O bound operations, mainly used when our **[assetCacheMaxItems](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#assetcachemaxitems)** does not have a big number, making the node process to execute a HUGE number of I/O operations all at once, freezing the entire event loop.

Possible solutions:

- use a [worker thread](https://nodejs.org/api/worker_threads.html) to handle I/O bound operations
- increase  **[assetCacheMaxItems](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#assetcachemaxitems)** (would increase memory usage)

**Comment by DoctorMcKay** [comment]
There's no synchronous I/O in tradeoffermanager, and Helpers.createOfferFromData doesn't do any I/O at all. It sounds like you have an issue somewhere else that's blocking your event loop.

**Comment by JustAzul** [comment]
> There's no synchronous I/O in tradeoffermanager, and Helpers.createOfferFromData doesn't do any I/O at all. It sounds like you have an issue somewhere else that's blocking your event loop.
> 
> If you're operating at a massive scale, you probably want to disable asset description retrieval by omitting the `language` option in the constructor and handle mapping item ids to descriptions yourself elsewhere. That eliminates the need for either memory capacity or disk I/O to cache the descriptions.

So, why when i use this:
```javascript
assetCacheMaxItems: Number.MAX_SAFE_INTEGER
```
The event loop stop freezing?

to set a big number on **[assetCacheMaxItems](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#assetcachemaxitems)**, makes the read, save, JSON.parse/stringify operations to be completely ignored, right?

Please correct me if i'm wrong, i'm here to learn(and help fix issues, if any) :)

**Comment by DoctorMcKay** [comment]
It does seem like if you try to read 30,000 files there's some event loop blockage, but I haven't been able to reproduce more than a few hundred ms of delay.

<details>
<summary>Test code</summary>

It's not the cleanest, I know

```js
const FS = require('fs');

let filenames = FS.readdirSync(__dirname + '/.local/share/node-steam-tradeoffer-manager');
console.log(filenames.length);

let filesToOpen = [];
for (let i = 0; i < 30000; i++) {
        filesToOpen.push(filenames[Math.floor(Math.random() * filenames.length)]);
}

let opened = 0;
let last = Date.now();
setInterval(() => {
        let now = Date.now();
        let diff = now - last;
        last = now;
        console.log(`${diff} - opened ${opened}`);
}, 100);

for (let i = 0; i < filesToOpen.length; i++) {
        FS.readFile(__dirname + '/.local/share/node-steam-tradeoffer-manager/' + filesToOpen[i], (err, file) => {
                if (err) throw err;
                JSON.parse(file.toString('utf8'));
                opened++;
        });
}
```
</details>

I ran this test code to see how much opening 30k random files from my disk asset cache would slow down the event loop.

<details>
<summary>Output</summary>

```
320322 // directory contains 320k files
117 - opened 0
235 - opened 0
223 - opened 0
99 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
100 - opened 0
128 - opened 716
487 - opened 30000
101 - opened 30000
100 - opened 30000
```
</details>

So the worst blockage I experienced was 387 milliseconds.

Some of this could possibly be mitigated by enqueueing disk I/O to ensure we don't try to read too many files from disk at once.

**Comment by JustAzul** [comment]
I will try to isolate everything and run tests to see whats wrong, in the mean time, #324 would be a nice first step

**Comment by DoctorMcKay** [comment]
Update [file-manager to v2.0.1](https://github.com/DoctorMcKay/node-file-manager/compare/v2.0.0...v2.0.1) and you should see some marked improvement in I/O performance due to limiting concurrent I/O operations.
