### ISSUE TITLE
steam remove CancelTradeOffer and DeclineTradeOffer api

### ISSUE THREAD

**Issue by MaplerStory** [DoctorMcKay/node-steam-tradeoffer-manager#325]
steam update the api list
https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1

those apis are removed from the apilist
https://api.steampowered.com/IEconService/CancelTradeOffer/v1/
https://api.steampowered.com/IEconService/DeclineTradeOffer/v1/

those methods [send](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#cancelcallback) and [decline](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#declinecallback) for TradeOffer may not work?

**Comment by lovesmurf** [comment]
wtf. What can it mean

**Comment by LoginPassword** [comment]
Lol i was wondering why my code is not working
Steam return error - 'HTTP error 404'

**Comment by lovesmurf** [comment]
> Lol i was wondering why my code is not working Steam return error - 'HTTP error 404'

Thanks for the fact that it is still possible to implement this without an API :D

**Comment by LoginPassword** [comment]
I think that this is done against scammers who steal the api key

**Comment by lovesmurf** [comment]
> I think that this is done against scammers who steal the api key

It remains for complete happiness only to add a captcha to trades

**Comment by arik123** [comment]
So, I looked a bit into it, and it seems that we should be able to `POST` to 
`https://steamcommunity.com/tradeoffer/${tradeOfferID}/${strAction}` where action is `cancel` or `decline`
with body of `{ sessionid: g_sessionID }`

**Comment by lovesmurf** [comment]
> 

Yes. This is true

**Comment by DoctorMcKay** [comment]
Published as version 2.10.5.
