### ISSUE TITLE
offer with large amount of items will cause a memory crash

### ISSUE THREAD

**Issue by MaplerStory** [DoctorMcKay/node-steam-tradeoffer-manager#329]
an offer with large amount items, such as 1k+ or 10k+ items will cause a large memory usage, an may cause a memory crash;
sometimes the large offer is useless for business now, but the offer-manager will load it and cause a memory crash,
so maybe could add some options to the manager to bypass or ignore to load the large offer?

momery usage was caused by those code ?
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/c32dc5762ac4dd519837160f9c1f7b48598883c3/lib/index.js#L519

**Comment by DoctorMcKay** [comment]
Memory usage is always going to happen if the module has to load lots of descriptions for a single offer. If memory is limited, I suggest that you disable description loading by not passing a language to the constructor.

**Comment by MaplerStory** [comment]
ok, thks,
it's a way to limit the memory usage by not to set the language
