### ISSUE TITLE
Brazilian portuguese language

### ISSUE THREAD

**Issue by matheustav** [DoctorMcKay/node-steam-tradeoffer-manager#331]
Hi, first of all, thanks for all of your awesome Steam related packages!

I'm trying to fetch inventory data using Brazilian portuguese. The docs states that language "Must be a 2-character language code like en or es.", but I already tried "br" and it doesn't work. "pt" uses Portugal portuguese.

I already tried "pt-BR", "brazilian" and other variants, but nothing seems to work.

Thanks!

**Comment by Gobot1234** [comment]
`pt-BR` should work at least according to my language enum (https://github.com/Gobot1234/steam.py/blob/main/steam/enums.py#L669) this might be a steam issue

**Comment by matheustav** [comment]
Unfortunately it doesn't work :(

I think the issue is related to the package "languages", which this project depends on, since its data doesn't mention brazilian portuguese:
https://github.com/joker-x/languages.js/blob/master/languages.json

I'm assuming this based on these lines: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/dc44de43232ed7572bf54c60d5f8d0c7da57d44c/lib/index.js#L79
