### ISSUE TITLE
Executing the example keeps prompting timeout

### ISSUE THREAD

**Issue by chenchen923** [DoctorMcKay/node-steam-tradeoffer-manager#334]
Hello author, when I execute the files in the examples folder, I will first be prompted that the login is successful, and then a timeout prompt will appear after a few minutes, as shown in the following figure:
<img width="435" alt="Snipaste_2023-05-26_11-08-39" src="https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/30c261f9-2d5d-4a83-ac14-ab28607ecb28">
Does the domain in the configuration item here need to be changed?
<img width="562" alt="Snipaste_2023-05-26_11-10-33" src="https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/cb3bc530-4796-449c-a397-4f8928a53a06">

**Comment by DoctorMcKay** [comment]
It seems like that error is coming from when it attempts to retrieve your WebAPI key from https://steamcommunity.com/dev/apikey. Can you load that page in your browser?

That seems to be a [Facebook IP](https://www.whois.com/whois/69.171.242.11). I don't know why it would attempt to connect to that. Do you have some weird DNS or proxy setup on your network?

**Comment by chenchen923** [comment]
Hello author, first of all thank you for answering my question. I am from China, I use some proxy software to access github, steam and google, but if I don't use this software, I will not be able to access the above websites.
But through the browser, I can access the steam web page, and also access the interface you gave me. The return value is as follows:
![image](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/dd36f945-4c19-410d-8e5e-694c7db33d5b)

**Comment by chenchen923** [comment]
Hello author, through the example you provided, I guess that the login communication with steam is another library you made: https://github.com/DoctorMcKay/node-steamcommunity
Then I cloned the library, and when running the deom in the examples folder, a timeout also occurred, as shown in the figure below:
![image](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/0a733a05-ff10-4ff5-b91f-334f886d2f7a)

Please help me if possible, thanks a lot~

**Comment by chenchen923** [comment]
This problem is still caused by the VPN I use, and it can be solved by changing the proxy method of the VPN, thank you author~
