### ISSUE TITLE
Executing the example login error

### ISSUE THREAD

**Issue by chenchen923** [DoctorMcKay/node-steam-tradeoffer-manager#335]
Dear author, when I execute the storehouse-steamcommunity.js file in the examples folder, the following error will be thrown directly
<img width="772" alt="Snipaste_2023-05-29_19-15-06" src="https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/f68130d9-8ed8-4981-a5f0-4ef8b42a9d92">
I just fill in my account and password in the login configuration item, as shown below:
![image](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/13377370/24b1eef3-87f7-46f1-8b70-0f6b21bf1fd3)
I hope you can answer my question when you have time, thank you~

**Comment by DoctorMcKay** [comment]
Sounds like you might need to update your OS root certificates.
