### ISSUE TITLE
Trade error after Steam Update today (2024/Feb/07): you cannot trade with [person] (34)

### ISSUE THREAD

**Issue by nhatkun** [DoctorMcKay/node-steam-tradeoffer-manager#341]
Hi, DoctorMcKay
After steam down and maybe have some update today, my bot get error when make offer: you cannot trade with [person] (34)

`let offer = manager.createOffer(tradelink);`
`offer.getUserDetails(function(err, me, them) {`
`	if (err) {`
`		console.log("ERROR: " + err);`
`		return;`
`	}`
`}`

**Comment by DoctorMcKay** [comment]
Probably a transient Steam issue. Try restarting your bot and waiting a bit.

**Comment by nhatkun** [comment]
Thanks, it's works now ^_^

**Comment by nhatkun** [comment]
Well, for some reason, idk why but seem it's get same error again. I feel quite strange because this has been going on for almost 30 hours.
Any other solution?
Thanks.

**Comment by nhatkun** [comment]
nvm, i just found out why, my bot change name after login.
https://steamcommunity.com/discussions/forum/1/4202490424033360096/
