### ISSUE TITLE
sentOfferChanged stop working

### ISSUE THREAD

**Issue by logan12344** [DoctorMcKay/node-steam-tradeoffer-manager#342]

**Comment by logan12344** [comment]
![code2](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/22130703/bcd06d31-7d8e-47ea-a48e-cbc31f81c5dd)
![code](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/22130703/e928a935-4bd6-4eef-bd39-2c17f2eb75eb)

**Comment by DoctorMcKay** [comment]
Still working fine here.
