### ISSUE TITLE
when I send the refund offer in steam I got the error.

### ISSUE THREAD

**Issue by petro0310** [DoctorMcKay/node-steam-tradeoffer-manager#343]
Error :HTTP error 404.
I am requesting to @DoctorMcKay.
Thanks.

**Comment by DoctorMcKay** [comment]
Details please

**Comment by petro0310** [comment]
![image](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/146043120/2a44f680-4631-46dd-b0c6-afc3e9140d66)
at this time I got this issue.

**Comment by DoctorMcKay** [comment]
Please try reading your screenshot.

**Comment by petro0310** [comment]
so I have to check the client steam account?

**Comment by petro0310** [comment]
Currently I have no permission of client steam account.
