### ISSUE TITLE
Error: Logged in elsewhere

### ISSUE THREAD

**Issue by farmer1234** [DoctorMcKay/node-steam-tradeoffer-manager#344]
I'm using my bot account to play games. Am i allowed to use the bot and play game simultaneously? If so, how can i do it?

**Comment by beastxbolt** [comment]
Yes you can use the bot and play games at the same time. Just run your bot and use steam normally like you would.

**Comment by farmer1234** [comment]
> Yes you can use the bot and play games at the same time. Just run your bot and use steam normally like you would.

But my code is designed a bit different. For example, my bot won't run continuously, instead it will be invoked upon meeting certain conditions. For this reason it will make login requests accordingly. I have noticed that when I'm in game certain functions of the bot are not working. Like accepting trade.

**Comment by beastxbolt** [comment]
You shouldn't get logged out from steam app even if you make login request through your bot. And I'm not sure why accepting trades isn't working for you. Are you using newOffer event to accept incoming trades? Atleast that's how I do it and it works just fine.
I have played CS2 while running the bot and received multiple trade offers and all of them were being accepted without any issue.

**Comment by farmer1234** [comment]
>  ... I have played CS2 while running the bot and received multiple trade offers and all of them were being accepted without any issue.

Does your bot fresh login every time you receive a trade offer? Mine does. I have removed 'client.setpersona' property, will have to see if it works now.

**Comment by farmer1234** [comment]
Alright after removing these lines my code works fine now.

*** client.setPersona(SteamUser.EPersonaState.Online); ***
*** client.gamesPlayed(440); ***

**Comment by DoctorMcKay** [comment]
> Alright after removing these lines my code works fine now.
> 
> _**client.setPersona(SteamUser.EPersonaState.Online);**_ _**client.gamesPlayed(440);**_

Yep, that would be expected. Steam only allows you to have one logon session that's in-game at a time.
