### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by metzz1** [DoctorMcKay/node-steam-tradeoffer-manager#348]
Hello guys,

Due to Steam last update, it seems like some functionalities in CS2 are not working properly such as:
- cancelTime
- pendingCancelTime

The trade offers are not being canceled automatically like it used to (following parameters above).

Event `sentOfferChanged` is not getting fired at all. 

Does anybody know what exactly changed due to this new update, and what would be needed to fix?

Best regards,

**Comment by markberbon22** [comment]
It only affects cs2 base on my test.

**Comment by tktq40** [comment]
+ 1 same problem with cs2, any new endpoints to help this situation ?

**Comment by DoctorMcKay** [comment]
I suggest you contact Valve about their public APIs not returning data they're expected to return.

**Comment by metzz1** [comment]
> I suggest you contact Valve about their public APIs not returning data they're expected to return.


Just checked source code and it seems like this endpoint: `https://api.steampowered.com/IEconService/GetTradeOffers/v1` is not returning any data at all.

**Comment by MaplerStory** [comment]
you may try to use the latest version lib with accessToken mode, 
by pass the 'useAccessToken' option to the constructor.

**Comment by metzz1** [comment]
> you may try to use the latest version lib with accessToken mode, by pass the 'useAccessToken' option to the constructor.

That works, thanks for the insight.

**Comment by logan12344** [comment]
> > you may try to use the latest version lib with accessToken mode, by pass the 'useAccessToken' option to the constructor.
> 
> That works, thanks for the insight.

Can you explain how you fixed it?:)

**Comment by Rodrigo-JM** [comment]
> you may try to use the latest version lib with accessToken mode, by pass the 'useAccessToken' option to the constructor.

can you show us an example of this? thanks
