### ISSUE TITLE
'sentOfferChanged' doesn't call on csgo items

### ISSUE THREAD

**Issue by nhatkun** [DoctorMcKay/node-steam-tradeoffer-manager#353]
'sentOfferChanged' doesn't call on csgo offer.
I tested that when decline/accept offer of csgo items, the event is not called.
I tested other game, all good.
So I try to found a solution to replace it by checking offer status continuously (manager.getOffer), but error show up "Access is denied".

ps: sorry for my bad english.

**Comment by DoctorMcKay** [comment]
Duplicate of #348
