### ISSUE TITLE
getWebApiKey no longer functional -> GetTradeOffers & other api-key based stuff is broken

### ISSUE THREAD

**Issue by kjljxybr** [DoctorMcKay/node-steam-tradeoffer-manager#354]
Since getWebApiKey gives zeros, polling stopped working. How to reproduce:
You're getting cookies somehow -> you're using manager.setCookies() -> manager sets cookies for steamcommunity -> manager tries to get api key from steam -> manager receives zeros -> manager polling is broken 

![CleanShot 2024-05-02 at 16 27 47@2x](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/39905249/c1984cf4-5968-49cc-a6fd-b092b5959223)
![CleanShot 2024-05-02 at 16 28 03@2x](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/39905249/7a4f007a-4f9d-479b-aeeb-971944335c76)

**Comment by kjljxybr** [comment]
https://github.com/DoctorMcKay/node-steamcommunity/issues/342 is reliable to this issue

**Comment by kjljxybr** [comment]
![CleanShot 2024-05-02 at 16 49 40@2x](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/39905249/a87323ca-31e3-4cfb-afb6-2439d1ed49f5)

**Comment by kjljxybr** [comment]
workaround #2: 
![CleanShot 2024-05-06 at 19 50 20@2x](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/39905249/06fe5f03-1fc1-4966-97c5-397a7d0eebd9)

**Comment by Jeramy499k** [comment]
> workaround №2: ![CleanShot 2024-05-06 at 19 50 20@2x](https://private-user-images.githubusercontent.com/39905249/328254029-06fe5f03-1fc1-4966-97c5-397a7d0eebd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNTc4ODUsIm5iZiI6MTcxNTA1NzU4NSwicGF0aCI6Ii8zOTkwNTI0OS8zMjgyNTQwMjktMDZmZTVmMDMtMWZjMS00OTY2LTk3YzUtMzk3YTdkMGVlYmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA0NTMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDhlMWJkNTZjNGIzYTExNTE0Y2IxMzRhYjBmMzVlYjkzODI0ZDMzYjczNWQ3Y2NjOTRmNTg0NTc3YzJhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.anftNacygN-ZRgx5_f5I2B5rJUMf5Q-B1B6hQeNKAxc)

THanks it's work after get 429/403 for few days

**Comment by DoctorMcKay** [comment]
I still haven't seen this behavior on any of my accounts.

<img width="326" alt="image" src="https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/assets/1538723/fb6a0a4e-5e5c-4df5-92b6-22a8c9ffa53c">

**Comment by ikolka** [comment]
Neither option works for me. If I don't use 'UseAccessToken: true' when creating the manager, I get a 429 error in trades. If I use 'UseAccessToken', there are no errors, but trades aren't accepted, even though I receive information about them. Also, when trying to create an API key, I somehow received a 429 error from Steam
