### ISSUE TITLE
How to get sent offer id?

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steam-tradeoffer-manager#37]
Is there actually a way to get a ID of a sent offer?!
That might be important if you want to track sent offers via database.

**Comment by trzyrazyzero** [comment]
yes, https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#sendmessage-token-callback

**Comment by jsieler** [comment]
Oh, sorry, i'm really blind. Sorry again.
