### ISSUE TITLE
Verify if an offer will go to escrow after you accept it.

### ISSUE THREAD

**Issue by Merkelon** [DoctorMcKay/node-steam-tradeoffer-manager#38]
Hello there,
I'm trying to verify that incoming offers wont go to Escrow if accepted. i want to verify this just for received offers.

first, i used
```javascript
offers.getEscrowDuration(SteamID[,Token],function(err,theirEscrowDays,yourEscrowDays){
...
});
```
 to extract *theirEscrowDays* & *yourEscrowDays* vars, but it doesnt work if the sender is not on my friend list, i've noticed that this method(*getEscrowDuration*) creates a new trade offer.

second, i tried to get *escrowEnds* property of the *offer* object
```javascript
offers.on('newOffer', function (offer) {
...
    var escrow = offer.escrowEnds;
...
});
```
but it returns *null*.
the *offers* var here is the instanciation of 
```javascript
var client = new SteamUser();
var offers = new TradeOfferManager({
    steam:        client,
    domain:       config.domain, 
    language:     "en", 
    pollInterval: 10000, 
});
```
Thx for helping.

**Comment by jsieler** [comment]
I'm not sure, but i think that escrowEnds is null just only because there is currently no escrow. You will see that this might change on 9th.

**Comment by Merkelon** [comment]
@jsieler yeah, i think so. but i think that *escrowEnds* will be used **AFTER** items were hold, not before. something like this : 
```javascript
// items are on Hold for x Days
offer.escrowEnds -> x Days

// items aren't on Hold 
offer.escrowEnds -> null
```

**Comment by DoctorMcKay** [comment]
Nobody knows for sure yet, but I suspect @Merkelon is correct, since it's a date and not a number of seconds.

**Comment by jsieler** [comment]
According to Steam Forums, the items will land in escrow if you don't "verify" the trade. The value of "escrowEnds" will be almost the same to trade expiration date, also unix timestamp. Think calculation will be like: now() + 3 days in seconds = escrowEnds

**Comment by Merkelon** [comment]
Thank you @DoctorMcKay.
