### ISSUE TITLE
Add support for node-steam v1.x

### ISSUE THREAD

**Issue by scholtzm** [DoctorMcKay/node-steam-tradeoffer-manager#4]
`tradeOffers` event has been moved to separate `SteamUser` [handler](https://github.com/seishun/node-steam/tree/master/lib/handlers/user#tradeoffers).

This should be a fairly simple update.

**Comment by DoctorMcKay** [comment]
Unless I'm mistaken, all you need to do is pass the SteamUser handler as "steam" instead of the SteamClient?

**Comment by scholtzm** [comment]
[This](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/index.js#L57) will not work.

Personally, I would use `SteamClient`'s `message` event.

**Comment by DoctorMcKay** [comment]
I'm putting the finishing touches on my own `SteamUser` handler. Once that's done, I'll add support for it and the existing `SteamUser`.

**Comment by DoctorMcKay** [comment]
Done in 1.2.1. See [Steam Integration](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#steam-integration) on the wiki for the updated info.
