### ISSUE TITLE
Offer state "undefined". What to do?

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steam-tradeoffer-manager#40]
So, i've created small bot which should accept trades. Scenario is well known.

Some small part of code.
```javascript
manager.on('newOffer', function(offer) {
  /* SOME FUNCTIONS & CHECKS */
  // Try to accept the offer
  offer.accept(function(err, status) {
    console.log('ACCEPTED OFFER STATE: ' + status);

    if(status == 'accepted') {

      /* DO MYSQL STUFF & MORE */

    }
  });
});
```
I check if trade status was accepted and let the server do the stuff. But...
Sometimes trade status is "unknown" and trade offer is accepted anyway. No error, just unknown.
Will simple if(status != accepted) { return; } skip the acceptation until next check? Or its better just to .decline() the offer?

**Comment by DoctorMcKay** [comment]
If status is undefined, then there was an error. Your code doesn't seem to be checking for errors.

**Comment by jsieler** [comment]
Will this actually not accept the offer?

```javascript
manager.on('newOffer', function(offer) {
  /* SOME FUNCTIONS & CHECKS */
  // Try to accept the offer
  offer.accept(function(err, status) {
if(err != null) { return; }  <----- line added

    console.log('ACCEPTED OFFER STATE: ' + status);

    if(status == 'accepted') {

      /* DO MYSQL STUFF & MORE */

    }
  });
});
```

**Comment by DoctorMcKay** [comment]
Now you're just silently failing when there's an error. I'd assume that you would at least want to log it.

**Comment by jsieler** [comment]
Will it just fail or will it recheck this offer on next polling try?!

**Comment by DoctorMcKay** [comment]
It will continue trying to accept it, although that callback will never fire again. And some errors are just permanent failures.

**Comment by jsieler** [comment]
Is it possible to make sure to call a function inside callback only if offer was really "accepted"?

**Comment by DoctorMcKay** [comment]
Sure, that's what you're doing now. It's just not wise to throw away errors, is all.

**Comment by kinsi55** [comment]
Learn to properly code, and best practices and error handling before creating anything around Steams good, stable system ;)

**Comment by jsieler** [comment]
That was just an example, for people like you i will add big fat red notice about that.
