### ISSUE TITLE
Get Items Id after partner accepts a trade offer.

### ISSUE THREAD

**Issue by orik007** [DoctorMcKay/node-steam-tradeoffer-manager#42]
Situation:
Bot creates tradeoffer where bot is giving nothing and partner is giving some items. Partner accepts the tradeoffer, and items are transfered to bot.

Now, how can i determine new items id? Because the bot didnt accept nothing i cant call getreceiveditems (cos i dont have tradeId).

Should i turn something on?
Should i fetch bot inventory and do any magic recognising by hashname, instanceid, classid, etc?
What way do you use?

Thx

**Comment by DoctorMcKay** [comment]
You can call getReceivedItems for any accepted offer.

**Comment by orik007** [comment]
If my bot does not accept trade offer (it only creates trade offers, partners accept). I dont have TradeID.

Maybe im still missing some basic logic. But my bots only create trade offers, players accept it and over, bot does not make any aditional action. TYrade offer ends in accepted state.

**Comment by DoctorMcKay** [comment]
The tradeID is available for all accepted offers, regardless of who sent them. We pull it from the WebAPI.

**Comment by orik007** [comment]
Ah nice, thats what i was missing, thanks. What method do you use? This would save me :-)

**Comment by DoctorMcKay** [comment]
Just use offer.getReceivedItems.

**Comment by orik007** [comment]
ooo god, you are right, i watched canceled trade, and there is no tradeid o:-)
Thx
