### ISSUE TITLE
Steam Mobile Authenticator

### ISSUE THREAD

**Issue by ParrotCraft** [DoctorMcKay/node-steam-tradeoffer-manager#43]
Hello!
Is there will be support to Steam Mobile Authenticator?
My bot isn't working w/o it.

Thanks!

**Comment by Aareksio** [comment]
I think everything you need can be found here: https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/

**Comment by DoctorMcKay** [comment]
Thus module doesn't log in, so that's outside the scope. 

Confirmations are available in node-steamcommunity.
