### ISSUE TITLE
Trade escrowEnds ist null

### ISSUE THREAD

**Issue by jsieler** [DoctorMcKay/node-steam-tradeoffer-manager#44]
So i was just testing, with my own account. Items gone definitely to escrow, since i have notifications disabled, but escrowEnds in trade is still null. Is it bug?

Forgot to say, that even so, offer.state is 2.

**Comment by bulgakovk** [comment]
Same problem. Items in Escrow have state 2

**Comment by jsieler** [comment]
Was testing some times more. Yeah, state is always 2 and escrowEnds ist null, no matter what.

**Comment by DoctorMcKay** [comment]
Is this in the callback of `offer.accept`?

**Comment by bulgakovk** [comment]
In the callback of  
>offer.accept 

I've got this:
![default](https://cloud.githubusercontent.com/assets/8983736/11744252/d7617956-a01f-11e5-9ca6-27d3b75719a9.png)

**Comment by jsieler** [comment]
@DoctorMcKay,
yes, it's inside offer.accept.

@bulgakovk,
update library. it was already fixed.

**Comment by DoctorMcKay** [comment]
Fixed in latest version.

**Comment by sasd97** [comment]
I have the same issue.  escrowEnds: null, but when I am using getEscrowDuration method, it returned the 3 days of Escrow. offer.state is 2. lib version is 1.17.0

**Comment by Merkelon** [comment]
escrowEnds: Used when the trade is already on hold, and you want to know for how much time. (__After Hold__).
getEscrowDuration : Used to know if the trade will go to hold (if accepted) or not. (__Befor Hold__).
