### ISSUE TITLE
Offer accept InvalidState (11)

### ISSUE THREAD

**Issue by vigeron** [DoctorMcKay/node-steam-tradeoffer-manager#46]
When I decline offer, state no change
```javascript
manager.on('newOffer', function(offer) {
      offer.decline(function(err){
            console.log('Decline: '+err);
       });
   
   if(offer.state==2) {
             offer.accept(function(err,status){
                  if(err) {
                       console.log('Accept Error: ' + err);
                  };
             };
     };
 });
```
I got error:
Error: There was an error accepting this trade offer. Please try again later. (11)

**Comment by DoctorMcKay** [comment]
Nothing I can do about Steam errors.

**Comment by jsieler** [comment]
I just will reopen it by asking: is nodejs asynchronous?

The code he provided will try to decline and accept the trade at the same time, isn't it so?

**Comment by DoctorMcKay** [comment]
You're right.

**Comment by petrutaranu** [comment]
It also happens to me in this very moment. What have u done? did u get ur items back? the offer is avalabile untill 6 feb and i cant decline it. it shows me the error 2 and 11 and i wanna get my items back. what have u done?

**Comment by andrewda** [comment]
Error 11, in my experience, usually means that the trade has been accepted/declined without issue OR that it has already been accepted/declined/countered. With error 2, I always recheck the trade offer. Sometimes the trade is successfully accepted/declined, other times not.

**Comment by petrutaranu** [comment]
so what can i do? should i wait till 6 feb and the items will be on my inventory or what? anyways i cant accept the offer nor decline it. im stuck with it i hop ill get em back o9n 6 feb. what do u think?
