### ISSUE TITLE
EAI_AGAIN error

### ISSUE THREAD

**Issue by emdy** [DoctorMcKay/node-steam-tradeoffer-manager#47]
Sorry if i post here, but i have this error every time :( how to fix?
![sad](https://cloud.githubusercontent.com/assets/16139265/11761583/7958fa40-a0d9-11e5-9cc8-7c7d84385158.png)

**Comment by MaTyyyJ** [comment]
Check your firewall ;)

**Comment by emdy** [comment]
@MaTyyyJ FIREWALL IS NOT A PROBLEM! Any ideas?

**Comment by MaTyyyJ** [comment]
Its firewall probem, check anty-virus.

**Comment by emdy** [comment]
@MaTyyyJ i set firewall off and i dont have anty-virus!!!

**Comment by DoctorMcKay** [comment]
Check your DNS servers.

**Comment by emdy** [comment]
Iam lost for new escow. Just dont know what i need to combine to get it work :/
