### ISSUE TITLE
Language ru

### ISSUE THREAD

**Issue by kaikash** [DoctorMcKay/node-steam-tradeoffer-manager#48]
manager = new TradeOfferManager
    'language': 'ru' // if there was 'en' it would work
    'pollInterval': 5000
And it is not working, I can't setCookies, but when it is 'en' it works.

**Comment by DoctorMcKay** [comment]
I need to know what "not working" means.

**Comment by kaikash** [comment]
when language is en
Logged into Steam
Got API key: 0A1FC2A5597BA232FC7E50B1A5B6AA9C

when language is ru
Logged into Steam
// and nothing else

    manager = new TradeOfferManager
    'language': 'ru'
    'pollInterval': 5000
    steam.login logOnOptions, (err, sessionID, cookies, steamguard) ->
    if err
      console.log 'Steam login fail: ' + err.message
      process.exit(1)
    console.log 'Logged into Steam'
    manager.setCookies cookies, (err) ->
      if err
        console.log err
        process.exit(1)
      console.log 'Got API key: ' + manager.apiKey

**Comment by DoctorMcKay** [comment]
Fixed in 1.15.1, thanks for the report.

**Comment by kaikash** [comment]
Thank you!
