### ISSUE TITLE
Get escrow duration before making a offer.

### ISSUE THREAD

**Issue by Zexuz** [DoctorMcKay/node-steam-tradeoffer-manager#49]
Nice work McKay!

But how come we can't get the escrow duration before making a offer? Have you not yet fixed this or is it going to stay the way it is now? The 
    `var g_daysMyEscrow = x;
    var g_daysTheirEscrow = y;`
Still works even if we have not done a trade already.

**Comment by DoctorMcKay** [comment]
[Please read the documentation.](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#getescrowdurationsteamid-token-callback)
