### ISSUE TITLE
There was an error sending your trade offer.  Please try again later. You cannot trade with NickName. (50)

### ISSUE THREAD

**Issue by overheader** [DoctorMcKay/node-steam-tradeoffer-manager#50]
I can't send an offer to the user:
There was an error sending your trade offer.  Please try again later. You cannot trade with NickName. (50).
I authorize using node-steam with node-steam-totp.

**Comment by andrewda** [comment]
```
AlreadyLoggedInElsewhere = 50;
```

Make sure you're not logged in on another device somewhere.
