### ISSUE TITLE
About send trade offer

### ISSUE THREAD

**Issue by emdy** [DoctorMcKay/node-steam-tradeoffer-manager#51]
With manager you can check trade status but no example about how to trade offer :dash:

**Comment by jsieler** [comment]
It's all described here:
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#methods

**Comment by DoctorMcKay** [comment]
Please use the Steam group for future questions.

**Comment by emdy** [comment]
@DoctorMcKay ye use steam group where no one ansver and email too :?

**Comment by DoctorMcKay** [comment]
I generally respond to every thread on the group.
