### ISSUE TITLE
Accepting a trade offer doesn't change anything, leaves offer in pending state

### ISSUE THREAD

**Issue by charredgrass** [DoctorMcKay/node-steam-tradeoffer-manager#54]
Here's my issue - I accept an offer like this:

```js
offer.accept(function(err){ //where offer is a TradeOffer
    if (err) {
        console.log(err)
    } else {
        console.log("Offer accepted")
}
```

Console outputs "Offer Accepted" but offer is left in pending state on both ends (both account the offer is sent from and the account receiving the offer see pending). Confirmations are enabled for both and I am polling for confirmations.

**Comment by DoctorMcKay** [comment]
Make sure it's actually getting confirmed.

**Comment by charredgrass** [comment]
@DoctorMcKay I'm pretty sure it is getting confirmed. I have this code:

```js
steam.on('confKeyNeeded', function(tag, callback) {
  var time = Math.floor(Date.now() / 1000);
  confKey = totp.getConfirmationKey(identitySecret, time, tag)
  console.log("Setting Trade Confirmations key as: " + confKey)
  callback(null, time, confKey);
})

steam.on('newConfirmation', function(conf) {
  if (confKey != undefined) {
    conf.respond(Math.floor(Date.now() / 1000), confKey, true, function() {
      console.log("Trade confirmed.")
    });
  } else {
    console.log("Could not set trade confirmations key.")
  }
});
```

and it claims to be confirming each trade.

**Comment by charredgrass** [comment]
I just realized the problem - the confirmation fails and passes an Error object to the callback, which I didn't act on.

The error says "Could not act on confirmation", but what does this mean?
