### ISSUE TITLE
Error 400 after sending trade offer

### ISSUE THREAD

**Issue by frook1** [DoctorMcKay/node-steam-tradeoffer-manager#58]
Hello, 

I've got a problem with your library, when I send 800 items from bot A to bot B I'm getting a ERROR 400 on both bots, Steam is returning an anwser: Your browser sent an request that this server could not understand. Problem does not occur when the variable input has a empty object but when i turn that variable off the polling stops working [image removed due to steam api key]

**Comment by DoctorMcKay** [comment]
It seems to me that this is being caused by a URL that is too long for the Steam API servers to handle. I'll need to split up the GetAssetClassInfo calls into smaller chunks.

**Comment by DoctorMcKay** [comment]
Fixed in 1.16.1.

**Comment by Artyomcha** [comment]
Failed to send trade offer: 400 Client Error: Bad Request for url: https://steamcommunity.com/tradeoffer/new/send I have this error, what to do , the headers, payload , and cookies are correct, but this error is constant
