### ISSUE TITLE
Bot stops emiting 'newOffer' event after long idle.

### ISSUE THREAD

**Issue by GlebkaF** [DoctorMcKay/node-steam-tradeoffer-manager#59]
Hello, after few hours ( 3-4 I guess) of idle bot stops emiting this event, even if i restart the bot it still doesn't emit it. Only login via steam native client helps. 
So: 
1. Bot working properly
2. Few hours of idle
3. Bot stops emiting 'newOffer' event, even if i restart it
4. I logining to the bot account via steam client
5. Bot working properly
p.s. It worked fine for a couple month.

**Comment by frook1** [comment]
try listen for event 

manager.on('pollFailure', function(err) {
	logger.error("pollFailure");
	logger.error(err);
});

**Comment by GlebkaF** [comment]
@frook1 thank you, listening for it now.

**Comment by DoctorMcKay** [comment]
It's generally a good idea to refresh your web session if you're using the Steam client every hour or so.

Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).

**Comment by GlebkaF** [comment]
@DoctorMcKay Yes, but as i said it don't polling properly even after restart. Now i'm got "pollFailure:  [Error: HTTP error 400]".

**Comment by DoctorMcKay** [comment]
Error 400 can happen if you have very large offers, update if that's the case.

**Comment by frook1** [comment]
Update steam-tradeoffer-manager

W dniu poniedziałek, 21 grudnia 2015 Glebka <notifications@github.com>
napisał(a):

> @DoctorMcKay <https://github.com/DoctorMcKay> Yes, but as i said it don't
> polling properly even after restart. Now i'm got "pollFailure: [Error: HTTP
> error 400]".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/issues/59#issuecomment-166399217>
> .
>


-- 
Pozdrawiam
Mirosław Święcicki

**Comment by GlebkaF** [comment]
I'm just listening 'pollFailure' event and got this error, but there is no vert large offers, even just large offers :) All incoming offers contains about 1-2 items. I updated trade-offer-manager, i need time to got this issue again if this issue was not fixed.

**Comment by GlebkaF** [comment]
This error does not appear anymore.
