### ISSUE TITLE
It didn't works.

### ISSUE THREAD

**Issue by z1feR** [DoctorMcKay/node-steam-tradeoffer-manager#6]
**So i required the lib. and set it up with**
    var manager = new TradeOfferManager({
	    "steam": client, // Polling every 30 seconds is fine since we get notifications from Steam
	    "domain": "crackbook.de", // Our domain is example.com
	    "language": "en" // We want English item descriptions
    });
**When i pasted the following in**
// TRADEOFFER
// If a user sends a trade request...
manager.on('newOffer', function(offer) {
	console.log("New offer #" + offer.id + " from " + offer.partner.getSteam3RenderedID());
	offer.accept(function(err) {
		if(err) {
			console.log("Unable to accept offer: " + err.message);
		} else {
			console.log("Offer accepted");
		}
	});
});

manager.on('receivedOfferChanged', function(offer, oldState) {
	console.log("Offer #" + offer.id + " changed: " + TradeOfferManager.getStateName(oldState) + " -> " + TradeOfferManager.getStateName(offer.state));
	
	if(offer.state == TradeOfferManager.ETradeOfferState.Accepted) {
		offer.getReceivedItems(function(err, items) {
			if(err) {
				console.log("Couldn't get received items: " + err);
			} else {
				var names = items.map(function(item) {
					return item.name;
				});
				
				console.log("Received: " + names.join(', '));
			}
		});
	}
});

manager.on('pollData', function(pollData) {
	fs.writeFile('polldata.json', JSON.stringify(pollData));
});

**But it didnt works. I get no log on new tradeoffers**

**Comment by DoctorMcKay** [comment]
Please use the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/) for general usage questions.
