### ISSUE TITLE
getEscrowDuration daysTheirEscrow is undefined

### ISSUE THREAD

**Issue by Maarethyu** [DoctorMcKay/node-steam-tradeoffer-manager#60]
I'm coding a bot that will deny any trade offer with potential escrow but it seems like the function is broken or i've done something wrong.

```
offer.getEscrowDuration(function(err, daysTheirEscrow, daysMyEscrow) {
    if(err) {
        console.log(err);
    }
    else if(daysTheirEscrow != 0) {
        console.log("User have escrow, denying ...");
    }

    console.log(daysTheirEscrow); // print undefined in all cases
});
```

My bot is still accepting the offer and daysTheirEscrow is undefined, what is wrong ?

I tried to update all the dependencies but it keep happening.

**Comment by DoctorMcKay** [comment]
That `console.log` gets called even when an error is returned. Are you also getting an error printed?

Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).

**Comment by Maarethyu** [comment]
I'm sorry if i shouldn’t have asked this here.
There is no error, the trade offer goes trough a lot of verification like appid check and escrow check (all with errors handling) and the bot keep accepting the trade without error except when it tries to get the received items because they are in escrow.

**Comment by DoctorMcKay** [comment]
You... just described two different errors?

**Comment by GlebkaF** [comment]
@Maarethyu You should check offer state before use getRecivedItems(), accepted offers has status 3, escrowed has status 11. Check wiki about 'receivedOfferChanged' event.

**Comment by Maarethyu** [comment]
I'm sorry if i'm not clear, the getReceivedItems error is normal because the offer is in escrow, so no worry about this one.
The real question is, in which cases, the getEscrowDuration function can return a undefined daysTheirEscrow without returning an error ?

**Comment by DoctorMcKay** [comment]
[There are no cases.](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/index.js#L172)

**Comment by Maarethyu** [comment]
I think i'm just in the callback hell ._.
