### ISSUE TITLE
setCookies returns undefined

### ISSUE THREAD

**Issue by borianm** [DoctorMcKay/node-steam-tradeoffer-manager#61]
So I was going through some debugging of my earlier issue with this plugin and I wanted to see what do I get after I set cookies on the manager.

It should return NULL on success or an ERROR on failure but it actually returns UNDEFINED.
I logged my cookies, and they seem to be fine.

I re-searched and found that it runs pollFailure when it can't use getOffers normally. But I used steam-tradeoffers, I've set the API, cookies and sessionID in it and I ran the getOffers function without any problems.
(my earlier error was pollFailure with error socket hang up, ECONNRESET)

**Comment by scholtzm** [comment]
`setCookies` doesn't return anything, hence the [callback.](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/index.js#L69)
