### ISSUE TITLE
[BUG] Trade offer id not available after sending offer

### ISSUE THREAD

**Issue by kingjerod** [DoctorMcKay/node-steam-tradeoffer-manager#62]
According to the documentation, the trade offer id should be available in the callback after sending it. Right now the trade offer id is undefined because it is checking in the manager for pollData: https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L196

When I output the trade object, I can see the id is defined, and I see the trade in Steam. 

My code looks like this:
```javascript
  var self = this;
  var offer = self.tradeManager.createOffer(steamId);
  offer.addMyItems(items);
  offer.send(message, accessToken, function(err, status){
    if (err) {
      return callback(err.cause);
    }
    self.logger.info('Trade id: ' + offer.data('id')); //shows undefined 
    self.logger.info('Status: ' + status); //shows "sent"
    return callback(null, offer.data('id'));
  });
```

**Comment by kingjerod** [comment]
Looks like I can get the id just fine using offer.id, was trying to follow the docs and use the data method.

**Comment by scholtzm** [comment]
`id` is object property so you can access it directly.

`data(...)` is used for storing arbitrary values - e.g. attach "order number" to specific `TradeOffer` instance etc.

**Comment by kingjerod** [comment]
Yeah I realized that after looking at the offer dump. Might be useful to mention that the data method should be used for arbitrary properties. There is even code in the data method specifically for handling the id, which made me believe the data method should be used to retrieve it.

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOffer#datakey-value

>Gets or sets any arbitrary data you wish to associate with a trade offer.

**Comment by kingjerod** [comment]
The function also handles cancelTime, which isn't arbitrary data and affects how the trade is handled.

**Comment by DoctorMcKay** [comment]
>Some data keys are special, and are used to modify the properties or options of a specific trade offer.
