### ISSUE TITLE
Offer expire time?

### ISSUE THREAD

**Issue by arnaspecelis** [DoctorMcKay/node-steam-tradeoffer-manager#63]
Hi, I think offer expire time is not working correctly. I'm creating object using these params:

```javascript
var manager = new TradeOfferManager({
    "domain": "domain",
    "language": "en",
    "pollInterval": 5000,
    "cancelTime": 300000
});
```

and with this logic I think offer should be canceled automatic after 300 seconds, but even offer was active for day, it was still able to accept. So how to set offer expire time correctly?

**Comment by DoctorMcKay** [comment]
Is it an incoming offer that's not getting canceled? `cancelTime` only applies to outgoing offers.

**Comment by arnaspecelis** [comment]
no, its offer sent by me. so how to handle sent offers? becouse I tried many ways and it seems that this manager don't have it. And nothing found in the net..

**Comment by DoctorMcKay** [comment]
It works just fine for me. Can I see some more code?

**Comment by arnaspecelis** [comment]
Yeah, sure..

```javascript
var manager = new TradeOfferManager({
    "domain": "...",
    "language": "en",
    "pollInterval": 5000,
    "cancelTime": 300000
});

<.....>

manager.getOffer(value.tradeofferid, function (err, offer) {

var offer_details = {
                                    trade_id: value.id,
                                    trade_type: value.type,
                                    selected_type: 'deposit',
                                    created_time: time, // 1450730076
                                    created_date: value.created_at,
                                    time_now: Math.round(+new Date() / 1000), // 1450884220334
                                    offer_state: offer.state,
                                    callback_time: (key + 1) * 1000
                                };

if ((offer_details.time_now - offer_details.created_time) >= 7495) { // 7200 seconds due to timezone + 295s (almost 5 mins)
// maybe there should be some function to decline this offer?
}

});
```

**Comment by DoctorMcKay** [comment]
`created_time: time`

Where is `time` coming from?

**Comment by arnaspecelis** [comment]
I've been creating it before, it is timestamp. Everything is allright with checking and when I print message "console.log("offer timed out");" it prints me it. But how to cancel offer knowing its offer id?

**Comment by arnaspecelis** [comment]
is it even possible to add offer max acceptable time? for example to make it acceptable only for 5 mins after its being created

**Comment by DoctorMcKay** [comment]
>is it even possible to add offer max acceptable time? for example to make it acceptable only for 5 mins after its being created

Yes, that's the purpose of `cancelTime`.
