### ISSUE TITLE
getEscrowDuration on offers sent

### ISSUE THREAD

**Issue by hach3** [DoctorMcKay/node-steam-tradeoffer-manager#65]
Hi, i'm on a project where people will never send directly offers to the bot. The bot checks every 10 secondes if an offer has to be sent through the database. If it has, it sends the offer.

I wanted to know if i can directly check if a user has escrow enabled before sending the offer ? If not, is there any solution to handle this sort of behaviour ?

**Comment by scholtzm** [comment]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#getescrowdurationsteamid-token-callback

**Comment by hach3** [comment]
Ok thx :p Sorry for my newbiisme <3

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).
