### ISSUE TITLE
#932643199 is not accepted, cannot request received items

### ISSUE THREAD

**Issue by jeanggi90** [DoctorMcKay/node-steam-tradeoffer-manager#67]
I got this (#932643199 is not accepted, cannot request received items) error message from the callback of the "accept([autoRetry][, callback])" method. What went wrong? How can I fix it?

**Comment by scholtzm** [comment]
The trade offer is probably waiting for confirmation.

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L613
