### ISSUE TITLE
Error: Access Denied

### ISSUE THREAD

**Issue by ivailo-stoianov** [DoctorMcKay/node-steam-tradeoffer-manager#7]
Hello,
when I try to set the cookies I get an error saying Access Denied. Any idea what's causing this?

**Comment by DoctorMcKay** [comment]
As per the [documentation](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-callback), "You'll get an `Access Denied` error if your account is limited."
