### ISSUE TITLE
Latest NPM version not up to date

### ISSUE THREAD

**Issue by andrewda** [DoctorMcKay/node-steam-tradeoffer-manager#70]
The version of node-steam-tradeoffer-manager on NPM is not updated to the latest version (commit 6e885828acb54b2d98b0330be22aee11a12b6c8c)

**Comment by scholtzm** [comment]
npm versions are in-sync with tags https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/releases

**Comment by andrewda** [comment]
Yea, they're in-sync up to v1.16.4, but the latest update in commit 6e885828acb54b2d98b0330be22aee11a12b6c8c has some useful features not yet pushed to NPM and that don't yet have a GitHub tag (most likely v1.16.5).

**Comment by DoctorMcKay** [comment]
I pushed out v1.17.0.

**Comment by andrewda** [comment]
Great, thanks @DoctorMcKay.
