### ISSUE TITLE
Malformed response problem from getEscrowDuration

### ISSUE THREAD

**Issue by Merkelon** [DoctorMcKay/node-steam-tradeoffer-manager#72]
Hello there,
recently i have one problem with the method ___getEscrowDuration___ from the ___tradeOffer___ object, the problem is, once the method returns "Malformed response" it keeps returning the same error for all incoming trade offers.

````javascript
offersManager.on('newOffer', function(offer) {
...
    offer.getEscrowDuration(function(err,theirEscrow,MyEscrow){
    ...
        if(err){
            logger.error("error while trying to get escrow days: "+err);
            // so if this err equals "Malformed response" it keeps returning 
            // the same for all incoming trade offers
       }
    });
});
````
if i restart the bot the problem is gone for further offers until the next ___Malformed response___ again.

i tried to ___update___ the offer but it didnt solve the problem : 

````javascript
    offer.getEscrowDuration(function(err,theirEscrow,MyEscrow){
    ...
        if(err){
            offer.update(function(err){
                ....
            });
       }
    });
````

i dont get how a ___Malformed response___ from a trade offer affects other incoming offers.

thank you for helping.

**Comment by scholtzm** [comment]
Possibly dead cookies. Are you able to send/accept that offer (without checking escrow)?

**Comment by Merkelon** [comment]
i didnt try, since my process is to verify the escrowDuration before accepting any offer(cuz all my bot is doing is to accept/decline incoming offers).

**Comment by scholtzm** [comment]
> i wonder how can i solve the problem without restarting the bot ?

Basically, just re-log again, retrieve new set of cookies and retry to process the trade offer again.

**Comment by Merkelon** [comment]
ok, but how can i do that inside an event (i mean inside ___newOffer), should i just call for ___logOff___ method from ___steam-user___ object, and try to listen to ___disconnected___ event.

**Comment by scholtzm** [comment]
Nope, use [this](https://github.com/DoctorMcKay/node-steam-user#weblogon) instead.

**Comment by Merkelon** [comment]
ok, seems that it's going to solve the problem.

thx for your time.
