### ISSUE TITLE
Steam bot crashes after trade accepted and fails to send trade.

### ISSUE THREAD

**Issue by sword134** [DoctorMcKay/node-steam-tradeoffer-manager#73]
As the title says everytime i trade with my bot on my website i get this error: https://gyazo.com/89f39fa0c02e63bcea2b1be818770151

It does deposit the skins though but on end of the round it crashes when trying to return skins to winner.

**Comment by DoctorMcKay** [comment]
That's a problem in sell.js on line 604. Nothing to do with any external modules.
