### ISSUE TITLE
Offers limit to one person?

### ISSUE THREAD

**Issue by arnaspecelis** [DoctorMcKay/node-steam-tradeoffer-manager#74]
Hi there. Is there any way to make limit for offers to one user? For example I want to make that one steam user could handle only 1 active offer at the time. 

Or if there is any way to check if specified user didn't received any treadeoffer from the bot which is active? Because I have a problem where bot sends 2 offers at the same time and I can handle data only from the first one..

**Comment by DoctorMcKay** [comment]
You're requesting an option which will auto-cancel any offers sent to someone which would put the number of outgoing active offers to them over a limit?

This could be done, although it sounds like you have some kind of bug in your code that's causing this in the first place.

**Comment by arnaspecelis** [comment]
Yeah, i know there is a bug, but I don't know where. The bot sometimes sends 2 offers at the same time and I have no idea how to disable it. So i need maybe a check somehow if user didn't received such offer before.

**Comment by DoctorMcKay** [comment]
You could just call `getOffers` and check your active offers before/after sending.

**Comment by arnaspecelis** [comment]
I tried to make it for the last 3 seconds, but it returns me a lot of active offers. Even older then 1 day. 

```
function get_sent_offers(){
    var date_instance = new Date();
    var timestamp     = date_instance.getTime();
    var timer         = timestamp - 3000;
    var date          = new Date(timer * 1000);

    manager.getOffers('ActiveOnly', date, function(err, sent){
        console.log('getting active offers');
        console.log(err);
        console.log(sent);
    });
}
```

**Comment by LeCoffee** [comment]
When I ran the snippet 

```
    var date_instance = new Date();
    var timestamp     = date_instance.getTime();
    var timer         = timestamp - 3000;
    var date          = new Date(timer * 1000);
```

in my terminal I got a date of Sat Jan 27 48001 03:44:48 GMT+0000 (GMT) which is most definitely invalid. To use a date with this library I believe you use 

```
Date.now() - 3000
```
To get 3 seconds ago. I believe it will be fine like this however you may need to 
```
Math.floor((Date.now() - 3000) / 1000) 
```
to get it into a unix timestamp, I'll go check the documentation now.

**Comment by DoctorMcKay** [comment]
@LeCoffee is correct.
