### ISSUE TITLE
Getting items from a database problem

### ISSUE THREAD

**Issue by InterZittus** [DoctorMcKay/node-steam-tradeoffer-manager#75]
Hi there,

I am trying to add items into the offer using, offer.addMyItems(items);. I have set the variable items to row.items which is a field in my database.

mysqlConnection.query('SELECT * FROM `queue` WHERE `status`="New" AND `bot_id` ='+botid+' '+ 'LIMIT 1', function(err, rows, fields) { etc....

then: 
		var row = rows[i];
		var item = row.items;

The information for the items in the query is: {"assetid": "4754010408", "contextid": "2", "appid": "730", "amount": "1"} but when I run the bot, it does an error and says missing assetid, contextid etc...

I am wanting to know why the code cannot read the items from a variable because when I enter {"assetid": "4754010408", "contextid": "2", "appid": "730", "amount": "1"} into offer.addMyItems it works normal and sends an offer but not with a variable.

Thanks

Here is my code code which is buggy:

function sendOffers() {
	mysqlConnection.query('SELECT * FROM `queue` WHERE `status`="New" AND `bot_id` ='+botid+' '+ 'LIMIT 1', function(err, rows, fields) {
	  if (err) throw err;  
	  
		var row = rows[i];
		var id64 = row.id64;
		var typeofoffer = row.type;	
		var queueid = row.id;
		var token = row.token;
		var tradesecret = row.secret;
		var items = row.items;
		
		}
		
	  if (typeofoffer == 'send') {
		  console.log("New items to Send");
		  var message = "WITHDRAWL on ----- #"+tradesecret;
		  var offer = manager.createOffer(id64);
		  offer.addMyItems(items);
		  offer.send(message, token, function(err) {
		  if(err) {
			console.log(err);
			return;
		}
		  });
		  
		  mysqlConnection.query('UPDATE `queue` SET `status`="Trade Sent" WHERE `id`='+ [queueid]);
		  
	  }
	  if (typeofoffer == 'receive') {
		  console.log("New items to Receive");
		  var message = "DEPOSIT on ----- #"+tradesecret;
		  var offer = manager.createOffer(id64);
		  offer.addMyItems(items);
		  offer.send(message, token, function(err) {
		  if(err) {
			console.log(err);
			return;
		}
		  });
	  
		  mysqlConnection.query('UPDATE `queue` SET `status`="Trade Sent" WHERE `id`='+ [queueid]);
	  }
	});
}

**Comment by Merkelon** [comment]
hey,
your ___for___ loop is broken, i mean it does nothing.

**Comment by InterZittus** [comment]
that is nothing, ill remove it now, I was experimenting and forgot to remove that. Thanks

**Comment by DoctorMcKay** [comment]
Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).

The data is probably stored in your database as JSON, but you aren't parsing it and so you're passing a JSON string to `addMyItems` instead of an object.

**Comment by InterZittus** [comment]
thanks
