### ISSUE TITLE
Issue: Error: HTTP Error 400

### ISSUE THREAD

**Issue by InterZittus** [DoctorMcKay/node-steam-tradeoffer-manager#76]
Hi, I get this error when I try to send an offer. The offer does have a token and a message:

                  var token = row.token;
		  var message = "WITHDRAWL on -------- #"+tradesecret;
		  var offer = manager.createOffer(id64);
		  offer.addMyItems(items);
		  offer.send(message, token, function(err) {
		  if(err) {
			console.log(err);
			return;
		  }	
![capture](https://cloud.githubusercontent.com/assets/16028870/12214600/1be2098c-b700-11e5-804c-0e248d46ed8f.PNG)

**Comment by DoctorMcKay** [comment]
https://steamcommunity.com/groups/SteamRE/discussions/3/
