### ISSUE TITLE
[question]offer.itemsToGive.amount

### ISSUE THREAD

**Issue by WalkingCore** [DoctorMcKay/node-steam-tradeoffer-manager#77]
Let's say that the I offer 3 same keys. Would that just be a offer.itemsToGive[0] with amount == 3, or offer.itemsToGive[0], offer.itemsToGive[1] and offer.itemsToGive[2] and all of them are keys?

**Comment by Merkelon** [comment]
___offer.itemsToGive.length___ == 3.
so ___offer.itemsToGive[0]___, ___offer.itemsToGive[1]___ and ___offer.itemsToGive[2]___all of them are keys in your case.

**Comment by Aareksio** [comment]
You can stack (`amount = x`) items that can be stacked in your inventory (for example Holiday Sale 2014 Gems). Case keys doesn't stack.

**Comment by scholtzm** [comment]
Each key has unique ID so you the keys aren't the "same" really.

**Comment by WalkingCore** [comment]
Allright guys, thanks.
