### ISSUE TITLE
Question about tradeoffer values

### ISSUE THREAD

**Issue by emdy** [DoctorMcKay/node-steam-tradeoffer-manager#79]
My cookies val steamCountry, steamMachineAuth, steamRememberLogin, sessionid, steamRememberLoginError 1, steamLogin, steamLoginSecure.
     Cookies working 100%, but i have problem with makeing trade offer - what value i missing? cookie, offer or url?
URL=https://steamcommunity.com/tradeoffer/new/send
MAKE OFFER VAL
array(
     'serverid' => '1',
     'sessionid' =>''sessionid'',
     'partner' => '76561198215265409',
     'tradeoffermessage' => 'test',
     'json_tradeoffer' => '{"newversion":true,"version":2,
             "me":{"assets":[{"contextId":2,"appId":730,"amount":1,"assetid":"4964209355"}],"currency":[],"ready":false},
             "them":{"assets":[],"currency":[],"ready":false}}'
            )

Result=null

**Comment by emdy** [comment]
now i get, iam confused.
string(947) "HTTP/1.1 401 Unauthorized Server: Apache Vary: Accept-Encoding,Origin Content-Security-Policy: script-src 'self' 'unsafe-inline' 'unsafe-eval' https://steamcommunity-a.akamaihd.net/ https://api.steampowered.com/ http://www.google-analytics.com https://ssl.google-analytics.com ...

**Comment by DoctorMcKay** [comment]
What does this have to do with this library?

**Comment by emdy** [comment]
@DoctorMcKay i want just send trade offer post request! you can explain if i code is wrong? doesnt work /(-.-)\

**Comment by DoctorMcKay** [comment]
This has nothing to do with this library.

**Comment by emdy** [comment]
@DoctorMcKay i ask how to make a offer? i want just know how?

**Comment by scholtzm** [comment]
This is an issue tracker, not your personal help desk. You are spamming notifications to dozens of people.

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager#support
