### ISSUE TITLE
 There was an error sending your trade offer.  Please try again later. (8)

### ISSUE THREAD

**Issue by EnVires** [DoctorMcKay/node-steam-tradeoffer-manager#80]
i have error with send offer
 There was an error sending your trade offer.  Please try again later. (8)

code:

    manager.loadInventory(730, 2, true, function(err, myItems) {
        itemscopy = myItems;
        mysqlConnection.query('SELECT * FROM `queue` WHERE `status`=\'active\'', function(err, row, fields) {
            if (err) {
                return;
            }
            for (var i = 0; i < row.length; i++) {
                if (row[i].userid != "" && row[i].token != "" && row[i].items != "") {
                    var gameid = row[i].id;
                    var sendItems = (row[i].items).split('/');
                    var offer = manager.createOffer(row[i].userid);
                    for (var x = 0; x < itemscopy.length; x++) {
                        for (var j = 0; j < sendItems.length; j++) {
                            if (itemscopy[x].tradable && (itemscopy[x].market_name).indexOf(sendItems[j]) == 0) {
                               offer.addMyItem(itemscopy[x]);
							   
                            }
                        }
                    }
                       offer.send("Ваши вещи с сайта CSGOENERGY.ru", row[i].token, function(err, csgo) {
					    if (err) {
						   console.log(err);
                           return;
					    }		                           
                        steam.chatMessage(admin, "Отправил выйгришь в игре");
						mysqlConnection.query('UPDATE `queue` SET `status`=\'sent\' WHERE `id`=\''+gameid+'\'', function(err, row, fields) {});
					   });
                       

                    
                }
            }
        });
    });

**Comment by DoctorMcKay** [comment]
**Please direct future coding help questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

What is the format of `row[i].userid`?

**Comment by EnVires** [comment]
http://prntscr.com/9ph2m2

**Comment by DoctorMcKay** [comment]
That all looks fine to me. Make sure you're actually matching some items, I suppose.

**Comment by EnVires** [comment]
items have format http://prntscr.com/9ph3pn

**Comment by EnVires** [comment]
I do not know where there may be an error (

**Comment by EnVires** [comment]
[Error: There was an error sending your trade offer.  Please try again later. (8)] eresult: 8

**Comment by andrewda** [comment]
Add a `console.log(itemscopy[x])` here:

```
if (itemscopy[x].tradable && (itemscopy[x].market_name).indexOf(sendItems[j]) == 0) {
    console.log(itemscopy[x]);
    offer.addMyItem(itemscopy[x]);
}
```

Make sure there are actually items being added. Also check to make sure the `userid` row is a string (text/varchar) instead of a large int, as that *might* be causing an issue.

**Comment by EnVires** [comment]
LOOK http://prntscr.com/9ph3pn

**Comment by andrewda** [comment]
@EnVires Sorry, I had no idea about the context of where that came from. You could have been printing `myItems` for all I know. Apologies for my ignorance...

**Comment by EnVires** [comment]
ok,i fix this,update node modules stean

**Comment by andrewda** [comment]
Huh, ok. That's an odd fix, but glad it worked for you!
