### ISSUE TITLE
Users dont see trade offers

### ISSUE THREAD

**Issue by SevertainDOTcom** [DoctorMcKay/node-steam-tradeoffer-manager#82]
I use the last verisons of steambot modules. There are no errors, and all trades are sent well. But users dont see it (with mobile authentication too)
Whats a problem? Thx!
May be reason on Steam Guard?

*removed image as it contained an API key*

**Comment by andrewda** [comment]
I'm guessing the issue is with mobile confirmations. However, the trade should be successfully sending up until that point,

**Comment by SevertainDOTcom** [comment]
"the trade should be successfully sending up until that point,"
very bad =(

"issue is with mobile confirmations."
ok, thx.. try to fix
