### ISSUE TITLE
Manager set cookies responds with: [Error: Access Denied]

### ISSUE THREAD

**Issue by arnaspecelis** [DoctorMcKay/node-steam-tradeoffer-manager#83]
I'm trying to set cookies after client logged in and i keep getting this error: [Error: Access Denied] - what is wrong? it have always worked with this code.

console print: http://pastebin.com/uJ3XbrSv
and the code: http://pastebin.com/XDaB47ue

also this is how I set up my manager: http://pastebin.com/TUfb5qWE

Also: when I tried to login with my own steam account everything was good. But the bot accounts not.

**Comment by DoctorMcKay** [comment]
Please read the [documentation](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-callback).
