### ISSUE TITLE
partner can not agree with the proposal

### ISSUE THREAD

**Issue by nikadrenalin** [DoctorMcKay/node-steam-tradeoffer-manager#84]
I am sending a proposal to the partner to give me his thing, which he must agree, but I can not click submit button since the program dont ansver 

this code...

function getItem(sellerId, buyerId, partnerToken, itemId, itemQuantity, gameNumber) {
    var SteamID = TradeOfferManager.SteamID;
    var sid = new SteamID(buyerId);
    var trade = offers.createOffer(sid);

    loadPartnerInventory(trade, gameNumber, function (inventory) {
        findItems(inventory, itemId, function (item) {
            if (item) {
                logger.info('Item in partner inventory: '+inventory.length);
                
                trade.addTheirItems(item);
                sendOffer(trade, partnerToken, item, function(status) {
                    if (status == 'pending') {
                        logger.warn('Trade offer sent but awaiting email confirmation. You should probably turn off email confirmation here: http://steamcommunity.com/my/edit/settings/');
                    }else {
                        logger.info('Trade offer ' + item.length + ' item sent successfully');
                        getConfirm();
                    }
                });
            }else {
                logger.error('Not item for trade');
                return true;
            }   
        });
    });
};

function loadPartnerInventory (trade, gameNumber, callback) {
    trade.loadPartnerInventory(gameNumber, 2, function (err, inventory) {
        if (err) {
            logger.error('loadInventory '+err);
            return true;
        }

        callback(inventory);
    });
};

function sendOffer (trade, partnerToken, item, callback) {
    trade.send('New offer', partnerToken, function (err, status) {
        if (err) {
            logger.error('sendOffer: '+err);
        }

        callback(status);
    });
}

function findItems (inventory, itemId, callback) {
    var items = [];

    console.log(itemId);
    for(var i = 0; i < itemId.length; i++) {
        inventory.forEach(function (item, index, array) {
            console.log('item.classid: '+item.classid);
            if (item.classid === itemId) {
                logger.debug('itemId: '+item.classid);
                items.push(item);
            }
        });
    }
    callback(items);
}

**Comment by DoctorMcKay** [comment]
http://steamcommunity.com/groups/SteamRE/discussions/3/458606877309967543/
