### ISSUE TITLE
Question about createOffer.

### ISSUE THREAD

**Issue by jensej** [DoctorMcKay/node-steam-tradeoffer-manager#85]
To use this method -> createOffer, I need have two vars? :
Steam trade url second person, and his trade url?
It is not enough only TRADE url to create and send new offer?

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#createofferpartner
