### ISSUE TITLE
getEscrowDuration error

### ISSUE THREAD

**Issue by Gergo4961** [DoctorMcKay/node-steam-tradeoffer-manager#86]
Hello!

I'm making a bot and it's kinda done, I'm stress-testing it at the moment, I've sent it 4 offers in a row, confirmed all of them quick on my phone and it can only handle 2-3 out of the 4 it receives, then it doesn't re-check those trades.

I'm sending all the trades from the same account, I tested this twice, the first time 3 got processed, the second time only 2 out of 4. When I send a different trade the bot goes back to this offer and successfully accepts it, I thought I'd report the issue and ask for help.

Screenshot of the code:

http://i.imgur.com/e5yuQrJ.png

There's nothing after the ':' in the end.

Hopefully you guys can help me out or fix the issue!
~ Gergő

**Comment by DoctorMcKay** [comment]
That's on Steam's end. All you can do is retry.
