### ISSUE TITLE
accept error eresult:2 but offer is accepted

### ISSUE THREAD

**Issue by Freaders** [DoctorMcKay/node-steam-tradeoffer-manager#88]
hello, sometimes when there are more offers to accept in short time im getting this error but the offer accepts on steam. any solution? thanks

**Comment by Freaders** [comment]
and after the eresult 2 i usualy get [Error: Cannot load new trade data: HTTP error 500]

**Comment by DoctorMcKay** [comment]
That's just Steam. Nothing that can be done about it.
