### ISSUE TITLE
Users dont see trade offers (part II)

### ISSUE THREAD

**Issue by SevertainDOTcom** [DoctorMcKay/node-steam-tradeoffer-manager#89]
I remove all scripts, and download again (except for 2fa.js)
After reauthorization of my profile on server, i  should wait for 7 days. But again users dont see trade offers (bot takes items quite normal). 
How can I fix it , which modules are is responsible for the confirmation offers?

**Comment by DoctorMcKay** [comment]
**Please direct questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

You can use [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity) to confirm trades.
