### ISSUE TITLE
Error with loadInventory

### ISSUE THREAD

**Issue by Arakiri** [DoctorMcKay/node-steam-tradeoffer-manager#9]
Hello, I have an error that I have hard time to fix.

It happens when I try to use offers.loadInventory(); where 

```js
var offers = new TradeOfferManager({
    steam:        client,
    language:     "en", // English item descriptions
    pollInterval: 10000, // (Poll every 10 seconds (10,000 ms)
    cancelTime:   300000 // Expire any outgoing trade offers that have been up for 5+ minutes (300,000 ms)
});
```

I have this error : 

```
bash# : ./node bot.js 
/root/bot/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/users.js:248
	var endpoint = "/profiles/" + userID.getSteamID64();
	                                    ^
TypeError: Cannot read property 'getSteamID64' of undefined
```

Thank you for your help :)

**Comment by DoctorMcKay** [comment]
Few questions:

1. What version of `node-steam-tradeoffer-manager` do you have?
2. Can I get the full stack trace?
3. Can I see the code where you're calling `loadInventory`?

**Comment by Arakiri** [comment]
1. I just downloaded it via npm few hours ago so I guess I have the latest version.
2. ./node bot.js 
/root/bot/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/users.js:248
	var endpoint = "/profiles/" + userID.getSteamID64();
	                                    ^
TypeError: Cannot read property 'getSteamID64' of undefined
    at SteamCommunity.getUserInventory (/root/bot/node_modules/steam-tradeoffer-manager/node_modules/steamcommunity/components/users.js:248:38)
    at TradeOfferManager.loadInventory (/root/bot/node_modules/steam-tradeoffer-manager/lib/index.js:118:18)
    at Object.<anonymous> (/root/bot/bot.js:58:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

3. 
var SteamUser         = require('steam-user');
var TradeOfferManager = require('steam-tradeoffer-manager'); // Only required if you're using trade offers


var appid = {
    CSGO:  730,
    Steam: 753
};

var contextid = {
    CSGO:  2,
    Steam: 6
}

var client = new SteamUser();
var offers = new TradeOfferManager({
    steam:        client,
    language:     "en", // English item descriptions
    pollInterval: 10000, // (Poll every 10 seconds (10,000 ms)
    cancelTime:   300000 // Expire any outgoing trade offers that have been up for 5+ minutes (300,000 ms)
});


client.logOn({
	"accountName": "xxxxx",
	"password": "xxxxx",
	"authCode": "xxxxx"
});

client.on('loggedOn', function (details) {
    console.log("Logged into Steam as " + client.steamID.getSteam3RenderedID());

});
 
client.on('error', function (e) {
    console.log(e);
    process.exit(1);
});

client.on('webSession', function(sessionID, cookies) {
	offers.setCookies(cookies, function(err) {
		if(err) {
			console.log(err);
			process.exit(1); // Fatal error since we couldn't get our API key
			return;
		}

		console.log("Got API key: " + offers.apiKey);
		console.log("Steam ID: " + offers.steamID);
		 console.log("Steam ID: " + offers.steamID64);
	});
});

offers.loadInventory(); //With or without parameter it returns the same error

**Comment by DoctorMcKay** [comment]
You're calling it too early. You can't call `loadInventory` before the callback of `setCookies` fires.

**Comment by Arakiri** [comment]
Thanks a lot :)
