### ISSUE TITLE
Error: HTTP error 503

### ISSUE THREAD

**Issue by jeanggi90** [DoctorMcKay/node-steam-tradeoffer-manager#90]
What does this error message mean ("Error: HTTP error 503"). I received this message when I tried to accept a trade offer.

**Comment by Aareksio** [comment]
[HTTP error 503](https://pbs.twimg.com/media/BeMUtg4CMAA59I6.jpg)

**Comment by DoctorMcKay** [comment]
http://lmgtfy.com/?q=http+error+503
