### ISSUE TITLE
how to send multiple identical goods?

### ISSUE THREAD

**Issue by nikadrenalin** [DoctorMcKay/node-steam-tradeoffer-manager#91]
Can I add the same item several times in an array use addMyItems for this?

**Comment by Aareksio** [comment]
Every item has different `id` ([CEchonItem](https://github.com/DoctorMcKay/node-steamcommunity/wiki/CEconItem#id)), you have to add them one by one.

**Comment by DoctorMcKay** [comment]
**Please direct questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

You can't have the same item in an offer multiple times. If you have multiple *copies* of the same item, then you can add it as normal. Either call `addMyItem` multiple times, or call `addMyItems` with an array containing the items you want to add.
