### ISSUE TITLE
Invalid behavior on tradeoffer cancel

### ISSUE THREAD

**Issue by ErickSkrauch** [DoctorMcKay/node-steam-tradeoffer-manager#92]
I need to implement the trade offer so that it must be completed in a minute. 
I implemented it this way:

```js
var { partnerID, itemID, token, appID } = req.body;
var offer = offersManager.createOffer(partnerID);
offer.addTheirItem({
    id: itemID,
    appid: appID,
    contextid: 2
});
offer.send('Tradeoffer created by ErickSkrauch bot', token, (error, status) => {
    console.log({ error, status });
    if (error === null) {
        setTimeout(() => {
            offer.cancel((err) => {
                if (err) {
                    console.log('Can not cancel trade offer', err);
                } else {
                    console.log('Tradeoffer successfully canceled.');
                }
            });
        }, 60 * 1000);
    }
});
```

And after 60 secounds I get error `42, NoMatch`. I handle event `newOffer` and try to compare object, that I have after create tradeoffer and object, that I got from event callback. All the same except `offer.isOurOffer` in false state, but when we create it ourselves (in code above) it is true. If we check [code](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/master/lib/classes/TradeOffer.js#L486) we can see, that depending on state of this field request url is different. When I modifie my code above to set this field to false imediately after tradeoofer created all work fine.

If in results of my English you do not understand something, do not hesitate to ask, I wiil try reformulate.

**Comment by scholtzm** [comment]
Have you considered using [`cancelTime`](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#constructoroptions)?

**Comment by ErickSkrauch** [comment]
Yes, but I need in exactly 60 seconds, rather than in the range between this value and the time of the pool. The problem is not the approach to implementation, namely the behavior library to create trade offer.

**Comment by DoctorMcKay** [comment]
So what you're saying is that `isOurOffer` is incorrectly `false` for newly-sent offers? Are you up to date?

**Comment by ErickSkrauch** [comment]
No, this flag is logicaly the correct. But Steam handle cancel request for this offer on `DeclineTradeOffer` route rather that `CancelTradeOffer`. I don't know why it work thats, but it work that.

And, as I say, when we handle `newOffer` event you have `offer` object with `isOurOffer` 	
though it's out offer.

**Comment by DoctorMcKay** [comment]
I really have no idea what you just said so I'll just test it myself when I get a chance.

**Comment by DoctorMcKay** [comment]
I just tested with code similar to yours, and it worked as expected. I don't know what your issue is, but it doesn't appear to be in the module. You have to use `CancelTradeOffer` in order to cancel a trade offer that you've sent. If you're being forced to use `DeclineTradeOffer`, then you didn't send the offer.

**Comment by ErickSkrauch** [comment]
Can you show me which code you used to test? Maybe I am missing some key concept.

**Comment by ErickSkrauch** [comment]
I've noticed that conducted work on a limited Steam account. After I bought CSGO and activated it, the library began to behave as expected.

You can check the behavior of the library on a [limited account](https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663)?

**Comment by DoctorMcKay** [comment]
Behavior on a limited account [is undefined](https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#setcookiescookies-callback).
