### ISSUE TITLE
`partner` param for accepting a trade offer appears to be unnecessary

### ISSUE THREAD

**Issue by waylaidwanderer** [DoctorMcKay/node-steam-tradeoffer-manager#93]
https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/blob/e620c12ce2caf94d550d8cd739fc6c799206bf6e/lib/classes/TradeOffer.js#L532

I was confused why https://github.com/Alex7Kom/node-steam-tradeoffers didn't have the `partner` param for accepting trade offers, but upon testing it seems unnecessary as accepting a trade works without it.

**Comment by DoctorMcKay** [comment]
![](https://mckay.media/06BnF)

Steam sends it so we do also. There are plenty of cases where Steam does something but it works without it, then everything breaks because that thing starts becoming required.
