### ISSUE TITLE
Seperate errors when accepting an offer?

### ISSUE THREAD

**Issue by Gergo4961** [DoctorMcKay/node-steam-tradeoffer-manager#95]
Hello!

I was wondering if it was possible to seperate error messages the accept function returns when a trade offer is supposed to be accepted.

For example if it returns an ,,error: http error 503" it still accepts the offer and it doesn't accept the offer if it's an error 28. This is a huge problem when you want to insert data to a mysql table and it doesn't get inserted but the offer is accepted anyway :\.

I could try messing around with it on my end but I thought I'd report this issue to you guys to see what is up with it.

~ Gergő

**Comment by DoctorMcKay** [comment]
If it returns an error, then Steam returned an error. There's no way to determine whether an error was actually an error or not.
