### ISSUE TITLE
Please try again later (26)

### ISSUE THREAD

**Issue by dolanmiu** [DoctorMcKay/node-steam-tradeoffer-manager#96]
Our server is uses ```node-steam-trade-offer``` for managing trades for our bots, but occasionally, we get these errors.

It is an **EXTREMELY** long list of ```ersult: 26```

Any idea why? Could it be the end user is spamming?

Screenshot:

![image](https://cloud.githubusercontent.com/assets/2917613/12715374/edfbcb96-c8d1-11e5-8d19-c175fe3514a5.png)

**Comment by DoctorMcKay** [comment]
You're in the wrong repository. 

https://steamerrors.com/26
