### ISSUE TITLE
CreateOffer with TradeURL

### ISSUE THREAD

**Issue by jensej** [DoctorMcKay/node-steam-tradeoffer-manager#97]
Hello.
Is any possible to createOffer only with TRADE URL?
I Trying sth like this:

`var sidd = new SteamID();
idd.universe = SteamID.Universe.PUBLIC;
sidd.type = SteamID.Type.INDIVIDUAL;
sidd.instance = SteamID.Instance.DESKTOP;
sidd.accountid = 291289832;
var offer = manager.createOffer(sidd); `

Error:  

> [ERROR-SEND]: Error: HTTP error 400

**Comment by DoctorMcKay** [comment]
**Please direct future questions to the [Steam group](https://steamcommunity.com/groups/SteamRE/discussions/3/).**

You left out the part of the code that's causing that error.

**Comment by jensej** [comment]
Error is generate by:
`sidd.accountid = row.acces;`
it is works when I do 
sidd.accountid = 291289832; 
Any Ideas?

**Comment by DoctorMcKay** [comment]
No it's not.

**Comment by jensej** [comment]
Why not????
I tested these two options and failed first and the second worked.
Maybe Is a problem with parse from DB.
This field has bigint.

**Comment by DoctorMcKay** [comment]
The error message very clearly says that you're trying to read a property `send` of `null`. I don't see any `send` in that code.

**Comment by jensej** [comment]
Sorry my fault, I forgot to edit the first post. 
Here is this error:

> [ERROR-SEND]: Error: HTTP error 400

**Comment by DoctorMcKay** [comment]
You've sent a bad request. I suspect that `row.acces` isn't defined or has a bad value.
